/**
 * PG 迁移器 —— 沿用 SQLite 侧 SCHEMA_VERSION 幂等 exec 纪律：
 *
 *   - schema.sql 全部 IF NOT EXISTS / CREATE OR REPLACE / ON CONFLICT DO NOTHING，
 *     每次启动全量重放；同一版本重复执行 = 零效果（tests 里有逐对象快照比对）。
 *   - 版本号落在 octopus_schema_version 单行表（PG 没有 user_version pragma 的等价物；
 *     语义与 SQLite `db.pragma('user_version = N')` 一致 —— 每次 apply 后 stamp）。
 *   - IDENTITY 序列 setval 同步每次 apply 都跑（P1 数据搬迁票带原 id COPY 后，
 *     下一次启动即自动对齐；BY DEFAULT 而非 ALWAYS 就是为了允许显式 id 插入）。
 *
 * 触发器判定（SQLite 8 → PG 6 保留 / 2 删除，判定依据同文件内 schema.sql 注记）：
 *   保留  prevent_audit_update / prevent_audit_delete（schedule_audit_logs）
 *   保留  prevent_scheduler_audit_update / prevent_scheduler_audit_delete
 *   保留  prevent_task_phase_acceptance_update / _delete
 *         → 四张表都是 append-only 台账，架构约束③（可执行提案必须留被裁决的记录）
 *           的 DB 层落点；PG 有 BEFORE 触发器 + RAISE 等价物，没有理由丢语义。
 *   删除  messages_after_insert / messages_after_delete
 *         → 它们唯一职责是维护 FTS5 影子表 session_memory_fts。FTS5 在下一票被
 *           pg_search BM25（messages 表上的真实索引）整体替换；在 DAO 异步票前
 *           PG 占位表没有任何读路径，继续同步 = 白写 + 下一票双倍拆除面。
 *
 * ⚠ statement_timeout 不在这里设 —— 见 config.ts 的「超时纪律」注释；本迁移器要求
 *   连接与会话可跑 DDL（部分索引/HNSW 将来在下一票出现），故测试/启动接线都用
 *   查询连接级超时，server 级保持未设。
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import type { PgClient } from './pool'

// Cross-format __dirname（与 SQLite 侧 schema.ts 同款：tsup CJS 有 __dirname，ESM 没有）
declare const __dirname: string
const _dirname: string =
  typeof __dirname !== 'undefined'
    ? __dirname
    : path.dirname(fileURLToPath(import.meta.url))

/** PG schema 独立版本轨道。本票 = 1；pg_search/搬迁各自 +1。 */
export const PG_SCHEMA_VERSION = 1

/** IDENTITY 表清单 —— 与 schema.sql 的 GENERATED BY DEFAULT AS IDENTITY 一一对应。 */
export const IDENTITY_COLUMNS: ReadonlyArray<readonly [table: string, column: string]> = [
  ['orgs', 'id'],
  ['pipeline_state', 'id'],
  ['evolution_log', 'id'],
  ['experiences', 'id'],
  ['safety_events', 'id'],
  ['insight_marks', 'id'],
]

export interface PgMigrationReport {
  version: number
  identitySequencesSynced: number
}

export function readPgSchemaSql(): string {
  // 解析双形态：
  //   · 源码直跑（vitest / dev）：_dirname = src/db/pg → ./schema.sql
  //   · tsup 打包：_dirname = dist → ./pg/schema.sql（tsup onSuccess 拷贝，
  //     与 SQLite schema.sql 同款）。必须优先 pg/ 子路径 —— dist/schema.sql
  //     是 SQLite 那份，重名但内容完全不同；下面的 PG 标记校验让误读变成响亮的
  //     错误而不是静默跑错方言。
  const candidates = [path.join(_dirname, 'pg', 'schema.sql'), path.join(_dirname, 'schema.sql')]
  const pick = candidates.find((c) => fs.existsSync(c))
  if (!pick) throw new Error(`[pg] schema.sql not found next to migrate (tried: ${candidates.join(', ')})`)
  const sqlText = fs.readFileSync(pick, 'utf-8')
  if (!/GENERATED BY DEFAULT AS IDENTITY/.test(sqlText) || /^PRAGMA/m.test(sqlText)) {
    throw new Error(`[pg] ${pick} is not the PG schema port (SQLite content detected) — check the tsup copy step`)
  }
  return sqlText
}

/**
 * 应用完整 PG schema（幂等重放）。传入的 client 可以是任意 postgres.js 实例
 * （池化的或一次性），便于测试 harness 与启动接线共用。
 */
export async function applyPgSchema(sql: PgClient): Promise<PgMigrationReport> {
  // 1) 全量 DDL+种子：单条 simple query 多语句 —— PG 把 simple 多语句包进一个
  //    隐式事务，中途失败整体回滚，不留半迁移状态。
  await sql.unsafe(readPgSchemaSql())

  // 2) IDENTITY 序列对齐（显式 id COPY 后的唯一收口点）。
  //    表名/列名是本文件常量的固定字面量（IDENTITY_COLUMNS），无注入面。
  for (const [table, column] of IDENTITY_COLUMNS) {
    await sql.unsafe(
      `SELECT setval(pg_get_serial_sequence('${table}', '${column}'), ` +
      `(SELECT COALESCE(MAX("${column}"), 0) + 1 FROM "${table}"), false)`,
    )
  }

  // 3) 版本 stamp（等价 SQLite 的 user_version pragma）
  await sql`
    CREATE TABLE IF NOT EXISTS octopus_schema_version (
      id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
      version integer NOT NULL,
      applied_at timestamptz NOT NULL DEFAULT now()
    )`
  await sql`
    INSERT INTO octopus_schema_version (id, version, applied_at)
    VALUES (1, ${PG_SCHEMA_VERSION}, now())
    ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, applied_at = now()`

  return { version: PG_SCHEMA_VERSION, identitySequencesSynced: IDENTITY_COLUMNS.length }
}
