-- =============================================================================
-- Octopus Unified Schema — PostgreSQL port (packages/server/src/db/pg/schema.sql)
-- P1 单引擎迁移：SQLite schema.sql (SCHEMA_VERSION 49) 的逐表平移。
--
-- 本文件与 SQLite 版一样幂等 —— 全部 IF NOT EXISTS / CREATE OR REPLACE /
-- ON CONFLICT DO NOTHING，重复执行零效果、可重放（migrate.ts 的 exec 纪律）。
--
-- 类型映射规则（见 .scratch/20260927-kb-roadmap/architecture.html §2）：
--   TEXT 存 ISO 时间戳      → timestamptz
--   INTEGER 存 epoch 毫秒   → bigint
--   TEXT 存 JSON 字符串     → jsonb（仅写入侧证实为 JSON 的列；混存文本的保持 text，见各行注记）
--   INTEGER 0/1 当布尔      → boolean
--   INTEGER PK AUTOINCREMENT→ bigint GENERATED BY DEFAULT AS IDENTITY
--     （BY DEFAULT 而非 ALWAYS：P1 数据搬迁票要带原 id COPY 进来；
--       搬迁/装载后由 migrate.ts 的 setval 纪律对齐序列 —— 每次 exec 都跑）
--   INSERT OR IGNORE       → INSERT ... ON CONFLICT DO NOTHING
--   FTS5 虚表 (3)          → 普通占位表 + pg_search BM25 注记（下一票替换）
--   datetime('now')        → now()
--
-- ⚠ 时区坑（搬迁票必读）：SQLite 侧同一列混着 `new Date().toISOString()`（带 Z）
--   与 `datetime('now')`（UTC 无标记）两种写法。COPY 时必须显式
--   `SET timezone = 'UTC'` 后再灌，否则无标记串会按会话时区解读。
-- =============================================================================

-- ── 触发器共用函数（append-only 账本的不可变性守卫） ─────────────────────────
CREATE OR REPLACE FUNCTION octopus_assert_append_only() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  RAISE EXCEPTION '% is append-only: % on % is blocked', TG_ARGV[0], TG_OP, TG_TABLE_NAME;
END;
$fn$;

-- =============================================================================
-- Core Tables (from main DB — schema.ts)
-- =============================================================================

-- 1. Workspaces
CREATE TABLE IF NOT EXISTS workspaces (
  id text PRIMARY KEY,
  name text NOT NULL,
  org text NOT NULL,
  description text,
  status text DEFAULT 'active',
  path text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  source text NOT NULL DEFAULT 'user',
  source_schedule_id text,
  -- schema v41 (task-scheduler-decouple): direct task ownership. No FK (S2 polymorphic convention).
  task_id text,
  archive_status text
);

-- 2. Executions
-- schema v40 (task-phase-redesign K4): + phase_index/round_index — v4 round
-- identity. NULL = v3/generic. [port] duration 是 epoch-ms 差值 → bigint。
CREATE TABLE IF NOT EXISTS executions (
  id text PRIMARY KEY,
  workspace_id text NOT NULL,
  parent_id text NOT NULL DEFAULT '0',
  child_index integer DEFAULT 0,
  workflow_ref text NOT NULL,
  workflow_name text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  gate_status text DEFAULT 'closed',
  rollback text DEFAULT 'none',
  rollback_on_error boolean DEFAULT false,          -- [port] 0/1 → bool
  input_values jsonb DEFAULT '{}'::jsonb,           -- [port] JSON text → jsonb (writer: stringify, ExecutionLifecycle/dao insert)
  var_pool jsonb DEFAULT '{}'::jsonb,
  progress integer DEFAULT 0,
  triggered_by text DEFAULT 'manual',
  node_type text NOT NULL DEFAULT 'normal',
  branch text,
  start_commit_id text,
  end_commit_id text,
  name text,
  instance_id text,
  global_session_id text,
  retry_count integer DEFAULT 0,
  pending_hooks jsonb DEFAULT '[]'::jsonb,
  approval_metadata jsonb,                          -- [port] 写入 JSON.stringify；NULL=无审批 (ExecutionLifecycle:1051 类)
  interaction_metadata jsonb,
  resume_attempts integer DEFAULT 0,
  pipeline_config jsonb DEFAULT '{}'::jsonb,        -- [port] ExecutionLifecycle:355 JSON.stringify
  chain_retry_count integer DEFAULT 0,
  preset_inputs jsonb,
  harness_status text,
  harness_summary jsonb,                            -- [port] live 库 6/6 json_valid
  budget_snapshot jsonb,                            -- [port] ExecutionLifecycle:305 JSON.stringify(wf.parsed.budget)
  phase_index integer,
  round_index integer,
  task_id text,                                     -- schema v41: execution states WHICH task it serves (no FK, S2)
  started_at timestamptz,
  completed_at timestamptz,
  duration bigint,                                  -- [port] epoch-ms 时长 → bigint
  org text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
);

-- 3. Node Executions
CREATE TABLE IF NOT EXISTS node_executions (
  id text PRIMARY KEY,
  execution_id text NOT NULL,
  node_id text NOT NULL,
  node_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  started_at timestamptz,
  completed_at timestamptz,
  duration bigint,                                  -- [port] epoch-ms
  exit_code integer,
  error text,
  vars_snapshot jsonb,                              -- [port] JSON.stringify(vars)
  outputs jsonb,                                    -- [port] live 库 145/145 json_valid
  session_id text,
  retry_count integer DEFAULT 0,
  last_retry_at timestamptz,
  parent_node_id text,
  iteration_index integer,
  harness_status text,
  harness_interventions jsonb,                      -- [port] 消费侧 JSON.parse (routes/execution.ts:237)
  FOREIGN KEY (execution_id) REFERENCES executions(id)
);

-- 4. Node Edges
CREATE TABLE IF NOT EXISTS node_edges (
  id text PRIMARY KEY,
  execution_id text NOT NULL,
  from_node_id text NOT NULL,
  to_node_id text NOT NULL,
  edge_type text NOT NULL,
  label text,
  FOREIGN KEY (execution_id) REFERENCES executions(id)
);

-- 5. Branch Executions
CREATE TABLE IF NOT EXISTS branch_executions (
  id text PRIMARY KEY,
  node_execution_id text NOT NULL,
  iteration integer,
  branch_label text,
  status text NOT NULL DEFAULT 'pending',
  started_at timestamptz,
  completed_at timestamptz,
  duration bigint,                                  -- [port] epoch-ms
  output text,
  FOREIGN KEY (node_execution_id) REFERENCES node_executions(id)
);

-- 6. Chat Sessions
CREATE TABLE IF NOT EXISTS chat_sessions (
  id text PRIMARY KEY,
  workspace_id text NOT NULL,
  title text,
  is_active boolean DEFAULT true,                   -- [port] 0/1 → bool
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  provider text DEFAULT 'claude',
  provider_session_id text
);

-- 7. Chat Messages
CREATE TABLE IF NOT EXISTS chat_messages (
  id text PRIMARY KEY,
  session_id text NOT NULL,
  role text NOT NULL,
  type text DEFAULT 'text',
  content text NOT NULL,
  metadata jsonb,                                   -- [port] live 库 31/31 json_valid
  created_at timestamptz NOT NULL
);

-- 8. Orgs
-- [port] AUTOINCREMENT → IDENTITY（BY DEFAULT：搬迁票带原 id 插入；migrate.ts 每次 setval 对齐）
CREATE TABLE IF NOT EXISTS orgs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  path text NOT NULL,
  created_at timestamptz NOT NULL
);

-- 9. Node Token Usages
-- billing NEW-r2: cost_usd 快照列已移除 —— 费用查询时现算。
CREATE TABLE IF NOT EXISTS node_token_usages (
  id text PRIMARY KEY,
  node_execution_id text NOT NULL,
  model text NOT NULL,
  input_tokens integer NOT NULL DEFAULT 0,
  output_tokens integer NOT NULL DEFAULT 0,
  cache_read_tokens integer NOT NULL DEFAULT 0,
  cache_creation_tokens integer NOT NULL DEFAULT 0,
  source text DEFAULT 'node',
  created_at timestamptz NOT NULL,
  FOREIGN KEY (node_execution_id) REFERENCES node_executions(id)
);

-- 10. Agent Events
-- [port] content/tool_input/tool_result 保持 text：live 库实测混存
--   （tool_result 3538 行中 534 非 JSON，content 100570 行中仅 7164 是 JSON）——
--   jsonb 会拒绝截断文本，强转 = 丢数据。timestamp 是 epoch-ms → bigint。
CREATE TABLE IF NOT EXISTS agent_events (
  node_execution_id text NOT NULL,
  event_order       integer NOT NULL,
  turn_index        integer NOT NULL,
  event_type        text NOT NULL,
  timestamp         bigint NOT NULL,                -- [port] epoch ms → bigint
  content           text,
  content_length    integer DEFAULT 0,
  tool_call_id      text,
  tool_name         text,
  tool_input        text,
  tool_result       text,
  tool_is_error     boolean DEFAULT false,          -- [port] 0/1 → bool
  tool_duration_ms  bigint,                         -- [port] epoch ms → bigint
  status_value      text,
  error_code        text,
  error_message     text,
  PRIMARY KEY (node_execution_id, event_order)
);

-- 11. LLM Calls
CREATE TABLE IF NOT EXISTS llm_calls (
  id                    text PRIMARY KEY,
  node_execution_id     text,                       -- v47: 可空（聊天/压缩行无执行链路）；FK 保留
  execution_id          text,
  turn_index            integer NOT NULL,
  call_index            integer NOT NULL,
  message_id            text,
  model                 text,
  stop_reason           text,
  timestamp             bigint NOT NULL,            -- [port] epoch ms → bigint
  duration_ms           bigint NOT NULL,            -- [port] epoch ms → bigint
  ttft_ms               bigint,                     -- [port] epoch ms → bigint
  input_tokens          integer NOT NULL DEFAULT 0,
  output_tokens         integer NOT NULL DEFAULT 0,
  cache_read_tokens     integer NOT NULL DEFAULT 0,
  cache_creation_tokens integer NOT NULL DEFAULT 0,
  org                   text,
  workspace_id          text,
  workflow_ref          text,
  node_id               text,
  session_id            text,
  instance_id           text,
  source_path           text,                       -- v46 (KD20/KD21)
  FOREIGN KEY (node_execution_id) REFERENCES node_executions(id)
);

-- 12. Optimization Suggestions
-- [port] applied_changes 保持 text：唯一写入点 workspace-dao:92 传 ? 绑定，
--   仓内找不到证实其为 JSON 的调用方；升级 jsonb 留给 DAO 异步票定死写入侧后做。
CREATE TABLE IF NOT EXISTS optimization_suggestions (
  id text PRIMARY KEY,
  workspace_id text NOT NULL,
  workflow_ref text NOT NULL,
  rule_name text NOT NULL,
  node_id text,
  severity text NOT NULL DEFAULT 'info',
  title text NOT NULL,
  detection text NOT NULL,
  diagnosis text NOT NULL,
  prescription text NOT NULL,
  impact_estimate text,
  status text NOT NULL DEFAULT 'pending',
  applied_at timestamptz,
  applied_changes text,
  created_at timestamptz NOT NULL,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
);

-- 13. Execution Summaries
CREATE TABLE IF NOT EXISTS execution_summaries (
  id          text PRIMARY KEY,
  execution_id text NOT NULL,
  workflow_ref text NOT NULL,
  workspace_id text NOT NULL,
  summary     text NOT NULL,
  status      text NOT NULL,
  duration_ms bigint NOT NULL,                      -- [port] epoch-ms → bigint
  failed_nodes jsonb,                               -- [port] ExecutionLifecycle:647 JSON.stringify(array)
  created_at  timestamptz NOT NULL DEFAULT now(),   -- [port] datetime('now') → now()
  FOREIGN KEY (execution_id) REFERENCES executions(id)
);

-- 14. Pipeline State
CREATE TABLE IF NOT EXISTS pipeline_state (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- [port] AUTOINCREMENT → IDENTITY
  workspace_id text NOT NULL UNIQUE,
  chain_status text NOT NULL DEFAULT 'idle',
  config_hash text,
  config_change_strategy text NOT NULL DEFAULT 'snapshot',
  last_execution_id text,
  started_at timestamptz,
  updated_at timestamptz NOT NULL,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

-- 15. Schedules — A JOB DEFINITION, nothing else. (v42 语义同 SQLite 版)
CREATE TABLE IF NOT EXISTS schedules (
  id text PRIMARY KEY,
  org text NOT NULL DEFAULT '',
  name text NOT NULL,
  cron_expression text,
  timezone text NOT NULL DEFAULT 'Asia/Shanghai',
  workspace_id text,
  workflow_ref text,
  input_values jsonb DEFAULT '{}'::jsonb,           -- [port] JSON text → jsonb
  enabled boolean NOT NULL DEFAULT true,            -- [port] 0/1 → bool
  timeout_seconds integer NOT NULL DEFAULT 3600,
  notify_on_failure boolean NOT NULL DEFAULT false, -- [port] 0/1 → bool
  notify_channel text,
  notify_target text,
  container_execution_id text,
  missed_alert_dismissed_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  next_trigger_at timestamptz,
  job_type text NOT NULL DEFAULT 'workflow',
  config jsonb NOT NULL DEFAULT '{}'::jsonb,        -- [port] JSON text → jsonb
  parallel_policy text NOT NULL DEFAULT 'skip',
  description text,
  version integer NOT NULL DEFAULT 1,
  consecutive_failures integer NOT NULL DEFAULT 0,
  max_retain integer NOT NULL DEFAULT 10,
  status text NOT NULL DEFAULT 'queued',
  claimed_at timestamptz,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
);

-- 16. Schedule Executions
CREATE TABLE IF NOT EXISTS schedule_executions (
  id text PRIMARY KEY,
  schedule_id text NOT NULL,
  execution_id text,
  status text NOT NULL DEFAULT 'triggered',
  trigger_type text NOT NULL DEFAULT 'scheduled',
  triggered_at timestamptz NOT NULL,
  timezone_offset text NOT NULL,
  timezone_iana text NOT NULL,
  duration_ms bigint,                               -- [port] epoch-ms → bigint
  skip_reason text,
  missed_reason text,
  retry_of text,
  error_summary text,
  exit_code integer,
  agent_output text,
  model_used text,
  token_usage jsonb DEFAULT '{}'::jsonb,            -- [port] JSON text → jsonb
  metadata jsonb DEFAULT '{}'::jsonb,
  triggered_by text,
  workspace_id text,
  created_at timestamptz NOT NULL,
  completed_at timestamptz,
  FOREIGN KEY (schedule_id) REFERENCES schedules(id),
  FOREIGN KEY (execution_id) REFERENCES executions(id)
);

-- 17. Schedule Audit Logs (immutable — trigger-guarded below)
CREATE TABLE IF NOT EXISTS schedule_audit_logs (
  id text PRIMARY KEY,
  action text NOT NULL,
  actor_id text,
  actor_name text NOT NULL DEFAULT 'system',
  schedule_id text,
  schedule_name text,
  workspace_id text NOT NULL,
  changes jsonb,                                    -- [port] 审计变更集；DAO 侧 JSON 串
  created_at timestamptz NOT NULL
);

-- 18. Scheduler State
CREATE TABLE IF NOT EXISTS scheduler_state (
  id integer PRIMARY KEY DEFAULT 1,
  last_heartbeat timestamptz,                       -- [port] ISO text → timestamptz
  schema_version integer NOT NULL DEFAULT 21,
  missed_alert_pending boolean NOT NULL DEFAULT false  -- [port] 0/1 → bool
);

-- 19. Scheduler Audit Logs (immutable — trigger-guarded below)
CREATE TABLE IF NOT EXISTS scheduler_audit_logs (
  id text PRIMARY KEY,
  schedule_id text,
  action text NOT NULL,
  actor text NOT NULL DEFAULT 'system',
  changes jsonb,                                    -- [port] live 库 100/100 json_valid
  ip_address text,
  workspace_id text,
  created_at timestamptz NOT NULL
);

-- 20. Schedule Workspaces
CREATE TABLE IF NOT EXISTS schedule_workspaces (
  id text PRIMARY KEY,
  schedule_id text NOT NULL,
  workspace_id text NOT NULL,
  execution_id text,
  status text NOT NULL DEFAULT 'running',
  branch_suffix text NOT NULL,
  started_at timestamptz NOT NULL,
  completed_at timestamptz,
  error text,
  FOREIGN KEY (schedule_id) REFERENCES schedules(id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  FOREIGN KEY (execution_id) REFERENCES executions(id)
);

-- =============================================================================
-- v41 单实例闩锁（同 SQLite 版；部分谓词布尔化：enabled=1 → enabled 等）
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_exec_task ON executions(task_id, created_at DESC)
  WHERE task_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ws_task ON workspaces(task_id) WHERE task_id IS NOT NULL;

-- ux_exec_task_active — 「一个任务一个在飞」的 DB 约束。
-- NOT IN (terminal) 写法是刻意的：将来新增第六种存活状态默认持锁（同 SQLite 版注释）。
CREATE UNIQUE INDEX IF NOT EXISTS ux_exec_task_active ON executions(task_id)
  WHERE task_id IS NOT NULL AND (parent_id = '0' OR phase_index IS NOT NULL)
    AND status NOT IN ('completed','completed_with_failures','failed','cancelled','aborted','skipped','rejected');
CREATE INDEX IF NOT EXISTS idx_exec_pending_claimable ON executions(created_at)
  WHERE task_id IS NOT NULL AND status = 'pending';

-- =============================================================================
-- Agent Tables (from agent_memory.db)
-- =============================================================================

-- 21. Sessions
CREATE TABLE IF NOT EXISTS sessions (
  id text PRIMARY KEY,
  org text NOT NULL,
  title text NOT NULL DEFAULT '新会话',
  clone_name text,
  perspective_clone_name text,
  session_type text NOT NULL DEFAULT 'main',
  is_active boolean NOT NULL DEFAULT true,          -- [port] 0/1 → bool
  is_deleted boolean NOT NULL DEFAULT false,        -- [port] 0/1 → bool
  scope_id text,                                    -- v38: retargeted to tasks.id
  provider_session_id text,
  last_message_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

-- 21b. Tasks (v38 一等任务域；v40 gate 状态；v41 trigger_*)
CREATE TABLE IF NOT EXISTS tasks (
  id text PRIMARY KEY,
  org text NOT NULL,
  name text NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','ready','running','awaiting_review','archiving','done','failed','aborted')),
  source_chat_session_id text,
  task_spec jsonb NOT NULL DEFAULT '{}'::jsonb,     -- [port] JSON text → jsonb
  authoring_resources jsonb NOT NULL DEFAULT '[]'::jsonb,
  resources jsonb NOT NULL DEFAULT '[]'::jsonb,
  skills jsonb NOT NULL DEFAULT '[]'::jsonb,
  project_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  workflow_ref text,
  version integer NOT NULL DEFAULT 1,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  completed_at timestamptz,
  workspace_id text,
  trigger_mode text NOT NULL DEFAULT 'manual'
    CHECK (trigger_mode IN ('manual','once','cron')),
  trigger_at timestamptz,
  cron_expression text,
  cron_timezone text NOT NULL DEFAULT 'Asia/Shanghai',
  trigger_enabled boolean NOT NULL DEFAULT true,    -- [port] 0/1 → bool
  next_fire_at timestamptz,
  last_fired_at timestamptz
  -- [B1-B5 混合期] FK 待 B6 恢复：sessions 迁 PG 后
  --   FOREIGN KEY (source_chat_session_id) REFERENCES sessions(id)
  -- 撤除理由：sessions 写路径仍在 SQLite（B5/B6 批），PG 的 sessions 恒空 =
  -- 任何带 source_chat_session_id 的 tasks 行被 PG 拒写（恢复清单见 README）
);

-- 21c. Task Phase Acceptances (v4 验收 Gate 台账, append-only — trigger-guarded)
CREATE TABLE IF NOT EXISTS task_phase_acceptances (
  id text PRIMARY KEY,
  task_id text NOT NULL,
  phase_index integer NOT NULL,
  round_index integer NOT NULL,
  decision text NOT NULL CHECK (decision IN ('accepted','rejected')),
  feedback text,
  decided_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_task_phase_acceptances_task_phase
  ON task_phase_acceptances(task_id, phase_index);

-- 22. Messages
CREATE TABLE IF NOT EXISTS messages (
  id text PRIMARY KEY,
  session_id text NOT NULL,
  role text NOT NULL,
  content text NOT NULL,
  type text NOT NULL DEFAULT 'text',
  metadata jsonb,                                   -- [port] live 库 66/66 json_valid
  tool_calls jsonb,                                 -- [port] 消费侧 JSON.parse (agent-service:153)
  is_summary boolean NOT NULL DEFAULT false,        -- [port] 0/1 → bool
  is_compressed boolean NOT NULL DEFAULT false,
  is_edited boolean NOT NULL DEFAULT false,
  source text NOT NULL DEFAULT 'main',
  created_at timestamptz NOT NULL,
  FOREIGN KEY (session_id) REFERENCES sessions(id)
);

-- 23. Clones
-- [port] ⚠ memory_scope 保持 text：SQLite DDL 默认 '[]' 是谎话 —— live 库存的是
--   'shared'/'isolated' 枚举串（clone-dao 直接透传 row.memory_scope）。映成 jsonb
--   会拒写。语义漂移已记入 P1 报告，纠正（或文档化）留给 DAO 异步票。
--   skills/workspace_ref 实测 JSON → jsonb。
CREATE TABLE IF NOT EXISTS clones (
  name text PRIMARY KEY,
  org text NOT NULL,
  type text NOT NULL DEFAULT 'user',
  status text NOT NULL DEFAULT 'active',
  persona text NOT NULL,
  skills jsonb NOT NULL DEFAULT '[]'::jsonb,
  workspace_ref jsonb NOT NULL DEFAULT '{}'::jsonb,
  memory_scope text NOT NULL DEFAULT '[]',
  current_version_id text,                            -- [port] SQLite 侧 ensureColumn(schema.ts:537) 动态列，B1 核对补齐
  last_active_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

-- 24. Evolution Log
CREATE TABLE IF NOT EXISTS evolution_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- [port] AUTOINCREMENT → IDENTITY
  skill_name text NOT NULL,
  change_type text NOT NULL,
  level text NOT NULL,
  summary text NOT NULL,
  diff_path text,
  rolled_back boolean NOT NULL DEFAULT false,       -- [port] 0/1 → bool
  org text NOT NULL,
  timestamp timestamptz NOT NULL                    -- [port] 列名叫 timestamp 但 live 值是 ISO 文本 → timestamptz
);

-- 25. Experiences (v2 — v35: +scope/scope_ref/pattern_tags/outcome/source_type/…)
CREATE TABLE IF NOT EXISTS experiences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- [port] AUTOINCREMENT → IDENTITY
  skill_name text NOT NULL,
  content text NOT NULL,
  source_session_id text,
  org text NOT NULL,
  created_at timestamptz NOT NULL,
  scope text NOT NULL DEFAULT 'agent',
  scope_ref text,
  pattern_tags jsonb DEFAULT '[]'::jsonb,           -- [port] JSON array text → jsonb
  outcome text,
  source_type text NOT NULL DEFAULT 'session',
  execution_id text,
  node_id text
);

-- 26. Safety Events
-- [port] context 保持 text：写入点是调用方给的自由文本（safety-dao 透传），
--   live 库 0 行，无 JSON 证据。
CREATE TABLE IF NOT EXISTS safety_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- [port] AUTOINCREMENT → IDENTITY
  type text NOT NULL,
  operation text NOT NULL,
  decision text NOT NULL,
  actor text NOT NULL,
  context text,
  org text NOT NULL,
  timestamp timestamptz NOT NULL                    -- [port] ISO 文本（同 evolution_log）
);

-- 27. Reports
-- [port] date 保持 text：'YYYY-MM-DD' 日期串非时间戳，且无时区语义；
--   本表与 reports_fts 一起在 pg_search 票重新设计。
-- P1 B2（p1-batch-plan §3 S8 缩微版，首战趟路）：检索面直接建在真表上 ——
--   SQLite 侧 reports_fts 是「外部内容 FTS5 虚表」且仓内零写路径（从未被填充，
--   旧 searchReports 实际恒空），不存在存量数据要搬；不再造影子占位表。
--   BM25 索引列 = 全部文本列（key_field=id 必须是第一列）；CJK 默认按字符切
--   （单字可命中，见 db/pg/README.md「pg_search 第一趟」差异清单），
--   jieba 词级切分可经 text_fields 选项开启（B3 的坑）。
CREATE TABLE IF NOT EXISTS reports (
  id text PRIMARY KEY,
  task_name text NOT NULL,
  date text NOT NULL,
  file_path text NOT NULL,
  status text NOT NULL DEFAULT 'ok',
  org text NOT NULL,
  created_at timestamptz NOT NULL
);

-- pg_search BM25（幂等重放：CREATE INDEX IF NOT EXISTS；扩展随 octopus_template
--   预装，CREATE 语句依赖 pg_search 已在 search_path —— migrate.ts 对缺扩展库
--   先行报错，不静默跳表）。
CREATE INDEX IF NOT EXISTS idx_reports_bm25 ON reports
  USING bm25 (id, task_name, date, file_path, status, org)
  WITH (key_field = 'id');

-- 28. Scheduled Job Executions
-- [port] metadata 保持 text：safety-dao 透传 row.metadata，无 stringify 证据。
CREATE TABLE IF NOT EXISTS scheduled_job_executions (
  id text PRIMARY KEY,
  job_name text NOT NULL,
  status text NOT NULL DEFAULT 'running',
  started_at timestamptz NOT NULL,
  finished_at timestamptz,
  duration_ms bigint,                               -- [port] epoch-ms → bigint
  report_path text,
  report_summary text,
  error_message text,
  trigger_type text NOT NULL DEFAULT 'cron',
  org text NOT NULL,
  metadata text
);

-- 29. Billing — 价格配置与全局计费设置
-- [port] REAL → double precision（SQLite REAL 即 f8，语义等价）。
--   valid_from/valid_to 是 epoch-ms（本地零点）→ bigint。钱的口径是查询时现算
--   （账本三件套平移票负责 llm_calls_costed 视图 —— 本票不建视图）。
CREATE TABLE IF NOT EXISTS billing_price_config (
  id                     text PRIMARY KEY,
  vendor                 text NOT NULL,
  model_id               text NOT NULL,
  input_unit_price       double precision NOT NULL,
  output_unit_price      double precision NOT NULL,
  cache_write_unit_price double precision NOT NULL,
  cache_read_unit_price  double precision NOT NULL,
  currency               text NOT NULL CHECK (currency IN ('USD','CNY')),
  valid_from             bigint,   -- epoch ms，本地零点；NULL = 不设下界
  valid_to               bigint,   -- epoch ms，本地零点；NULL = 不设上界
  created_at             timestamptz NOT NULL,
  updated_at             timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_price_catchall ON billing_price_config(model_id)
  WHERE valid_from IS NULL AND valid_to IS NULL;
CREATE INDEX IF NOT EXISTS ix_price_match ON billing_price_config(model_id, valid_from);

-- key/value 全局设置：usd_to_cny（KD7）、display_currency（KD8）。
-- [port] key/value 在 PG 非保留字（不带引号的列名合法），照平。
CREATE TABLE IF NOT EXISTS billing_setting (
  key   text PRIMARY KEY,
  value text NOT NULL
);

-- =============================================================================
-- FTS5 虚表 → 普通占位表（P1 本票）。
-- ⚠ 下一票（pg_search BM25 + jieba）会替换这三张：session_memory_fts 的
--   「触发器同步」语义届时改为 pg_search 索引 + messages 表内联投影；
--   row_id 列刻意显式建模 FTS5 的隐式 rowid（手工同步契约：experiences 用
--   experiences.id 当 rowid，见 SQLite schema.ts 的 migrateExperiencesFtsV2）。
--   占位表当前无消费者（DAO 仍走 SQLite），不建触发器 —— 8 触发器判定见
--   migrate.ts 顶部注记表。
-- =============================================================================

CREATE TABLE IF NOT EXISTS session_memory_fts (
  row_id bigint PRIMARY KEY,      -- = messages.rowid（FTS5 隐式 rowid 的显式化）
  session_id text,
  summary text,
  session_title text,
  created_at timestamptz,
  source text
);

CREATE TABLE IF NOT EXISTS experiences_fts (
  row_id bigint PRIMARY KEY,      -- = experiences.id（v2 blue-green 同步语义）
  skill_name text,
  content text,
  scope text,
  scope_ref text,
  pattern_tags text               -- 注意：FTS 列保持 text —— pattern_tags 在此是
                                  -- 「供检索的序列化标签」，不是结构化 jsonb
);

CREATE TABLE IF NOT EXISTS reports_fts (
  row_id bigint PRIMARY KEY,
  task_name text,
  content text
);

-- =============================================================================
-- Indexes — Core Tables（102 条与 SQLite schema.sql 一一对应，布尔谓词改写）
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_executions_workspace ON executions(workspace_id);
CREATE INDEX IF NOT EXISTS idx_executions_parent ON executions(parent_id);
CREATE INDEX IF NOT EXISTS idx_node_execs_execution ON node_executions(execution_id);
CREATE INDEX IF NOT EXISTS idx_node_edges_execution ON node_edges(execution_id);
CREATE INDEX IF NOT EXISTS idx_branch_execs_node ON branch_executions(node_execution_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_workspace ON chat_sessions(workspace_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_created ON chat_messages(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_node_token_usages_node ON node_token_usages(node_execution_id);
CREATE INDEX IF NOT EXISTS idx_ntu_composite ON node_token_usages(node_execution_id, model, input_tokens, output_tokens, cache_read_tokens, cache_creation_tokens);
-- agent_events: PK (node_execution_id, event_order) 左前缀覆盖 node 维度查询；
-- idx_agent_events_ts 服务 data-retention 的 timestamp 范围清理。
CREATE INDEX IF NOT EXISTS idx_agent_events_turn ON agent_events(node_execution_id, turn_index);
CREATE INDEX IF NOT EXISTS idx_agent_events_ts ON agent_events(timestamp);
CREATE INDEX IF NOT EXISTS idx_llm_calls_node ON llm_calls(node_execution_id);
CREATE INDEX IF NOT EXISTS idx_llm_calls_execution ON llm_calls(execution_id);
CREATE INDEX IF NOT EXISTS idx_llm_calls_timestamp ON llm_calls(timestamp);
CREATE INDEX IF NOT EXISTS idx_llm_calls_workspace_workflow ON llm_calls(workspace_id, workflow_ref);
CREATE INDEX IF NOT EXISTS idx_llm_calls_source_ts ON llm_calls(source_path, timestamp);
CREATE INDEX IF NOT EXISTS idx_llm_calls_session ON llm_calls(session_id);
CREATE INDEX IF NOT EXISTS idx_suggestions_workspace ON optimization_suggestions(workspace_id);
CREATE INDEX IF NOT EXISTS idx_suggestions_status ON optimization_suggestions(status);
CREATE INDEX IF NOT EXISTS idx_summaries_workflow ON execution_summaries(workflow_ref, workspace_id);
CREATE INDEX IF NOT EXISTS idx_summaries_created ON execution_summaries(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pipeline_state_status ON pipeline_state(chain_status);
CREATE INDEX IF NOT EXISTS idx_executions_chain_retry ON executions(chain_retry_count);

-- Schedules indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_schedules_org_name ON schedules(org, name) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_schedules_enabled ON schedules(enabled, deleted_at);
CREATE INDEX IF NOT EXISTS idx_schedules_next_trigger ON schedules(next_trigger_at) WHERE enabled AND deleted_at IS NULL;  -- [port] enabled=1 → enabled
CREATE INDEX IF NOT EXISTS idx_schedules_job_type ON schedules(job_type);
CREATE INDEX IF NOT EXISTS idx_schedules_enabled_type ON schedules(enabled, job_type) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_schedules_status ON schedules(status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_schedules_claimed ON schedules(claimed_at) WHERE claimed_at IS NOT NULL;

-- Schedule executions indexes
CREATE INDEX IF NOT EXISTS idx_sched_execs_schedule ON schedule_executions(schedule_id, triggered_at DESC);
CREATE INDEX IF NOT EXISTS idx_sched_execs_status ON schedule_executions(status);
CREATE INDEX IF NOT EXISTS idx_sched_execs_execution ON schedule_executions(execution_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sched_execs_unique_active ON schedule_executions(schedule_id) WHERE status IN ('triggered', 'running');
CREATE INDEX IF NOT EXISTS idx_sched_execs_schedule_status ON schedule_executions(schedule_id, status) WHERE status IN ('triggered', 'running');

-- Schedule audit indexes
CREATE INDEX IF NOT EXISTS idx_sched_audit_ws ON schedule_audit_logs(workspace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sched_audit_schedule ON schedule_audit_logs(schedule_id, created_at DESC);

-- Scheduler audit indexes
CREATE INDEX IF NOT EXISTS idx_scheduler_audit_schedule ON scheduler_audit_logs(schedule_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scheduler_audit_ws ON scheduler_audit_logs(workspace_id, created_at DESC);

-- Schedule workspaces indexes
CREATE INDEX IF NOT EXISTS idx_sched_ws_schedule ON schedule_workspaces(schedule_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sched_ws_workspace ON schedule_workspaces(workspace_id);

-- =============================================================================
-- Indexes — Agent Tables
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_sessions_org ON sessions(org);
CREATE INDEX IF NOT EXISTS idx_sessions_clone ON sessions(clone_name);
CREATE INDEX IF NOT EXISTS idx_sessions_active ON sessions(is_active) WHERE NOT is_deleted;  -- [port] =0 → NOT
CREATE INDEX IF NOT EXISTS idx_sessions_last_message ON sessions(last_message_at DESC) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_sessions_scope ON sessions(scope_id) WHERE scope_id IS NOT NULL;

-- Tasks indexes
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_org_status ON tasks(org, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_org ON tasks(org) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_source_chat_session ON tasks(source_chat_session_id) WHERE source_chat_session_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_updated ON tasks(updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_due ON tasks(next_fire_at)
  WHERE deleted_at IS NULL AND status = 'ready' AND trigger_enabled
    AND next_fire_at IS NOT NULL;                    -- [port] trigger_enabled=1 → trigger_enabled
CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_summary ON messages(is_summary) WHERE is_summary;  -- [port] =1 → 布尔谓词
CREATE INDEX IF NOT EXISTS idx_clones_org ON clones(org);
CREATE INDEX IF NOT EXISTS idx_clones_status ON clones(status);
CREATE INDEX IF NOT EXISTS idx_evolution_skill ON evolution_log(skill_name);
CREATE INDEX IF NOT EXISTS idx_evolution_org ON evolution_log(org);
CREATE INDEX IF NOT EXISTS idx_evolution_timestamp ON evolution_log(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_experiences_skill ON experiences(skill_name);
CREATE INDEX IF NOT EXISTS idx_experiences_org ON experiences(org);
CREATE INDEX IF NOT EXISTS idx_experiences_scope ON experiences(scope);
CREATE INDEX IF NOT EXISTS idx_experiences_scope_ref ON experiences(scope, scope_ref);
CREATE INDEX IF NOT EXISTS idx_experiences_source_type ON experiences(source_type);
CREATE INDEX IF NOT EXISTS idx_experiences_execution_id ON experiences(execution_id);
CREATE INDEX IF NOT EXISTS idx_experiences_org_scope_time ON experiences(org, scope, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_safety_events_org ON safety_events(org);
CREATE INDEX IF NOT EXISTS idx_safety_events_type ON safety_events(type);
CREATE INDEX IF NOT EXISTS idx_safety_events_timestamp ON safety_events(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_reports_org ON reports(org);
CREATE INDEX IF NOT EXISTS idx_reports_task ON reports(task_name);
CREATE INDEX IF NOT EXISTS idx_reports_date ON reports(date DESC);
CREATE INDEX IF NOT EXISTS idx_sje_org ON scheduled_job_executions(org);
CREATE INDEX IF NOT EXISTS idx_sje_job ON scheduled_job_executions(job_name);
CREATE INDEX IF NOT EXISTS idx_sje_started ON scheduled_job_executions(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sje_status ON scheduled_job_executions(status);

-- =============================================================================
-- Interaction Messages (schema version 31)
-- =============================================================================

CREATE TABLE IF NOT EXISTS interaction_messages (
  id text PRIMARY KEY,
  execution_id text NOT NULL,
  node_id text NOT NULL,
  role text NOT NULL,
  type text NOT NULL DEFAULT 'text',
  content text NOT NULL,
  metadata jsonb,                                   -- [port] live 库 66/66 json_valid
  created_at timestamptz NOT NULL
  -- [B1-B5 混合期] FK 待 B6 恢复：executions 迁 PG 后
  --   FOREIGN KEY (execution_id) REFERENCES executions(id)
  -- 撤除理由：executions 属 B5 事务簇（终批才迁 PG），混合期 PG 的 executions
  -- 恒空 = interaction_messages 根本无法造数（恢复清单见 README）
);

CREATE INDEX IF NOT EXISTS idx_interaction_msgs_exec_node
  ON interaction_messages(execution_id, node_id, created_at ASC);

-- =============================================================================
-- Insight Marks (evolution pipeline)
-- =============================================================================

CREATE TABLE IF NOT EXISTS insight_marks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- [port] AUTOINCREMENT → IDENTITY
  skill_name text NOT NULL,
  insight text NOT NULL,
  session_id text,
  org text NOT NULL,
  marked_at timestamptz NOT NULL DEFAULT now(),
  processed boolean NOT NULL DEFAULT false          -- [port] 0/1 → bool
);

CREATE INDEX IF NOT EXISTS idx_insight_marks_org ON insight_marks(org);
CREATE INDEX IF NOT EXISTS idx_insight_marks_processed ON insight_marks(processed);
CREATE INDEX IF NOT EXISTS idx_insight_marks_marked_at ON insight_marks(marked_at DESC);

-- =============================================================================
-- Agent Version Management (schema version 33)
-- =============================================================================

CREATE TABLE IF NOT EXISTS agent_versions (
  id text PRIMARY KEY,
  agent_name text NOT NULL,
  version text NOT NULL,
  major integer NOT NULL,
  minor integer NOT NULL,
  patch integer NOT NULL,
  stage text NOT NULL DEFAULT 'stable',
  status text NOT NULL DEFAULT 'draft',
  snapshot jsonb NOT NULL,                          -- [port] agent-version-service:202 JSON.stringify(snapshot)
  changelog text,                                   -- [port] :129 stringify(config, null, 2) —— 带缩进的 JSON 文本供人读，
                                                    --   不是检索面；保持 text 以免 jsonb 归一化吃掉缩进
  published_at timestamptz,
  published_by text,
  created_at timestamptz NOT NULL,
  UNIQUE(agent_name, version)
);

CREATE INDEX IF NOT EXISTS idx_agent_versions_name_status
  ON agent_versions(agent_name, status);
CREATE INDEX IF NOT EXISTS idx_agent_versions_name_stage
  ON agent_versions(agent_name, stage, published_at DESC);

-- =============================================================================
-- Triggers — 8 个 SQLite 触发器判定（详见 migrate.ts 顶部判定表）
--   保留 6：四张审计/台账表的 append-only 守卫（架构约束③的 DB 层落点，PG 有等价物）
--   删除 2：messages_after_insert / messages_after_delete —— 只为把 messages.is_summary=1
--     行推进 FTS5 虚表而存在；FTS5 已被「下一票 pg_search BM25」整体替换，占位表
--     在 DAO 异步票前没有任何读路径，同步触发器 = 白写。pg_search 票会把检索面
--     建成 messages 表上的真实索引，届时不存在「影子表」可同步。
-- =============================================================================

CREATE OR REPLACE TRIGGER prevent_audit_update BEFORE UPDATE ON schedule_audit_logs
  FOR EACH ROW EXECUTE FUNCTION octopus_assert_append_only('schedule_audit_logs');
CREATE OR REPLACE TRIGGER prevent_audit_delete BEFORE DELETE ON schedule_audit_logs
  FOR EACH ROW EXECUTE FUNCTION octopus_assert_append_only('schedule_audit_logs');

CREATE OR REPLACE TRIGGER prevent_scheduler_audit_update BEFORE UPDATE ON scheduler_audit_logs
  FOR EACH ROW EXECUTE FUNCTION octopus_assert_append_only('scheduler_audit_logs');
CREATE OR REPLACE TRIGGER prevent_scheduler_audit_delete BEFORE DELETE ON scheduler_audit_logs
  FOR EACH ROW EXECUTE FUNCTION octopus_assert_append_only('scheduler_audit_logs');

CREATE OR REPLACE TRIGGER prevent_task_phase_acceptance_update BEFORE UPDATE ON task_phase_acceptances
  FOR EACH ROW EXECUTE FUNCTION octopus_assert_append_only('task_phase_acceptances');
CREATE OR REPLACE TRIGGER prevent_task_phase_acceptance_delete BEFORE DELETE ON task_phase_acceptances
  FOR EACH ROW EXECUTE FUNCTION octopus_assert_append_only('task_phase_acceptances');

-- =============================================================================
-- Harness Tables (schema version 34)
-- =============================================================================

CREATE TABLE IF NOT EXISTS harness_events (
  id text PRIMARY KEY,
  execution_id text NOT NULL,
  node_id text,
  timestamp bigint NOT NULL,                        -- [port] epoch-ms → bigint
  event_type text NOT NULL,
  detector text,
  severity text,
  report_json jsonb,                                -- [port] *_json 后缀即 JSON 契约（harness-dao stringify）
  action_json jsonb,
  result_json jsonb,
  token_usage_json jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_harness_events_exec ON harness_events(execution_id);
CREATE INDEX IF NOT EXISTS idx_harness_events_time ON harness_events(timestamp);

CREATE TABLE IF NOT EXISTS harness_config (
  id text PRIMARY KEY DEFAULT 'default',
  config_yaml text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1
);

-- =============================================================================
-- Seed Data（INSERT OR IGNORE → ON CONFLICT DO NOTHING，语义不变）
-- =============================================================================

INSERT INTO orgs (name, path, created_at) VALUES ('xzf', '~/.octopus/orgs/xzf', now())
  ON CONFLICT (name) DO NOTHING;

INSERT INTO scheduler_state (id, schema_version, missed_alert_pending)
  VALUES (1, 21, false) ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- Knowledge System Tables
-- =============================================================================

CREATE TABLE IF NOT EXISTS pending_review (
  id text PRIMARY KEY,
  type text NOT NULL DEFAULT 'rule',
  source text NOT NULL DEFAULT 'system',
  source_ref text NOT NULL DEFAULT '',
  source_label text NOT NULL DEFAULT '',
  content text NOT NULL,
  target_file text NOT NULL DEFAULT '',
  scope text NOT NULL DEFAULT 'project',
  conflicts jsonb,                                  -- [port] pending-review-dao:13 注明 JSON string；extract.ts:525 stringify
  confidence double precision NOT NULL DEFAULT 0.5,
  auto_approve boolean NOT NULL DEFAULT false,      -- [port] 0/1 → bool
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  user_notes text
);

CREATE TABLE IF NOT EXISTS knowledge_effectiveness (
  rule_id text PRIMARY KEY,
  injected_count integer NOT NULL DEFAULT 0,
  helpful_count integer NOT NULL DEFAULT 0,
  not_helpful_count integer NOT NULL DEFAULT 0,
  last_injected timestamptz,
  confidence double precision NOT NULL DEFAULT 0.5
);

CREATE INDEX IF NOT EXISTS idx_pending_status ON pending_review(status);
CREATE INDEX IF NOT EXISTS idx_effectiveness_stale ON knowledge_effectiveness(injected_count, confidence, last_injected);
CREATE INDEX IF NOT EXISTS idx_pending_review_source ON pending_review(source);
CREATE INDEX IF NOT EXISTS idx_pending_review_type_status ON pending_review(type, status);

-- =============================================================================
-- Archive Tables (schema version 26)
-- =============================================================================

CREATE TABLE IF NOT EXISTS execution_archive (
  execution_id text PRIMARY KEY,
  workspace_id text NOT NULL,
  org text NOT NULL,
  workflow_name text,
  total_cost double precision DEFAULT 0,
  total_duration_ms bigint DEFAULT 0,               -- [port] epoch-ms → bigint
  node_count integer DEFAULT 0,
  success_rate double precision DEFAULT 0,
  token_breakdown jsonb,                            -- [port] archive-service:125-128 全部 JSON.stringify
  model_breakdown jsonb,
  node_summary jsonb,
  chain_info jsonb,
  status text NOT NULL,
  archived_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb                                    -- [port] archive-service:466 stringify(options.metadata)
);

CREATE INDEX IF NOT EXISTS idx_execution_archive_workspace ON execution_archive(workspace_id);
CREATE INDEX IF NOT EXISTS idx_execution_archive_org ON execution_archive(org);
CREATE INDEX IF NOT EXISTS idx_execution_archive_archived ON execution_archive(archived_at);
CREATE INDEX IF NOT EXISTS idx_execution_archive_workflow ON execution_archive(workflow_name);

-- [port] workspace_archive.metadata 保持 text：ensureColumn 加的裸 TEXT 列，
--   仓内无 stringify 写入证据（analysis_report 是 markdown 文本 —— 非 JSON，别映 jsonb）。
CREATE TABLE IF NOT EXISTS workspace_archive (
  workspace_id text PRIMARY KEY,
  org text NOT NULL,
  name text NOT NULL,
  description text,
  source text,
  execution_count integer DEFAULT 0,
  total_cost double precision DEFAULT 0,
  total_duration_ms bigint DEFAULT 0,
  created_at timestamptz,
  archived_at timestamptz NOT NULL DEFAULT now(),
  metadata text,
  extracted_experiences integer DEFAULT 0,
  extracted_skills integer DEFAULT 0,
  extracted_workflows integer DEFAULT 0,
  extracted_agents integer DEFAULT 0,
  analysis_report text,
  file_deleted boolean DEFAULT false                -- [port] 0/1 → bool
);

CREATE INDEX IF NOT EXISTS idx_workspace_archive_org ON workspace_archive(org);
CREATE INDEX IF NOT EXISTS idx_workspace_archive_archived ON workspace_archive(archived_at);

-- archive_drafts: cached analysis results（stats/token_stats/experiences/… 是 JSON 缓存；
--   analysis_report 是 markdown 文本，保持 text）
CREATE TABLE IF NOT EXISTS archive_drafts (
  workspace_id text PRIMARY KEY,
  org text NOT NULL,
  analysis_report text NOT NULL,
  experiences jsonb NOT NULL DEFAULT '[]'::jsonb,
  skills jsonb NOT NULL DEFAULT '[]'::jsonb,
  stats jsonb NOT NULL DEFAULT '{}'::jsonb,
  workflows jsonb NOT NULL DEFAULT '[]'::jsonb,
  token_stats jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
