/**
 * 路由清单快照守卫 —— B0.5 收口票 §5 方案2（routes/agent 拆 assembler）的硬性护栏。
 *
 * 枚举 app 上全部已注册 path+method，排序后与内联快照逐位比对。
 * per-domain assembler 拆分前后本快照必须逐位相等 —— 注册顺序、路径、方法
 * 任何一位漂移都会在这里红掉，比任何 review 可靠。
 *
 * 维护规则：只有当路由**本身**增删改（正常开发）才更新快照；
 * 纯重构类 PR 里本文件出现 diff = 该 PR 不干净。
 */
import { describe, it, expect } from 'vitest'
import app from '../index'

/** 排序后的 `METHOD path` 全量清单。 */
function routeList(): string[] {
  return app.routes.map((r) => `${r.method} ${r.path}`).sort()
}

describe('route manifest snapshot (B0.5 assembler-split guardrail)', () => {
  it('快照非空且结构稳定', () => {
    const list = routeList()
    expect(list.length).toBeGreaterThan(200)
    // VITEST 模式下 actuator 因 getDb() 未接线而缺席 —— 快照必须不含它（否则快照随环境漂移）
    expect(list.some((r) => r.includes('/api/actuator'))).toBe(false)
    // 具体 method 的路由不允许重复注册（ALL 条目是 use()/route() 中间件挂载，合法可重）
    const concrete = list.filter((r) => !r.startsWith('ALL '))
    const dup = concrete.filter((v, i) => concrete.indexOf(v) !== i)
    expect(dup, '重复注册的 path+method: ' + dup.join(', ')).toEqual([])
  })

  it('全量路由清单逐位相等', () => {
    expect(routeList()).toMatchInlineSnapshot(`
      [
        "ALL /*",
        "ALL /*",
        "ALL /*",
        "ALL /*",
        "ALL /api/agent/*",
        "ALL /api/agent/*",
        "ALL /api/agent/*",
        "ALL /api/resources/*",
        "DELETE /api/agent/clones/active",
        "DELETE /api/agent/sessions/:id",
        "DELETE /api/agent/skills/:name/local",
        "DELETE /api/archive/workspaces/:id/archive-draft",
        "DELETE /api/chat/global/sessions/:sessionId",
        "DELETE /api/clones/:name",
        "DELETE /api/clones/:name/files/:path{.+}",
        "DELETE /api/knowledge/file",
        "DELETE /api/repos/:name",
        "DELETE /api/resources/source/:name",
        "DELETE /api/system/billing/prices/:id",
        "DELETE /api/workspaces/:id",
        "DELETE /api/workspaces/:id/chat/sessions/:sessionId",
        "DELETE /api/workspaces/:id/executions/:executionId",
        "DELETE /api/workspaces/:id/files",
        "DELETE /api/workspaces/:id/schedules/:sid",
        "DELETE /api/workspaces/:id/workflows/:ref",
        "GET /api/agent/clones/:name/experiences",
        "GET /api/agent/config",
        "GET /api/agent/config/persona",
        "GET /api/agent/debug/assemble/:chat_id",
        "GET /api/agent/debug/log",
        "GET /api/agent/evolution/changelog",
        "GET /api/agent/evolution/experiences",
        "GET /api/agent/memory/:layer",
        "GET /api/agent/memory/search",
        "GET /api/agent/safe-mode",
        "GET /api/agent/safety/events",
        "GET /api/agent/sessions",
        "GET /api/agent/sessions/:id",
        "GET /api/agent/skills",
        "GET /api/agent/skills/:name",
        "GET /api/agent/skills/:name/diff-builtin",
        "GET /api/agent/tasks",
        "GET /api/agent/tasks/history",
        "GET /api/agent/tasks/progress",
        "GET /api/agent/tasks/reports",
        "GET /api/agent/tasks/reports/:id",
        "GET /api/agents/main/versions",
        "GET /api/agents/main/versions/:version",
        "GET /api/agents/main/versions/diff",
        "GET /api/archive/:id/summary",
        "GET /api/archive/skill-groups",
        "GET /api/archive/workspaces/:id",
        "GET /api/archive/workspaces/:id/archive-draft",
        "GET /api/chat/global/sessions",
        "GET /api/chat/global/sessions/:sessionId",
        "GET /api/clones",
        "GET /api/clones/:name",
        "GET /api/clones/:name/files",
        "GET /api/clones/:name/files/:path{.+}",
        "GET /api/clones/:name/sessions",
        "GET /api/clones/:name/sessions/:id",
        "GET /api/clones/:name/sessions/:id/running",
        "GET /api/clones/:name/versions",
        "GET /api/clones/:name/versions/:version",
        "GET /api/clones/:name/versions/diff",
        "GET /api/dashboard/leaderboard",
        "GET /api/dashboard/queue",
        "GET /api/dashboard/recent",
        "GET /api/dashboard/stats",
        "GET /api/dashboard/workflow-health",
        "GET /api/executions/:id/llm-calls",
        "GET /api/executions/:id/traces",
        "GET /api/feature-flags",
        "GET /api/knowledge/effectiveness",
        "GET /api/knowledge/file",
        "GET /api/knowledge/files",
        "GET /api/knowledge/preference",
        "GET /api/knowledge/workflows",
        "GET /api/orgs",
        "GET /api/repos",
        "GET /api/resources",
        "GET /api/resources/:type/:name",
        "GET /api/resources/:type/:name/files",
        "GET /api/resources/:type/:name/verify",
        "GET /api/resources/audit",
        "GET /api/resources/builtin",
        "GET /api/resources/source/:name",
        "GET /api/resources/source/list",
        "GET /api/resources/stats",
        "GET /api/review/pending",
        "GET /api/review/summary",
        "GET /api/sessions/:id/llm-calls",
        "GET /api/system/billing/calls",
        "GET /api/system/billing/prices",
        "GET /api/system/billing/report/breakdown",
        "GET /api/system/billing/report/ranking",
        "GET /api/system/billing/report/summary",
        "GET /api/system/billing/report/trend",
        "GET /api/system/billing/settings",
        "GET /api/system/models",
        "GET /api/workflows/built-in",
        "GET /api/workflows/built-in/:ref",
        "GET /api/workspaces",
        "GET /api/workspaces/:id",
        "GET /api/workspaces/:id/analytics",
        "GET /api/workspaces/:id/analytics/alerts",
        "GET /api/workspaces/:id/analytics/anomalies",
        "GET /api/workspaces/:id/analytics/cost",
        "GET /api/workspaces/:id/analytics/cost-analysis",
        "GET /api/workspaces/:id/analytics/execution/:executionId/logs",
        "GET /api/workspaces/:id/analytics/failure-patterns",
        "GET /api/workspaces/:id/analytics/health-summary",
        "GET /api/workspaces/:id/analytics/swarm-events/:executionId",
        "GET /api/workspaces/:id/analytics/swarm-stats",
        "GET /api/workspaces/:id/analytics/workflows/:ref",
        "GET /api/workspaces/:id/chat/sessions",
        "GET /api/workspaces/:id/chat/sessions/:sessionId",
        "GET /api/workspaces/:id/events",
        "GET /api/workspaces/:id/executions",
        "GET /api/workspaces/:id/executions/:executionId",
        "GET /api/workspaces/:id/executions/:executionId/agent-events",
        "GET /api/workspaces/:id/executions/:executionId/branches",
        "GET /api/workspaces/:id/executions/:executionId/logs",
        "GET /api/workspaces/:id/executions/:executionId/observability",
        "GET /api/workspaces/:id/executions/:executionId/repair/diagnose",
        "GET /api/workspaces/:id/executions/:executionId/state",
        "GET /api/workspaces/:id/executions/events",
        "GET /api/workspaces/:id/executions/tree",
        "GET /api/workspaces/:id/files",
        "GET /api/workspaces/:id/files/raw",
        "GET /api/workspaces/:id/harness/config",
        "GET /api/workspaces/:id/harness/events/:execId",
        "GET /api/workspaces/:id/interactions/:execId/:nodeId/messages",
        "GET /api/workspaces/:id/interactions/:execId/:nodeId/status",
        "GET /api/workspaces/:id/schedules",
        "GET /api/workspaces/:id/schedules/:sid",
        "GET /api/workspaces/:id/schedules/:sid/executions",
        "GET /api/workspaces/:id/schedules/audit-logs",
        "GET /api/workspaces/:id/schedules/permissions",
        "GET /api/workspaces/:id/suggestions",
        "GET /api/workspaces/:id/workflows",
        "GET /api/workspaces/:id/workflows/:ref",
        "GET /api/workspaces/:id/workflows/executions",
        "GET /api/workspaces/:id/workflows/executions/:execId/nodes/:nodeId/events",
        "GET /api/workspaces/:id/workflows/executions/:execId/status",
        "GET /api/workspaces/archive/status",
        "GET /api/workspaces/config/models",
        "GET /api/workspaces/importable",
        "GET /api/workspaces/repos",
        "PATCH /api/agents/main/versions/:version",
        "PATCH /api/chat/global/sessions/:sessionId",
        "PATCH /api/clones/:name/versions/:version",
        "PATCH /api/workspaces/:id/chat/sessions/:sessionId",
        "PATCH /api/workspaces/:id/files",
        "PATCH /api/workspaces/:id/schedules/:sid",
        "POST /api/agent/chat",
        "POST /api/agent/clones/:name/activate",
        "POST /api/agent/clones/:name/delegate/cancel",
        "POST /api/agent/clones/:name/merge",
        "POST /api/agent/config/test-notification",
        "POST /api/agent/evolution/experience",
        "POST /api/agent/evolution/feedback",
        "POST /api/agent/evolution/mark-insight",
        "POST /api/agent/evolution/process-marks",
        "POST /api/agent/evolution/record",
        "POST /api/agent/evolution/rollback/:id",
        "POST /api/agent/memory",
        "POST /api/agent/memory/archive",
        "POST /api/agent/memory/rebuild-fts",
        "POST /api/agent/memory/refine",
        "POST /api/agent/safe-mode/disable",
        "POST /api/agent/safe-mode/enable",
        "POST /api/agent/safety/confirm",
        "POST /api/agent/schedules/:id/execute",
        "POST /api/agent/schedules/register",
        "POST /api/agent/self-check",
        "POST /api/agent/self-check/evolve",
        "POST /api/agent/sessions",
        "POST /api/agent/sessions/:id/chat",
        "POST /api/agent/sessions/:id/stop",
        "POST /api/agent/tasks/:id/cancel",
        "POST /api/agents/main/versions",
        "POST /api/agents/main/versions/:version/rollback",
        "POST /api/archive/:id/propose",
        "POST /api/archive/workspaces/:id/archive",
        "POST /api/archive/workspaces/:id/archive-preview",
        "POST /api/chat/global/sessions",
        "POST /api/chat/global/sessions/:sessionId/generate-title",
        "POST /api/chat/global/sessions/:sessionId/messages",
        "POST /api/clones",
        "POST /api/clones/:name/files/:path{.+}",
        "POST /api/clones/:name/sessions",
        "POST /api/clones/:name/sessions/:id/chat",
        "POST /api/clones/:name/sessions/:id/stop",
        "POST /api/clones/:name/versions",
        "POST /api/clones/:name/versions/:version/rollback",
        "POST /api/knowledge/compact",
        "POST /api/knowledge/compact-preview",
        "POST /api/knowledge/generate",
        "POST /api/knowledge/rule/:id/restore",
        "POST /api/repos",
        "POST /api/repos/:name/clone",
        "POST /api/repos/:name/pull",
        "POST /api/repos/clone-missing",
        "POST /api/repos/pull-all",
        "POST /api/repos/rebuild-index",
        "POST /api/resources/activate",
        "POST /api/resources/deactivate",
        "POST /api/resources/install",
        "POST /api/resources/source/add",
        "POST /api/resources/source/analyze",
        "POST /api/resources/source/install",
        "POST /api/resources/source/sync",
        "POST /api/resources/source/update",
        "POST /api/resources/uninstall",
        "POST /api/review/:id/action",
        "POST /api/review/batch",
        "POST /api/schedules/cron/natural-language",
        "POST /api/schedules/cron/parse",
        "POST /api/system/billing/price-preview",
        "POST /api/system/billing/prices",
        "POST /api/system/models/test",
        "POST /api/system/models/test-all",
        "POST /api/workspaces",
        "POST /api/workspaces/:id/archive/retry",
        "POST /api/workspaces/:id/chat/sessions",
        "POST /api/workspaces/:id/chat/sessions/:sessionId/generate-title",
        "POST /api/workspaces/:id/chat/sessions/:sessionId/messages",
        "POST /api/workspaces/:id/executions",
        "POST /api/workspaces/:id/executions/:executionId/approve",
        "POST /api/workspaces/:id/executions/:executionId/cancel",
        "POST /api/workspaces/:id/executions/:executionId/harness-intervene",
        "POST /api/workspaces/:id/executions/:executionId/pause",
        "POST /api/workspaces/:id/executions/:executionId/repair/clear-retry",
        "POST /api/workspaces/:id/executions/:executionId/repair/intervene",
        "POST /api/workspaces/:id/executions/:executionId/repair/node/:nodeId/reset",
        "POST /api/workspaces/:id/executions/:executionId/repair/reload-workflow",
        "POST /api/workspaces/:id/executions/:executionId/repair/restore-point",
        "POST /api/workspaces/:id/executions/:executionId/repair/varpool",
        "POST /api/workspaces/:id/executions/:executionId/resume",
        "POST /api/workspaces/:id/executions/:executionId/retry",
        "POST /api/workspaces/:id/executions/:executionId/skip",
        "POST /api/workspaces/:id/executions/:executionId/start",
        "POST /api/workspaces/:id/files",
        "POST /api/workspaces/:id/files/debug-log",
        "POST /api/workspaces/:id/files/refresh",
        "POST /api/workspaces/:id/interactions/:execId/:nodeId/complete",
        "POST /api/workspaces/:id/interactions/:execId/:nodeId/messages",
        "POST /api/workspaces/:id/interactions/:execId/:nodeId/start",
        "POST /api/workspaces/:id/schedules",
        "POST /api/workspaces/:id/schedules/:sid/disable",
        "POST /api/workspaces/:id/schedules/:sid/dismiss-alert",
        "POST /api/workspaces/:id/schedules/:sid/enable",
        "POST /api/workspaces/:id/schedules/:sid/executions/:eid/retry",
        "POST /api/workspaces/:id/schedules/:sid/trigger",
        "POST /api/workspaces/:id/schedules/emergency-stop",
        "POST /api/workspaces/:id/suggestions/:sid/apply",
        "POST /api/workspaces/:id/workflows",
        "POST /api/workspaces/:id/workflows/executions/:execId/abort",
        "POST /api/workspaces/:id/workflows/validate",
        "POST /api/workspaces/import",
        "PUT /api/agent/config",
        "PUT /api/agent/config/persona",
        "PUT /api/agent/sessions/:id",
        "PUT /api/agent/skills/:name",
        "PUT /api/knowledge/file",
        "PUT /api/knowledge/preference",
        "PUT /api/repos/:name",
        "PUT /api/system/billing/prices/:id",
        "PUT /api/system/billing/settings",
        "PUT /api/system/models",
        "PUT /api/workspaces/:id",
        "PUT /api/workspaces/:id/files",
        "PUT /api/workspaces/:id/harness/config",
        "PUT /api/workspaces/:id/workflows/:ref",
      ]
    `)
  })
})
