export { parseManifest, writeManifest, parseManifestJson, writeManifestJson, findManifestEntry, findManifestGroup, type ManifestEntry, type ManifestJsonData } from "./manifest"
export { parseIndex, generateIndex, parseIndexLocalPaths, parseIndexBranches, parseIndexJson, writeIndexJson, type IndexEntry, type ProjectInfo, type KnowledgeInfoForIndex } from "./index-file"
export { inferAutoTags, AUTO_TAG_MAP } from "./tags"
export { detectKnowledge, createKnowledgeInfo, extractRepowikiDesc, extractAgentMdDesc, extractDescFromMdContent, findAgentMd, getLastCommitTime, type KnowledgeInfo } from "./knowledge"
export { resolveReposConfig, type ReposConfig } from "./repos-config"
export { cloneProject, pullProject, isDirtyWorkingTree, getCurrentBranch, type GitResult } from "./git"
export { findLocalRepo, scanExternalDirs, cloneMissingProjects } from "./scan"
export { buildProjectInfos, applyAiDesc, type ProjectInfoFull } from "./project-info"