/**
 * 逐表逐列比对 SQLite schema 与 PG schema（P1 交付物 3 的判据测试）。
 *
 * 不是快照糊弄：期望类型/可空性/默认值由本文件显式编码的**映射规则表**推导
 * （与 architecture.html §2 的类型映射规则一一对应），SQLite 侧现装 :memory:
 * 库作真值，PG 侧现建随机测试库跑迁移器。列集、可空性、主键、外键、类型、
 * 默认值语义、IDENTITY、索引名与唯一性、部分索引 DESC 语义全部结构化断言。
 *
 * CI 无 PG 服务 → 没有 OCTOPUS_PG_TEST_URL 时 describe.skip + 一行警告。
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import Database from 'better-sqlite3'
import { applySchema } from '../../schema'
import { pgTestEnabled, createTestDatabase, type PgTestDatabase } from './harness'

if (!pgTestEnabled) {
  // eslint-disable-next-line no-console
  console.warn('[pg-tests] OCTOPUS_PG_TEST_URL not set — PG schema parity tests are SKIPPED (CI has no PG service). See packages/server/src/db/pg/README.md')
}
const describePg = pgTestEnabled ? describe : describe.skip

// ── 映射规则表（architecture §2 的机器可读版） ─────────────────────────────

/** epoch 毫秒的 INTEGER 列 → bigint（int4 会溢出）。 */
const EPOCH_MS = new Set([
  'executions.duration',
  'node_executions.duration',
  'branch_executions.duration',
  'execution_summaries.duration_ms',
  'agent_events.timestamp',
  'agent_events.tool_duration_ms',
  'llm_calls.timestamp',
  'llm_calls.duration_ms',
  'llm_calls.ttft_ms',
  'harness_events.timestamp',
  'schedule_executions.duration_ms',
  'scheduled_job_executions.duration_ms',
  'execution_archive.total_duration_ms',
  'workspace_archive.total_duration_ms',
  'billing_price_config.valid_from',
  'billing_price_config.valid_to',
])

/** 0/1 当布尔的 INTEGER 列 → boolean。 */
const BOOL = new Set([
  'executions.rollback_on_error',
  'chat_sessions.is_active',
  'agent_events.tool_is_error',
  'schedules.enabled',
  'schedules.notify_on_failure',
  'sessions.is_active',
  'sessions.is_deleted',
  'tasks.trigger_enabled',
  'messages.is_summary',
  'messages.is_compressed',
  'messages.is_edited',
  'evolution_log.rolled_back',
  'insight_marks.processed',
  'pending_review.auto_approve',
  'scheduler_state.missed_alert_pending',
  'workspace_archive.file_deleted',
])

/** SQLite AUTOINCREMENT → bigint GENERATED BY DEFAULT AS IDENTITY。 */
const IDENTITY = new Set([
  'orgs.id',
  'pipeline_state.id',
  'evolution_log.id',
  'experiences.id',
  'safety_events.id',
  'insight_marks.id',
])

/**
 * 写入侧证实为 JSON 的 TEXT 列 → jsonb。
 * 反例（刻意保持 text 的判定，勿改）：
 *   agent_events.content/tool_input/tool_result — live 库实测混存非 JSON 文本
 *   clones.memory_scope — 存 'shared'/'isolated' 枚举串（DDL 默认 '[]' 是历史谎话）
 *   *.analysis_report — markdown 散文
 *   optimization_suggestions.applied_changes / safety_events.context /
 *   scheduled_job_executions.metadata / workspace_archive.metadata — 无 JSON 写入证据
 */
const JSONB = new Set([
  'executions.input_values',
  'executions.var_pool',
  'executions.pending_hooks',
  'executions.approval_metadata',
  'executions.interaction_metadata',
  'executions.pipeline_config',
  'executions.preset_inputs',
  'executions.harness_summary',
  'executions.budget_snapshot',
  'node_executions.vars_snapshot',
  'node_executions.outputs',
  'node_executions.harness_interventions',
  'chat_messages.metadata',
  'interaction_messages.metadata',
  'messages.metadata',
  'messages.tool_calls',
  'schedule_executions.token_usage',
  'schedule_executions.metadata',
  'schedule_audit_logs.changes',
  'scheduler_audit_logs.changes',
  'execution_summaries.failed_nodes',
  'pending_review.conflicts',
  'agent_versions.snapshot',
  'experiences.pattern_tags',
  'clones.skills',
  'clones.workspace_ref',
  'tasks.task_spec',
  'tasks.authoring_resources',
  'tasks.resources',
  'tasks.skills',
  'tasks.project_ids',
  'schedules.input_values',
  'schedules.config',
  'harness_events.report_json',
  'harness_events.action_json',
  'harness_events.result_json',
  'harness_events.token_usage_json',
  'execution_archive.token_breakdown',
  'execution_archive.model_breakdown',
  'execution_archive.node_summary',
  'execution_archive.chain_info',
  'execution_archive.metadata',
  'archive_drafts.experiences',
  'archive_drafts.skills',
  'archive_drafts.stats',
  'archive_drafts.workflows',
  'archive_drafts.token_stats',
])

/** SQLite 侧存 ISO 串的时间列（*_at / timestamp(ISO) / last_heartbeat / last_injected）→ timestamptz。 */
const ISO_EXTRA = new Set(['knowledge_effectiveness.last_injected', 'scheduler_state.last_heartbeat'])

/**
 * PG-only 列（SQLite 真值不存在对应物，P1 B5 票5 例外登记）。
 *   executions.seq —— SQLite 隐式 rowid DESC 单调插入序 tiebreak（findLatestTaskInstance/
 *   Instances、listTaskInstances、findTaskPhaseFirstRound 4 处）的显式对应物，
 *   bigint GENERATED BY DEFAULT AS IDENTITY；搬迁器按 rowid 序 COPY（不带此列）→
 *   seq 单调同构。**永久例外，非 B6 恢复项** —— B6 后 PG SQL 仍用 seq。
 */
const PG_ONLY_COLS: ReadonlyMap<string, string[]> = new Map([
  ['executions', ['seq']],
])
function isIsoTimestampCol(table: string, col: string): boolean {
  if (EPOCH_MS.has(`${table}.${col}`)) return false
  if (ISO_EXTRA.has(`${table}.${col}`)) return true
  if (col === 'timestamp') return table === 'evolution_log' || table === 'safety_events'
  return col.endsWith('_at')
}

function expectedPgType(table: string, col: string, sqliteType: string): string {
  const key = `${table}.${col}`
  if (sqliteType === 'REAL') return 'double precision'
  if (sqliteType === 'INTEGER') {
    if (IDENTITY.has(key)) return 'bigint'
    if (EPOCH_MS.has(key)) return 'bigint'
    if (BOOL.has(key)) return 'boolean'
    return 'integer'
  }
  if (sqliteType === 'TEXT') {
    if (JSONB.has(key)) return 'jsonb'
    if (isIsoTimestampCol(table, col)) return 'timestamptz'
    return 'text'
  }
  throw new Error(`unmapped SQLite type ${JSON.stringify(sqliteType)} on ${key}`)
}

/** 默认值语义归一：datetime('now')↔now()、剥外层括号/::cast/引号、0/1↔false/true、jsonb 比解析后结构。 */
function normalizeDefault(raw: string | null | undefined, pgType: string): string | null {
  if (raw === null || raw === undefined) return null
  let s = String(raw).trim()
  if (/^null$/i.test(s)) return null
  const paren = s.match(/^\((.*)\)$/s)
  if (paren && !/^\(.*\)$/.test(paren[1])) s = paren[1].trim()
  if (/^datetime\(\s*'now'\s*\)$/i.test(s) || /^now\(\)$/i.test(s)) return 'now()'
  s = s.replace(/::[\w" ]+$/, '')
  const quoted = s.match(/^'((?:[^']|'')*)'$/s)
  const value = quoted ? quoted[1].replace(/''/g, "'") : s
  if (pgType === 'boolean') {
    if (value === '1' || /^true$/i.test(value)) return 'true'
    if (value === '0' || /^false$/i.test(value)) return 'false'
  }
  if (pgType === 'jsonb') {
    return JSON.stringify(JSON.parse(value))
  }
  if (pgType === 'integer' || pgType === 'bigint') return String(Number(value))
  return value
}

interface SqliteCol {
  name: string
  type: string
  notnull: number
  dflt_value: string | null
  pk: number
}

describePg('PG schema parity — per-table/per-column vs SQLite', () => {
  let sqlite: Database.Database
  let pg: PgTestDatabase

  beforeAll(async () => {
    sqlite = new Database(':memory:')
    sqlite.pragma('foreign_keys = ON')
    applySchema(sqlite)
    pg = await createTestDatabase()
  }, 120_000)

  afterAll(async () => {
    sqlite?.close()
    await pg?.close()
  })

  // SQLite :memory: 上 applySchema 后仍有 FTS5 影子表（*_fts_content/_idx/…）与
  // 虚表本体；两侧统一剔除，只比 42 张普通表。
  const isFtsFamily = (n: string): boolean => /_fts(_|$)/.test(n)

  function sqliteTables(): string[] {
    return (sqlite.prepare(
      "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
    ).all() as { name: string }[])
      .map(r => r.name)
      .filter(n => !isFtsFamily(n))
  }

  function sqliteCols(table: string): SqliteCol[] {
    return sqlite.prepare(`PRAGMA table_info(${table})`).all() as SqliteCol[]
  }

  interface PgCol {
    column_name: string
    is_nullable: string
    data_type: string
    column_default: string | null
    attidentity: string
    ordinal: number
  }

  async function pgCols(table: string): Promise<PgCol[]> {
    const rows = (await pg.sql`
      SELECT a.attname AS column_name,
             CASE WHEN a.attnotnull THEN 'NO' ELSE 'YES' END AS is_nullable,
             format_type(a.atttypid, a.atttypmod) AS data_type,
             pg_get_expr(d.adbin, d.adrelid) AS column_default,
             a.attidentity::text AS attidentity,
             a.attnum AS ordinal
      FROM pg_attribute a
      LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
      WHERE a.attrelid = ${table}::regclass::oid
        AND a.attnum > 0 AND NOT a.attisdropped
      ORDER BY a.attnum
    `) as unknown as PgCol[]
    // format_type 给全称；映射规则表用简称
    return rows.map(r => ({ ...r, data_type: r.data_type === 'timestamp with time zone' ? 'timestamptz' : r.data_type }))
  }

  it('has the same 42 regular tables (PG side minus octopus_schema_version)', async () => {
    const sqliteNames = sqliteTables()
    expect(sqliteNames).toHaveLength(42)
    const pgNames = (await pg.sql`
      SELECT table_name FROM information_schema.tables
      WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
        AND table_name <> 'octopus_schema_version'
      ORDER BY table_name
    `).map(r => r.table_name as string).filter(n => !isFtsFamily(n))
    expect(pgNames).toEqual(sqliteNames)
  })

  it('per-column: name set, nullability, type mapping, default semantics, PK', async () => {
    for (const table of sqliteTables()) {
      const sCols = sqliteCols(table)
      const allPCols = await pgCols(table)
      // PG-only 列（PG_ONLY_COLS 登记）先从集合比对中剔除，其余必须逐列相等
      const pCols = allPCols.filter(c => !(PG_ONLY_COLS.get(table) ?? []).includes(c.column_name))
      // 登记名必须真是 PG 侧存在列（防止清单名写错后 filter 静默放行）
      for (const only of PG_ONLY_COLS.get(table) ?? []) {
        expect(allPCols.some(c => c.column_name === only), `${table}.${only}: registered PG-only col must exist`).toBe(true)
      }
      // 列名集合与顺序（顺序非契约，排序后比）
      expect(pCols.map(c => c.column_name).sort(), `${table}: column set`).toEqual(sCols.map(c => c.name).sort())

      for (const sc of sCols) {
        const pc = pCols.find(c => c.column_name === sc.name)
        expect(pc, `${table}.${sc.name}: missing in PG`).toBeDefined()
        if (!pc) continue
        const key = `${table}.${sc.name}`
        const want = expectedPgType(table, sc.name, sc.type)
        expect(pc.data_type, `${key}: type`).toBe(want)
        // 可空性：SQLite 语义 = declared NOT NULL 或 PK（PK 隐含非空）
        const sqliteNullable = sc.notnull === 0 && sc.pk === 0
        expect(pc.is_nullable === 'YES', `${key}: nullability`).toBe(sqliteNullable)
        // 默认值语义
        expect(
          normalizeDefault(pc.column_default, want),
          `${key}: default`,
        ).toEqual(normalizeDefault(sc.dflt_value, want))
        // IDENTITY 纪律：AUTOINCREMENT ↔ attidentity='d'（BY DEFAULT，搬迁票要带原 id）
        expect(pc.attidentity === 'd', `${key}: identity`).toBe(IDENTITY.has(key))
      }
    }
  })

  it('per-table: primary keys match', async () => {
    for (const table of sqliteTables()) {
      const sPk = sqliteCols(table).filter(c => c.pk > 0).sort((a, b) => a.pk - b.pk).map(c => c.name)
      const pPk = (await pg.sql`
        SELECT a.attname AS col
        FROM pg_index i
        JOIN pg_class c ON c.oid = i.indexrelid
        JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
        WHERE i.indrelid = ${table}::regclass::oid AND i.indisprimary
        ORDER BY array_position(i.indkey::int[], a.attnum)
      `).map(r => r.col as string)
      expect(pPk, `${table}: PK columns`).toEqual(sPk)
    }
  })

  /**
   * B1-B5 混合期刻意撤除的 PG FK（pg/schema.sql 注释撤除，恢复清单见 README「B6 FK 恢复清单」）。
   * SQLite 侧不撤（真值库保持约束原样）。本清单双向钉死：
   *   · B6 前 PG 若擅自恢复这两条 FK → 下面的 toEqual 红；
   *   · B6（sessions/executions 迁 PG + 数据灌满）后 → 删除对应条目，FK 自然回归。
   */
  const HYBRID_DROPPED_FKS: ReadonlyMap<string, string[]> = new Map([
    ['tasks', ['source_chat_session_id->sessions(id)']],
    ['interaction_messages', ['execution_id->executions(id)']],
    // P1 B4：llm_calls / node_token_usages 由 PG 直写（账本唯一写入口），
    // 但 node_executions 行生产者 ExecutionDAO 属 B5 —— 混合期撤这两条跨引擎 FK。
    ['llm_calls', ['node_execution_id->node_executions(id)']],
    ['node_token_usages', ['node_execution_id->node_executions(id)']],
    // P1 B5 票5：executions/pipeline_state（ExecutionDAO）、schedules（ScheduleConfigDAO）、
    // schedule_workspaces（ScheduleRunDAO）的行生产者已迁 PG，而被引用的 workspaces 行
    // 生产者 WorkspaceDAO 仍 SQLite（票6）—— 撤 4 条跨引擎 FK，列保留。
    ['executions', ['workspace_id->workspaces(id)']],
    ['pipeline_state', ['workspace_id->workspaces(id):CASCADE']],
    ['schedules', ['workspace_id->workspaces(id)']],
    ['schedule_workspaces', ['workspace_id->workspaces(id):CASCADE']],
  ])

  it('per-table: foreign keys match (columns, target, ON DELETE)', async () => {
    const sFks = new Map<string, string[]>()
    for (const table of sqliteTables()) {
      const row = sqlite.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name=?").get(table) as { sql: string }
      const fks: string[] = []
      for (const m of row.sql.matchAll(/FOREIGN KEY \((\w+)\) REFERENCES (\w+)\((\w+)\)( ON DELETE (\w+))?/g)) {
        fks.push(`${m[1]}->${m[2]}(${m[3]})${m[5] ? ':' + m[5].toUpperCase() : ''}`)
      }
      sFks.set(table, fks.sort())
    }
    // 撤除条目必须仍是 SQLite 真值里的 FK（防止清单名写错后 filter 静默放行）
    for (const [table, fks] of HYBRID_DROPPED_FKS) {
      for (const fk of fks) {
        expect(sFks.get(table) ?? [], `hybrid-dropped FK ${table}:${fk} must still exist in SQLite (source of truth)`).toContain(fk)
      }
    }
    const pFks = new Map<string, string[]>()
    const rows = (await pg.sql`
      SELECT src.relname AS table,
             (SELECT string_agg(a.attname, ',') FROM pg_attribute a WHERE a.attrelid = fc.conrelid AND a.attnum = ANY(fc.conkey)) AS col,
             tgt.relname AS reftable,
             (SELECT string_agg(a.attname, ',') FROM pg_attribute a WHERE a.attrelid = fc.confrelid AND a.attnum = ANY(fc.confkey)) AS refcol,
             CASE fc.confdeltype WHEN 'a' THEN '' WHEN 'c' THEN ':CASCADE' WHEN 'r' THEN ':RESTRICT' WHEN 'n' THEN ':SET NULL' WHEN 'd' THEN ':SET DEFAULT' ELSE ':' || upper(fc.confdeltype) END AS ondelete
      FROM pg_constraint fc
      JOIN pg_class src ON src.oid = fc.conrelid
      JOIN pg_class tgt ON tgt.oid = fc.confrelid
      WHERE fc.contype = 'f' AND src.relname = ANY(${[...sFks.keys()]}::text[])
    `) as unknown as Array<{ table: string; col: string; reftable: string; refcol: string; ondelete: string }>
    for (const r of rows) {
      const list = pFks.get(r.table) ?? []
      list.push(`${r.col}->${r.reftable}(${r.refcol})${r.ondelete}`)
      pFks.set(r.table, list)
    }
    for (const table of sFks.keys()) {
      const dropped = HYBRID_DROPPED_FKS.get(table) ?? []
      const expected = (sFks.get(table) ?? []).filter((f) => !dropped.includes(f))
      expect([...(pFks.get(table) ?? [])].sort(), `${table}: FKs`).toEqual(expected)
    }
  })

  it('explicit index parity: names, uniqueness, columns, DESC & partial semantics', async () => {
    const sIdx = (sqlite.prepare(
      "SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL AND sql LIKE 'CREATE%INDEX%' ORDER BY name",
    ).all() as Array<{ name: string; tbl_name: string; sql: string }>)
      .filter(r => !isFtsFamily(r.tbl_name))
    // 迁移票纪律：索引面 102 条是判据基线；任何一侧加索引必须两侧同改
    expect(sIdx.length).toBe(102)

    const pIdx = (await pg.sql`
      SELECT ic.relname AS name, t.relname AS tbl, i.indisunique AS "unique",
             i.indpred IS NOT NULL AS partial,
             (SELECT string_agg(a.attname, ',' ORDER BY x.pos)
                FROM unnest(i.indkey::int[]) WITH ORDINALITY x(attnum, pos)
                JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = x.attnum
               WHERE x.attnum > 0) AS cols,
             pg_get_indexdef(i.indexrelid) AS fulldef
      FROM pg_index i
      JOIN pg_class ic ON ic.oid = i.indexrelid
      JOIN pg_am am ON am.oid = ic.relam
      JOIN pg_class t  ON t.oid  = i.indrelid
      JOIN pg_namespace n ON n.oid = ic.relnamespace
      WHERE n.nspname = 'public'
        AND NOT EXISTS (
          SELECT 1 FROM pg_constraint pc WHERE pc.conindid = ic.oid
        )
        AND ic.relname NOT LIKE '%_key'      -- UNIQUE 约束的支撑索引（如 agent_versions）
        -- P1 B2：pg_search BM25 索引（am=bm25）是检索面，SQLite 对位物是
        -- reports_fts FTS5 虚表（下方 isFtsFamily 同款过滤理由）—— 不进 B-tree
        -- 索引名对账；判据 = 本查询返回集与 SQLite 显式索引 102 条双向相等。
        AND am.amname <> 'bm25'
      ORDER BY ic.relname
    `) as unknown as Array<{ name: string; tbl: string; unique: boolean; partial: boolean; cols: string; fulldef: string }>

    const pByName = new Map(pIdx.map(r => [r.name, r]))
    const sByName = new Map(sIdx.map(r => [r.name, r]))

    // 名字集合完全相等（双向）
    expect([...pByName.keys()].sort()).toEqual([...sByName.keys()].sort())

    for (const [name, s] of sByName) {
      const p = pByName.get(name)!
      const wantUnique = /CREATE UNIQUE/i.test(s.sql)
      expect(p.unique, `${name}: unique`).toBe(wantUnique)
      // 列集合（SQLite 侧从 index_info 取；PG 侧剥掉 DESC/NULLS 修饰再比）
      const info = sqlite.prepare(`PRAGMA index_info(${name})`).all() as Array<{ seqno: number; name: string }>
      const sCols = info.sort((a, b) => a.seqno - b.seqno).map(c => c.name).join(',')
      const pCols = p.cols.replace(/\s+(DESC|ASC)(\s+NULLS\s+(FIRST|LAST))?/gi, '').replace(/\s+/g, ' ').trim().toLowerCase()
      expect(pCols, `${name}: columns`).toBe(sCols.toLowerCase())
      // 部分索引：SQLite 有 WHERE 子句 ↔ PG indispred 非空
      expect(p.partial, `${name}: partial`).toBe(/\bWHERE\b/i.test(s.sql))
      // DESC 语义（部分索引里 created_at DESC 这类）
      if (/\w+ DESC\b/i.test(s.sql)) {
        expect(/DESC/.test(p.fulldef), `${name}: DESC ordering carried over`).toBe(true)
      }
    }
  })

  it('FTS5 placeholders retired (B3): dropped, bm25 indexes live on the real tables', async () => {
    const names = ['session_memory_fts', 'experiences_fts', 'reports_fts']
    for (const t of names) {
      const row = (await pg.sql`
        SELECT count(*)::int AS n FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = ${t}
      `)[0]
      expect(row.n, `${t}: placeholder dropped at B3 段2`).toBe(0)
    }
    // 检索面判据：三张真表上的 bm25 索引存在且 am=bm25（reports 为 B2 首例）
    const idx = (await pg.sql`
      SELECT c.relname AS name, am.amname AS am
      FROM pg_class c JOIN pg_am am ON am.oid = c.relam
      WHERE c.relname IN ('idx_messages_bm25', 'idx_experiences_bm25', 'idx_reports_bm25')
    `) as unknown as Array<{ name: string; am: string }>
    expect(idx.map(r => r.name).sort()).toEqual(
      ['idx_experiences_bm25', 'idx_messages_bm25', 'idx_reports_bm25'],
    )
    for (const r of idx) expect(r.am, `${r.name}: access method`).toBe('bm25')
  })

  it('triggers: 6 append-only guards kept, 2 FTS-sync triggers dropped', async () => {
    const kept = [
      'prevent_audit_update', 'prevent_audit_delete',
      'prevent_scheduler_audit_update', 'prevent_scheduler_audit_delete',
      'prevent_task_phase_acceptance_update', 'prevent_task_phase_acceptance_delete',
    ]
    const dropped = ['messages_after_insert', 'messages_after_delete']
    const rows = (await pg.sql`
      SELECT tgname FROM pg_trigger
      WHERE NOT tgisinternal AND tgrelid::regclass::text = ANY(${[
        'schedule_audit_logs', 'scheduler_audit_logs', 'task_phase_acceptances', 'messages',
      ]}::text[])
    `).map(r => r.tgname as string)
    expect(rows.sort()).toEqual(kept.sort())
    for (const t of dropped) expect(rows).not.toContain(t)

    // 保留触发器真的在挡 UPDATE（守卫没成哑弹）
    await expect(pg.sql`INSERT INTO task_phase_acceptances (id, task_id, phase_index, round_index, decision, decided_at)
      VALUES ('t-1', 'task-x', 0, 0, 'accepted', now())`).resolves.toBeTruthy()
    await expect(pg.sql`UPDATE task_phase_acceptances SET feedback = 'x' WHERE id = 't-1'`)
      .rejects.toThrow(/append-only/)
    await pg.sql`DELETE FROM task_phase_acceptances`.catch(() => { /* append-only 守卫同样挡 DELETE */ })
  })
})
