/**
 * ExecutionDAO — 执行域（executions/node_executions/node_edges/branch_executions/
 * agent_events/execution_summaries/pipeline_state + 级联删）。
 * P1 B5 票5：better-sqlite3（143 stmt）→ postgres.js（BasePgDAO）。
 *
 * 行形态契约（pg-mappers 出口归一，旧 Row 接口不动直到 B6）：
 *   - *_at: PG timestamptz(Date) ↔ 旧 ISO 文本 —— iso()/isoOrNull()。
 *   - jsonb 列（var_pool/input_values/pipeline_config/outputs/…）↔ 旧 JSON 文本 —— jsonStr()。
 *   - duration/timestamp/tool_duration_ms/duration_ms: PG bigint(string) ↔ 旧 number —— num()/numOrNull()。
 *   - rollback_on_error/tool_is_error: PG boolean ↔ 旧 0/1 —— flag()/bool()（写侧裸 0/1 静默 false 雷区）。
 *   - 读侧 SELECT * 一律经 fromExec/fromNe/fromAe/fromBe/fromEs/fromPs 归一，
 *     调用方与 route 快照零语义漂移。
 *
 * 方言改写（本批）：
 *   - S1 lastInsertRowid → 本 DAO 无 RETURNING 需求，run 语义 { changes }。
 *   - S3 `INSERT OR IGNORE` ×3 → `ON CONFLICT DO NOTHING`（PG 原生，无需冲突目标）。
 *   - S9 insertAgentEventBatch named-@ 逐行循环 + DAO 内事务 → 一条多行 VALUES 批量
 *     （单语句天然原子，事务随形消失）。replaceMergedEvents 复用同一批量构造器。
 *   - datetime('now', '-N days') → now() - make_interval(days => ?::int)。
 *   - julianday(a)-julianday(b) → EXTRACT(EPOCH FROM (a - b)) * 1000。
 *   - DATE(created_at) → to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD')（UTC 口径同旧）。
 *   - CAST(... AS REAL) → ::double precision（REAL 是 float4，保 double 语义）。
 *   - 裸别名进 HAVING（PG 不允许）→ 聚合表达式原地重写（getWorkflowHealth/findFlakyNodeStats）。
 *   - ORDER BY 可空列对齐 SQLite（NULL 最小）：ASC → NULLS FIRST；DESC → NULLS LAST。
 *   - json_patch(RFC7396 merge-patch) ×2 → `COALESCE(var_pool,'{}'::jsonb) || ?::jsonb`。
 *     裁决依据见下方 setLaunchStatus/retireLaunch 注释：两处 patch 均为平铺单键标量值
 *     {"error": <string>}，递归 merge 与顶层键覆盖在此形状下逐键等值，近似安全。
 *   - rowid 单调次序 tiebreak ×4 → 显式 seq 列（pg/schema.sql executions.seq
 *     bigint GENERATED BY DEFAULT AS IDENTITY；schema-parity 例外清单 PG_ONLY_COLS）。
 *     混合期数据由搬迁器按 SQLite rowid 序灌入，seq 单调与旧 tiebreak 同构。
 *   - `pending_hooks != '[]'` 文本比较 → `'[]'::jsonb` 比较。
 *   - tool_is_error = 1 → = true。
 *
 * 事务红线（4 处 DAO 内事务全部 tx 化，体内只经 tx 句柄构造的兄弟实例）：
 *   replaceMergedEvents / cascadeDeleteByWorkspace / cascadeDeleteExecution ——
 *   `const t = new ExecutionDAO(tx)`（同访问域可用 protected q/exec）；体内禁 this.*（池根句柄 = 逃逸提交）。
 *   insertAgentEventBatch 的事务随 S9 多行 VALUES 消灭。
 *   cascadeDeleteByWorkspace 新增 schedule_workspaces.execution_id 置 NULL 先行 ——
 *   PG FK 即时生效（SQLite 侧该 FK 同为 ON，删除序此前只是恰好没踩到）。
 *
 * 混合期（B5→B6）：workspaces 行生产者仍 SQLite —— JOIN workspaces 的读路径
 * （findWorkspacePath、getQueueItems、findByOrgWithWorkspace 等）读 PG 快照表，
 * 与 B4 账本读侧同一已裁决过渡态。executions/pipeline_state/schedules/
 * schedule_workspaces → workspaces(id) 四条 FK 已在 pg/schema.sql 注释撤除
 * （README「B6 FK 恢复清单」登记，schema-parity HYBRID_DROPPED_FKS 同步）。
 */
import { BasePgDAO, type PgSql } from "./base-pg"
import { iso, isoOrNull, jsonStr, num, numOrNull, flag, bool } from "./pg-mappers"
import { buildTurnBoundaries, deriveTurnForTs, toEpochMs } from "../../turn-index"
import type {
  ExecutionRow, NodeExecutionRow, NodeEdgeRow, BranchExecutionRow,
  AgentEventRow, ExecutionSummaryRow, PipelineStateRow,
} from "../types"

// ── PG 原始行 + 出口归一 mapper（契约列类型不动直到 B6）────────────────────

type PgDate = Date | string
type PgNum = string | number

interface ExecPg {
  id: string; workspace_id: string; parent_id: string; child_index: number | null
  workflow_ref: string; workflow_name: string; status: string; gate_status: string | null
  rollback: string | null; rollback_on_error: boolean | number
  input_values: unknown; var_pool: unknown; progress: number | null
  triggered_by: string | null; node_type: string; branch: string | null
  start_commit_id: string | null; end_commit_id: string | null; name: string | null
  instance_id: string | null; global_session_id: string | null; retry_count: number | null
  pending_hooks: unknown; approval_metadata: unknown; interaction_metadata: unknown
  resume_attempts: number | null; pipeline_config: unknown; chain_retry_count: number | null
  preset_inputs: unknown; harness_status: string | null; harness_summary: unknown
  budget_snapshot: unknown; phase_index: number | null; round_index: number | null
  task_id: string | null
  started_at: PgDate | null; completed_at: PgDate | null
  duration: PgNum | null; org: string; created_at: PgDate; updated_at: PgDate
}

function fromExec(r: ExecPg): ExecutionRow {
  return {
    id: r.id, workspace_id: r.workspace_id, parent_id: r.parent_id, child_index: r.child_index ?? 0,
    workflow_ref: r.workflow_ref, workflow_name: r.workflow_name, status: r.status,
    gate_status: r.gate_status ?? "closed", rollback: r.rollback ?? "none",
    rollback_on_error: flag(r.rollback_on_error),
    input_values: jsonStr(r.input_values) ?? "{}", var_pool: jsonStr(r.var_pool) ?? "{}",
    progress: r.progress ?? 0, triggered_by: r.triggered_by ?? "manual",
    node_type: r.node_type, branch: r.branch,
    start_commit_id: r.start_commit_id, end_commit_id: r.end_commit_id,
    name: r.name, instance_id: r.instance_id, global_session_id: r.global_session_id,
    retry_count: r.retry_count ?? 0,
    pending_hooks: jsonStr(r.pending_hooks) ?? "[]",
    approval_metadata: jsonStr(r.approval_metadata), interaction_metadata: jsonStr(r.interaction_metadata),
    resume_attempts: r.resume_attempts ?? 0,
    pipeline_config: jsonStr(r.pipeline_config) ?? "{}",
    chain_retry_count: r.chain_retry_count ?? 0,
    preset_inputs: jsonStr(r.preset_inputs), harness_status: r.harness_status,
    harness_summary: jsonStr(r.harness_summary), budget_snapshot: jsonStr(r.budget_snapshot),
    phase_index: r.phase_index, round_index: r.round_index, task_id: r.task_id,
    started_at: isoOrNull(r.started_at), completed_at: isoOrNull(r.completed_at),
    duration: numOrNull(r.duration), org: r.org,
    created_at: iso(r.created_at), updated_at: iso(r.updated_at),
  }
}

interface NePg {
  id: string; execution_id: string; node_id: string; node_type: string; status: string
  started_at: PgDate | null; completed_at: PgDate | null; duration: PgNum | null
  exit_code: number | null; error: string | null
  vars_snapshot: unknown; outputs: unknown; session_id: string | null
  retry_count: number | null; last_retry_at: PgDate | null
  parent_node_id: string | null; iteration_index: number | null
  harness_status: string | null; harness_interventions: unknown
}

function fromNe(r: NePg): NodeExecutionRow {
  return {
    id: r.id, execution_id: r.execution_id, node_id: r.node_id, node_type: r.node_type, status: r.status,
    started_at: isoOrNull(r.started_at), completed_at: isoOrNull(r.completed_at), duration: numOrNull(r.duration),
    exit_code: r.exit_code, error: r.error,
    vars_snapshot: jsonStr(r.vars_snapshot), outputs: jsonStr(r.outputs), session_id: r.session_id,
    retry_count: r.retry_count ?? 0, last_retry_at: isoOrNull(r.last_retry_at),
    parent_node_id: r.parent_node_id, iteration_index: r.iteration_index,
    harness_status: r.harness_status, harness_interventions: jsonStr(r.harness_interventions),
  }
}

interface AePg {
  node_execution_id: string; event_order: number; turn_index: number; event_type: string
  timestamp: PgNum; content: string | null; content_length: number | null
  tool_call_id: string | null; tool_name: string | null; tool_input: string | null
  tool_result: string | null; tool_is_error: boolean | number | null
  tool_duration_ms: PgNum | null; status_value: string | null
  error_code: string | null; error_message: string | null
}

function fromAe(r: AePg): AgentEventRow {
  return {
    node_execution_id: r.node_execution_id, event_order: r.event_order, turn_index: r.turn_index,
    event_type: r.event_type, timestamp: num(r.timestamp),
    content: r.content, content_length: r.content_length ?? 0,
    tool_call_id: r.tool_call_id, tool_name: r.tool_name, tool_input: r.tool_input, tool_result: r.tool_result,
    tool_is_error: flag(r.tool_is_error), tool_duration_ms: numOrNull(r.tool_duration_ms),
    status_value: r.status_value, error_code: r.error_code, error_message: r.error_message,
  }
}

interface BePg {
  id: string; node_execution_id: string; iteration: number | null; branch_label: string | null
  status: string; started_at: PgDate | null; completed_at: PgDate | null
  duration: PgNum | null; output: string | null
}

function fromBe(r: BePg): BranchExecutionRow {
  return {
    id: r.id, node_execution_id: r.node_execution_id, iteration: r.iteration, branch_label: r.branch_label,
    status: r.status, started_at: isoOrNull(r.started_at), completed_at: isoOrNull(r.completed_at),
    duration: numOrNull(r.duration), output: r.output,
  }
}

interface EsPg {
  id: string; execution_id: string; workflow_ref: string; workspace_id: string
  summary: string; status: string; duration_ms: PgNum; failed_nodes: unknown; created_at: PgDate
}

function fromEs(r: EsPg): ExecutionSummaryRow {
  return {
    id: r.id, execution_id: r.execution_id, workflow_ref: r.workflow_ref, workspace_id: r.workspace_id,
    summary: r.summary, status: r.status, duration_ms: num(r.duration_ms),
    failed_nodes: jsonStr(r.failed_nodes), created_at: iso(r.created_at),
  }
}

interface PsPg {
  id: PgNum; workspace_id: string; chain_status: string; config_hash: string | null
  config_change_strategy: string; last_execution_id: string | null
  started_at: PgDate | null; updated_at: PgDate
}

function fromPs(r: PsPg): PipelineStateRow {
  return {
    id: num(r.id), workspace_id: r.workspace_id, chain_status: r.chain_status,
    config_hash: r.config_hash, config_change_strategy: r.config_change_strategy,
    last_execution_id: r.last_execution_id, started_at: isoOrNull(r.started_at), updated_at: iso(r.updated_at),
  }
}

/** jsonb 目标的入侧规范化：空/空白文本 → 回退值（PG jsonb 拒收 ''，SQLite 旧层宽容）。 */
function jsonIn(v: string | null | undefined, fallback: string | null): string | null {
  if (v == null) return fallback
  const s = v.trim()
  return s.length > 0 ? s : fallback
}

/** outputs 列（jsonb）→ 旧 JSON.parse 语义。 */
function parseJsonObject(v: unknown): Record<string, unknown> | null {
  if (v === null || v === undefined) return null
  if (typeof v === "object") return v as Record<string, unknown>
  if (typeof v === "string") {
    if (!v) return null
    try { return JSON.parse(v) as Record<string, unknown> } catch { return null }
  }
  return null
}

// ── agent_events 批量插入（S9）──────────────────────────────────────────────

const AGENT_EVENT_COLS =
  "node_execution_id, event_order, turn_index, event_type, timestamp, content, content_length, " +
  "tool_call_id, tool_name, tool_input, tool_result, tool_is_error, tool_duration_ms, status_value, error_code, error_message"
const AGENT_EVENT_ROW_PH = "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
/** 16 列/行 → chunk 500 = 8000 参数，远低于 PG 65535 上限。 */
const AGENT_EVENT_CHUNK = 500

function agentEventParams(r: AgentEventRow): unknown[] {
  return [
    r.node_execution_id, r.event_order, r.turn_index, r.event_type, r.timestamp,
    r.content, r.content_length, r.tool_call_id, r.tool_name, r.tool_input,
    r.tool_result, bool(r.tool_is_error), r.tool_duration_ms, r.status_value, r.error_code, r.error_message,
  ]
}

export class ExecutionDAO extends BasePgDAO {
  constructor(db: PgSql) { super(db) }

  /** S9 多行 VALUES：单语句天然原子（原逐行循环 + DAO 内事务消失）。
   *  ignore=true → ON CONFLICT DO NOTHING（旧 INSERT OR IGNORE 语义）；
   *  replaceMergedEvents 走 ignore=false 保留原「唯一冲突即报错回滚」语义。 */
  private async insertAgentEvents(rows: AgentEventRow[], ignore: boolean): Promise<void> {
    for (let i = 0; i < rows.length; i += AGENT_EVENT_CHUNK) {
      const chunk = rows.slice(i, i + AGENT_EVENT_CHUNK)
      const values = chunk.map(() => AGENT_EVENT_ROW_PH).join(", ")
      await this.exec(
        `INSERT INTO agent_events (${AGENT_EVENT_COLS}) VALUES ${values}${ignore ? " ON CONFLICT DO NOTHING" : ""}`,
        chunk.flatMap(agentEventParams),
      )
    }
  }

  // ── executions ──────────────────────────────────────────────────

  async findById(id: string): Promise<ExecutionRow | null> {
    const row = await this.q1<ExecPg>("SELECT * FROM executions WHERE id = ?", [id])
    return row ? fromExec(row) : null
  }

  async listByWorkspace(workspaceId: string): Promise<ExecutionRow[]> {
    const rows = await this.q<ExecPg>(
      "SELECT * FROM executions WHERE workspace_id = ? ORDER BY created_at DESC", [workspaceId],
    )
    return rows.map(fromExec)
  }

  async findChildren(parentId: string): Promise<ExecutionRow[]> {
    const rows = await this.q<ExecPg>(
      "SELECT * FROM executions WHERE parent_id = ? ORDER BY child_index NULLS FIRST", [parentId],
    )
    return rows.map(fromExec)
  }

  async findRunningLeaves(workspaceId: string): Promise<ExecutionRow[]> {
    // 「这个工作区里跑得最深的那条」— the child predicate is workspace-scoped on
    // purpose (票03 复核). Composite children each live in their OWN workspace, so an
    // unscoped NOT EXISTS would stop treating the coordinator as a leaf the moment the
    // FIRST subunit was dispatched, and the second dispatchChild would find no parent at
    // all. Same-workspace chain children (triggerChildStep) are still excluded, which is
    // the invariant this helper was written for.
    const rows = await this.q<ExecPg>(`
      SELECT e.* FROM executions e
      WHERE e.workspace_id = ? AND e.status = 'running'
        AND NOT EXISTS (
          SELECT 1 FROM executions c
          WHERE c.parent_id = e.id AND c.workspace_id = e.workspace_id
        )
    `, [workspaceId])
    return rows.map(fromExec)
  }

  async findRootExecution(workspaceId: string): Promise<ExecutionRow | null> {
    const row = await this.q1<ExecPg>(
      "SELECT * FROM executions WHERE workspace_id = ? AND (parent_id = '0' OR parent_id IS NULL) LIMIT 1",
      [workspaceId],
    )
    return row ? fromExec(row) : null
  }

  // ── Task launches (ADR-0021) ────────────────────────────────────────
  //
  // A task run IS an executions row carrying task_id; `pending` = armed and waiting
  // behind the concurrency gate. These are the only reads the built-in task-lifecycle
  // job needs, and they are deliberately task-agnostic in the other direction: the
  // scheduler never queries them.
  //
  // [票5 裁决 a] 旧 `rowid DESC` tiebreak（同秒武装轮次的单调插入序）在 PG 无对应物，
  // 改为 executions.seq（bigint IDENTITY，pg/schema.sql）—— 搬迁器按 SQLite rowid 序
  // 灌入，seq 单调与旧语义同构。涉及 4 处（findLatestTaskInstance/Instances、
  // listTaskInstances、findTaskPhaseFirstRound）。

  /** The task's CURRENT instance = its most recent INSTANCE row, whatever its status
   *  ('pending' = queued, terminal = the previous round). NULL = never ran.
   *  Serves both the 单实例 guard and the board badge. Uses idx_exec_task
   *  (task_id, created_at DESC).
   *
   *  task-exec-tree (v44): an instance is a root OR a chained v4 round — the predicate
   *  `(parent_id = '0' OR phase_index IS NOT NULL)` is the latch's predicate, and it is
   *  the ONLY legal way to tell 「任务实例」 from a composite subunit arm (arms: parent
   *  set, phase NULL). A round's parent is the previous round, so the newest row — not
   *  the newest root — is what a human is looking at. */
  async findLatestTaskInstance(taskId: string): Promise<ExecutionRow | null> {
    const row = await this.q1<ExecPg>(
      `SELECT * FROM executions WHERE task_id = ? AND (parent_id = '0' OR phase_index IS NOT NULL)
       ORDER BY created_at DESC, seq DESC LIMIT 1`,
      [taskId],
    )
    return row ? fromExec(row) : null
  }

  /** The current instance of EACH of many tasks, in one query — the kanban's badge
   *  source. Latest instance per task by insert monotonic seq (旧 rowid 语义), which is
   *  also the tiebreak `created_at` cannot provide for two rounds armed in the same second. */
  async findLatestTaskInstances(taskIds: readonly string[]): Promise<ExecutionRow[]> {
    if (taskIds.length === 0) return []
    const ph = taskIds.map(() => "?").join(",")
    const rows = await this.q<ExecPg>(
      `SELECT e.* FROM executions e
       WHERE (e.parent_id = '0' OR e.phase_index IS NOT NULL) AND e.task_id IN (${ph})
         AND e.seq = (
           SELECT MAX(e2.seq) FROM executions e2
           WHERE e2.task_id = e.task_id AND (e2.parent_id = '0' OR e2.phase_index IS NOT NULL)
         )`,
      [...taskIds],
    )
    return rows.map(fromExec)
  }

  /** Timing rows of EVERY instance execution of many tasks, one query — the board's
   *  「实际用时」aggregate source (TasksService.runStats). Same instance predicate as
   *  findLatestTaskInstances (roots + chained v4 rounds; fan-out arms live inside their
   *  root's span and are excluded). Rows never started (armed, queued) carry no
   *  started_at and are filtered out; the sum itself is done in JS so the
   *  running-until-now term uses the server clock, not julianday parsing.
   *  v49: 顺带带出 `id` —— 同一批实例行也是「逐任务账本用量」的 execution 键源
   *  （TasksService.aiUsageFor），不再多跑一趟查询。未启动的行本就无 llm_calls，
   *  被 started_at 过滤掉不影响用量口径。 */
  async listTaskRunTimings(taskIds: readonly string[]): Promise<Array<{
    id: string
    task_id: string
    status: string
    started_at: string | null
    completed_at: string | null
  }>> {
    if (taskIds.length === 0) return []
    const ph = taskIds.map(() => "?").join(",")
    const rows = await this.q<{
      id: string; task_id: string; status: string; started_at: PgDate | null; completed_at: PgDate | null
    }>(
      `SELECT id, task_id, status, started_at, completed_at FROM executions
       WHERE (parent_id = '0' OR phase_index IS NOT NULL) AND task_id IN (${ph})
         AND started_at IS NOT NULL`,
      [...taskIds],
    )
    return rows.map(r => ({
      id: r.id, task_id: r.task_id, status: r.status,
      started_at: isoOrNull(r.started_at), completed_at: isoOrNull(r.completed_at),
    }))
  }

  /** Every instance execution of a task (roots + chained v4 rounds), newest first — the
   *  「执行历史」 read model that replaced the envelope's children[]. */
  async listTaskInstances(taskId: string, limit = 50): Promise<ExecutionRow[]> {
    const rows = await this.q<ExecPg>(
      `SELECT * FROM executions WHERE task_id = ? AND (parent_id = '0' OR phase_index IS NOT NULL)
       ORDER BY created_at DESC, seq DESC LIMIT ?`,
      [taskId, limit],
    )
    return rows.map(fromExec)
  }

  /** A round row addressed by (task, phase, round) — the acceptance ledger's join key
   *  (round_index is bumped INHERIT mode writes a new row, so this stays 1:1).
   *  No parent filter: task-exec-tree chains rounds under their predecessor, and a round
   *  is identified by its (phase, round) tag, never by being a root. */
  async findTaskRound(taskId: string, phaseIndex: number, roundIndex: number): Promise<ExecutionRow | null> {
    const row = await this.q1<ExecPg>(
      `SELECT * FROM executions
       WHERE task_id = ? AND phase_index = ? AND round_index = ?
       ORDER BY created_at DESC LIMIT 1`,
      [taskId, phaseIndex, roundIndex],
    )
    return row ? fromExec(row) : null
  }

  /** 本 phase 最早轮的「最新一条」exec 行 —— round-diff cumulative 口径（S3，
   *  2026-09-20）的 start 锚来源。轮号由 dispatchPhaseRound 保证自 1 起连续，
   *  MIN(round_index) 即首轮；同轮多条（接管/重写）取 created_at 最新 —— 与
   *  deriveTaskView 的 latestByRound 同律，锚的是那一轮真正跑过的行。 */
  async findTaskPhaseFirstRound(taskId: string, phaseIndex: number): Promise<ExecutionRow | null> {
    const row = await this.q1<ExecPg>(
      `SELECT * FROM executions
       WHERE task_id = ? AND phase_index = ?
         AND round_index = (
           SELECT MIN(round_index) FROM executions
           WHERE task_id = ? AND phase_index = ? AND round_index IS NOT NULL
         )
       ORDER BY created_at DESC, seq DESC LIMIT 1`,
      [taskId, phaseIndex, taskId, phaseIndex],
    )
    return row ? fromExec(row) : null
  }

  /** The claim queue, FIFO, over a task's roots AND its composite children (partial
   *  index idx_exec_pending_claimable). A child that overflowed the cap is parked here
   *  exactly like an armed root, so claiming only roots would strand it forever. */
  async listClaimableTaskLaunches(limit: number): Promise<ExecutionRow[]> {
    const rows = await this.q<ExecPg>(
      `SELECT * FROM executions
       WHERE task_id IS NOT NULL AND status = 'pending'
       ORDER BY created_at LIMIT ?`,
      [limit],
    )
    return rows.map(fromExec)
  }

  /** Task rows stranded in a live status whose engine is no longer running in this
   *  process — the crash/restart residue the reconciliation pass resolves. Instances
   *  only (roots + chained v4 rounds): a composite arm's fate is decided with its
   *  parent, and a chained round is an instance, not an arm (task-exec-tree v44). */
  async listLiveTaskInstancesNotIn(statuses: readonly string[]): Promise<Array<{ id: string; task_id: string; workspace_id: string; status: string }>> {
    if (statuses.length === 0) return []
    const placeholders = statuses.map(() => "?").join(",")
    return await this.q<{ id: string; task_id: string; workspace_id: string; status: string }>(
      `SELECT id, task_id, workspace_id, status FROM executions
       WHERE task_id IS NOT NULL AND (parent_id = '0' OR phase_index IS NOT NULL)
         AND status NOT IN (${placeholders})`,
      [...statuses],
    )
  }

  /** System-event status write for a launch row: flips pending→running on claim and
   *  running→terminal on finalize. NO version/optimistic-lock story here — the row is
   *  owned by the job, not by an editor (same discipline as the tasks.status mirrors).
   *
   *  `error` is merged into the row's var pool under `error` rather than into its own
   *  column: `executions` has no error column (the engine keeps node failures on
   *  node_executions), and the read model already projects var_pool.error as the badge's
   *  one-line reason. Every failure writer must pass it or the badge shows a red run with
   *  nothing to say about it.
   *
   *  [票5 裁决 b] json_patch（SQLite JSON1 内建，RFC 7396 merge-patch）→ PG `||`。
   *  语义勘察：仓内 json_patch 仅此 2 处（setLaunchStatus/retireLaunch），patch 载荷
   *  恒为 `JSON.stringify({ error })` —— 平铺单键、值为 string 标量（undefined 时
   *  stringify 直接产出 {}）。RFC7396 的递归 merge 与 jsonb `||` 顶层键覆盖对这种
   *  形状逐键等值（无嵌套对象值、无 null 删键分支：retireLaunch 的空 error 由
   *  CASE 守卫短路）→ 近似安全，取 `||`。NULLIF(var_pool,'') 在 PG 不可表达
   *  （jsonb 列存不了 ''），COALESCE(var_pool,'{}'::jsonb) 等价承接 NULL 分支。 */
  async setLaunchStatus(id: string, status: string, opts?: {
    startedAt?: string; completedAt?: string; duration?: number; error?: string | null
  }): Promise<{ changes: number }> {
    const now = new Date().toISOString()
    if (opts?.error == null) {
      return await this.exec(
        `UPDATE executions SET status = ?, updated_at = ?,
           started_at = COALESCE(?::timestamptz, started_at),
           completed_at = COALESCE(?::timestamptz, completed_at),
           duration = COALESCE(?::bigint, duration)
         WHERE id = ?`,
        [status, now, opts?.startedAt ?? null, opts?.completedAt ?? null, opts?.duration ?? null, id],
      )
    }
    return await this.exec(
      `UPDATE executions SET status = ?, updated_at = ?,
         started_at = COALESCE(?::timestamptz, started_at),
         completed_at = COALESCE(?::timestamptz, completed_at),
         duration = COALESCE(?::bigint, duration),
         var_pool = COALESCE(var_pool, '{}'::jsonb) || ?::jsonb
       WHERE id = ?`,
      [
        status, now, opts.startedAt ?? null, opts.completedAt ?? null, opts.duration ?? null,
        JSON.stringify({ error: opts.error }), id,
      ],
    )
  }

  /** Every subunit run of a task (child executions the task side armed), grouped by the
   *  caller. `task_id IS NOT NULL AND parent_id != '0' AND phase_index IS NULL` is the
   *  subunit predicate: engine chain children carry parent_id too but no task_id, and
   *  chained v4 ROUNDS carry both (task-exec-tree v44) — the phase tag is what tells a
   *  round apart from an arm. One query per read-model call, grouped in TS — the
   *  alternative (findChildren per root) is N queries for a 50-row history. */
  async listTaskChildRuns(taskId: string): Promise<ExecutionRow[]> {
    const rows = await this.q<ExecPg>(
      `SELECT * FROM executions
       WHERE task_id = ? AND parent_id != '0' AND phase_index IS NULL
       ORDER BY child_index ASC NULLS FIRST`,
      [taskId],
    )
    return rows.map(fromExec)
  }

  /** Claim a specific armed row out of the queue. Guarded on status='pending' so two
   *  overlapping job rounds (wake() + auxiliary tick) can never both launch it:
   *  changes===0 means someone else got there first.
   *
   *  `leaseAt` is the started_at this claim writes, and the caller passes it to the
   *  engine's `start(..., claimedLease)` as proof of ownership: the claim is the
   *  serializer, and `start` needs to distinguish "the row I just claimed" from "somebody
   *  else's live run". Callers that want the token generate it; the default keeps the DAO
   *  usable standalone. */
  async claimLaunch(id: string, leaseAt = new Date().toISOString()): Promise<{ changes: number }> {
    return await this.exec(
      "UPDATE executions SET status = 'running', started_at = ?, updated_at = ? WHERE id = ? AND status = 'pending'",
      [leaseAt, leaseAt, id],
    )
  }

  /** Retire an armed-but-not-started row (abort while queued / failed arming). Guarded
   *  on status='pending' so it can never touch a live run — the caller re-reads and
   *  aborts properly if the row has already started.（json_patch→|| 裁决见 setLaunchStatus） */
  async retireLaunch(id: string, status: string, error?: string): Promise<{ changes: number }> {
    const now = new Date().toISOString()
    return await this.exec(
      `UPDATE executions SET status = ?, completed_at = ?, updated_at = ?,
         var_pool = CASE WHEN ? = '' THEN var_pool
                         ELSE COALESCE(var_pool, '{}'::jsonb) || ?::jsonb END
       WHERE id = ? AND status = 'pending'`,
      [status, now, now, error ?? "", JSON.stringify({ error }), id],
    )
  }

  async insertExecution(row: Partial<ExecutionRow> & { id: string; workspace_id: string; org: string }): Promise<{ changes: number }> {
    const now = new Date().toISOString()
    return await this.exec(`
      INSERT INTO executions (
        id, workspace_id, parent_id, child_index, workflow_ref, workflow_name,
        status, gate_status, rollback, rollback_on_error, input_values, var_pool,
        progress, triggered_by, started_at, completed_at, duration, org,
        created_at, updated_at, node_type, branch, start_commit_id, end_commit_id,
        name, global_session_id, approval_metadata, interaction_metadata, chain_retry_count, preset_inputs,
        phase_index, round_index, task_id
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `, [
      row.id, row.workspace_id, row.parent_id ?? "0", row.child_index ?? 0,
      row.workflow_ref ?? "", row.workflow_name ?? "",
      row.status ?? "pending", row.gate_status ?? "closed",
      row.rollback ?? "none", bool(row.rollback_on_error ?? 0),
      jsonIn(row.input_values, "{}"), jsonIn(row.var_pool, "{}"),
      row.progress ?? 0, row.triggered_by ?? "manual",
      row.started_at ?? null, row.completed_at ?? null, row.duration ?? null,
      row.org, row.created_at ?? now, row.updated_at ?? now,
      row.node_type ?? "normal", row.branch ?? null,
      row.start_commit_id ?? null, row.end_commit_id ?? null,
      row.name ?? null, row.global_session_id ?? null,
      jsonIn(row.approval_metadata, null), jsonIn(row.interaction_metadata, null),
      row.chain_retry_count ?? 0,
      jsonIn(row.preset_inputs, null),
      row.phase_index ?? null, row.round_index ?? null,
      // ADR-0021: NULL = not a task launch (cron jobs, ad-hoc runs, chain children).
      // Set = this row IS a task instance; ux_exec_task_active then serializes it.
      row.task_id ?? null,
    ])
  }

  async updateExecution(id: string, fields: Partial<ExecutionRow>): Promise<{ changes: number }> {
    const allowed = new Set([
      "status", "gate_status", "var_pool", "progress", "started_at", "completed_at",
      "duration", "global_session_id", "approval_metadata", "interaction_metadata", "chain_retry_count",
      "preset_inputs", "name", "branch", "start_commit_id", "end_commit_id",
      "pipeline_config", "retry_count", "pending_hooks", "resume_attempts",
      "instance_id", "input_values", "budget_snapshot",
      "phase_index", "round_index",
    ])
    const sets: string[] = []
    const vals: unknown[] = []
    for (const [k, v] of Object.entries(fields)) {
      if (k === "id") continue
      if (!allowed.has(k)) throw new Error(`Disallowed column: ${k}`)
      sets.push(`${k} = ?`)
      vals.push(v)
    }
    if (sets.length === 0) return { changes: 0 }
    // PG 同列重复 SET 直接报错（SQLite 静默取后者）—— fields 已带 updated_at 时不再追加
    if (!("updated_at" in fields)) {
      sets.push("updated_at = ?")
      vals.push(new Date().toISOString())
    }
    vals.push(id)
    return await this.exec(`UPDATE executions SET ${sets.join(", ")} WHERE id = ?`, vals)
  }

  async deleteById(id: string): Promise<{ changes: number }> {
    return await this.exec("DELETE FROM executions WHERE id = ?", [id])
  }

  async countByWorkspaceAndStatus(workspaceId: string, status: string): Promise<number> {
    const row = await this.q1<{ cnt: PgNum }>(
      "SELECT COUNT(*) as cnt FROM executions WHERE workspace_id = ? AND status = ?",
      [workspaceId, status],
    )
    return num(row?.cnt)
  }

  // ── node_executions ─────────────────────────────────────────────

  async findNodeExecutions(executionId: string): Promise<NodeExecutionRow[]> {
    const rows = await this.q<NePg>("SELECT * FROM node_executions WHERE execution_id = ? ORDER BY id", [executionId])
    return rows.map(fromNe)
  }

  async findNodeExecution(executionId: string, nodeId: string): Promise<NodeExecutionRow | null> {
    const row = await this.q1<NePg>(
      "SELECT * FROM node_executions WHERE execution_id = ? AND node_id = ? LIMIT 1",
      [executionId, nodeId],
    )
    return row ? fromNe(row) : null
  }

  async findNodeOutputs(executionId: string, nodeId: string): Promise<Record<string, unknown> | null> {
    const row = await this.q1<{ outputs: unknown }>(
      "SELECT outputs FROM node_executions WHERE execution_id = ? AND node_id = ? AND status = 'completed' ORDER BY completed_at DESC NULLS LAST LIMIT 1",
      [executionId, nodeId],
    )
    return parseJsonObject(row?.outputs)
  }

  async insertNodeExecution(row: Partial<NodeExecutionRow> & { id: string; execution_id: string; node_id: string }): Promise<{ changes: number }> {
    return await this.exec(`
      INSERT INTO node_executions (
        id, execution_id, node_id, node_type, status,
        started_at, completed_at, duration, exit_code, error,
        vars_snapshot, outputs, session_id,
        parent_node_id, iteration_index
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `, [
      row.id, row.execution_id, row.node_id,
      row.node_type ?? "unknown", row.status ?? "pending",
      row.started_at ?? null, row.completed_at ?? null,
      row.duration ?? null, row.exit_code ?? null, row.error ?? null,
      jsonIn(row.vars_snapshot, null), jsonIn(row.outputs, null), row.session_id ?? null,
      row.parent_node_id ?? null, row.iteration_index ?? null,
    ])
  }

  async updateNodeExecution(id: string, fields: Partial<NodeExecutionRow>): Promise<{ changes: number }> {
    const allowed = new Set([
      "status", "started_at", "completed_at", "duration", "exit_code", "error",
      "vars_snapshot", "outputs", "session_id", "retry_count", "last_retry_at",
      "parent_node_id", "iteration_index",
    ])
    const sets: string[] = []
    const vals: unknown[] = []
    for (const [k, v] of Object.entries(fields)) {
      if (k === "id") continue
      if (!allowed.has(k)) throw new Error(`Disallowed node_execution column: ${k}`)
      sets.push(`${k} = ?`)
      vals.push(v)
    }
    if (sets.length === 0) return { changes: 0 }
    vals.push(id)
    return await this.exec(`UPDATE node_executions SET ${sets.join(", ")} WHERE id = ?`, vals)
  }

  async deleteNodeExecutionsByExecution(executionId: string): Promise<{ changes: number }> {
    return await this.exec("DELETE FROM node_executions WHERE execution_id = ?", [executionId])
  }

  // ── node_edges ──────────────────────────────────────────────────

  async findNodeEdges(executionId: string): Promise<NodeEdgeRow[]> {
    return await this.q<NodeEdgeRow>("SELECT * FROM node_edges WHERE execution_id = ?", [executionId])
  }

  async insertNodeEdge(row: Omit<NodeEdgeRow, "label"> & { label?: string | null }): Promise<{ changes: number }> {
    return await this.exec(
      "INSERT INTO node_edges (id, execution_id, from_node_id, to_node_id, edge_type, label) VALUES (?, ?, ?, ?, ?, ?)",
      [row.id, row.execution_id, row.from_node_id, row.to_node_id, row.edge_type, row.label ?? null],
    )
  }

  async deleteNodeEdgesByExecution(executionId: string): Promise<{ changes: number }> {
    return await this.exec("DELETE FROM node_edges WHERE execution_id = ?", [executionId])
  }

  // ── branch_executions ───────────────────────────────────────────

  async findBranchExecutions(executionId: string): Promise<BranchExecutionRow[]> {
    const rows = await this.q<BePg>(`
      SELECT b.* FROM branch_executions b
      JOIN node_executions n ON b.node_execution_id = n.id
      WHERE n.execution_id = ? ORDER BY b.iteration NULLS FIRST
    `, [executionId])
    return rows.map(fromBe)
  }

  async insertBranchExecution(row: Omit<BranchExecutionRow, "output"> & { output?: string | null }): Promise<{ changes: number }> {
    return await this.exec(`
      INSERT INTO branch_executions (id, node_execution_id, iteration, branch_label, status, started_at, completed_at, duration, output)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `, [row.id, row.node_execution_id, row.iteration, row.branch_label, row.status, row.started_at, row.completed_at, row.duration, row.output ?? null])
  }

  async deleteBranchExecutionsByExecution(executionId: string): Promise<{ changes: number }> {
    return await this.exec(`
      DELETE FROM branch_executions WHERE node_execution_id IN (
        SELECT id FROM node_executions WHERE execution_id = ?
      )
    `, [executionId])
  }

  // ── agent_events ────────────────────────────────────────────────

  async findAgentEvents(nodeExecutionId: string): Promise<AgentEventRow[]> {
    const rows = await this.q<AePg>(
      "SELECT * FROM agent_events WHERE node_execution_id = ? ORDER BY event_order",
      [nodeExecutionId],
    )
    return rows.map(fromAe)
  }

  async insertAgentEvent(row: AgentEventRow): Promise<{ changes: number }> {
    return await this.exec(`
      INSERT INTO agent_events (${AGENT_EVENT_COLS}) VALUES ${AGENT_EVENT_ROW_PH}
    `, agentEventParams(row))
  }

  async deleteAgentEventsByExecution(executionId: string): Promise<{ changes: number }> {
    return await this.exec(`
      DELETE FROM agent_events WHERE node_execution_id IN (
        SELECT id FROM node_executions WHERE execution_id = ?
      )
    `, [executionId])
  }

  async deleteAgentEventsByNode(nodeExecutionId: string): Promise<{ changes: number }> {
    console.log(`[ExecutionDAO] deleteAgentEventsByNode: ${nodeExecutionId}`)
    const result = await this.exec("DELETE FROM agent_events WHERE node_execution_id = ? AND event_type NOT LIKE 'harness_%' AND event_type != 'intervention_result'", [nodeExecutionId])
    console.log(`[ExecutionDAO] deleteAgentEventsByNode: deleted ${result.changes} events`)
    return result
  }

  /** Event types produced by the compaction merge — stored as full JSON for round-trip fidelity. */
  private static MERGED_EVENT_TYPES = new Set([
    "thinking_block", "text_block", "tool_call",
    "bash_output", "bash_stderr", "python_output", "python_stderr",
  ])

  /** Replace all agent events for a node with merged (compacted) events.
   *  [票5 事务红线] tx 体内全部经 `new ExecutionDAO(tx)`（t.*）—— this.* = 池根句柄，
   *  写入逃逸且照常提交（base-pg.ts 反模式钉桩）。合并插入改多行 VALUES 单语句。 */
  async replaceMergedEvents(executionId: string, nodeId: string, mergedEvents: any[]): Promise<void> {
    await this.transaction(async (tx) => {
      const t = new ExecutionDAO(tx)
      const neId = `${executionId}-${nodeId}`
      // Delete old fragmented events for this node, but preserve harness_* and intervention_result events
      await t.exec("DELETE FROM agent_events WHERE node_execution_id = ? AND event_type NOT LIKE 'harness_%' AND event_type != 'intervention_result'", [neId])
      // 权威轮次窗口：llm_calls 每回合一条、ts 与回合精确对齐，且在本方法（节点收尾
      // 后触发）之前已由 onNodeEnd 落库。合并块不带 turnIndex → 按窗口派生回合，
      // 否则旧逻辑 `e.turnIndex ?? 1` 会把任意多回合一律压成 turn_index=1。
      const callRows = await t.q<{ turn_index: number; timestamp: PgNum }>(
        "SELECT turn_index, timestamp FROM llm_calls WHERE node_execution_id = ? ORDER BY timestamp",
        [neId],
      )
      const bounds = buildTurnBoundaries(callRows.map(r => ({ turn_index: r.turn_index, timestamp: num(r.timestamp) })))
      // Build merged events（timestamp 列是 epoch-ms —— 同旧注释：ISO 串直存的历史 bug 已收口）
      const rows: AgentEventRow[] = []
      for (let i = 0; i < mergedEvents.length; i++) {
        const e = mergedEvents[i]
        const ts = toEpochMs(e.startedAt ?? e.timestamp) || Date.now()
        // For merged block types, store the full event as JSON so the read path
        // can round-trip without losing startedAt/completedAt/toolName/etc.
        const isMergedType = ExecutionDAO.MERGED_EVENT_TYPES.has(e.event)
        const content = isMergedType
          ? JSON.stringify(e)
          : (e.content ?? e.line ?? (e.lines ? e.lines.join("\n") : null))
        // 与读侧 assignTurnsToEvents 同一真相源(llm_calls 时间窗)，写读一致。
        const evMs = ts
        const turn = (bounds.length > 0 && evMs > 0) ? deriveTurnForTs(bounds, evMs) : (e.turnIndex ?? 1)
        rows.push({
          node_execution_id: neId, event_order: i, turn_index: turn, event_type: e.event, timestamp: ts,
          content, content_length: content ? content.length : 0,
          tool_call_id: e.toolCallId ?? null, tool_name: e.toolName ?? null,
          tool_input: e.input ? (typeof e.input === "string" ? e.input : JSON.stringify(e.input)) : null,
          tool_result: e.result ? (typeof e.result === "string" ? e.result : JSON.stringify(e.result)) : null,
          tool_is_error: e.isError ? 1 : 0, tool_duration_ms: e.toolDurationMs ?? null,
          status_value: null, error_code: null, error_message: null,
        })
      }
      if (rows.length > 0) await t.insertAgentEvents(rows, false)
    })
  }

  // ── execution_summaries ─────────────────────────────────────────

  async findSummariesByExecution(executionId: string): Promise<ExecutionSummaryRow[]> {
    const rows = await this.q<EsPg>(
      "SELECT * FROM execution_summaries WHERE execution_id = ?", [executionId],
    )
    return rows.map(fromEs)
  }

  async findRecentSummaries(workspaceId: string, limit: number): Promise<ExecutionSummaryRow[]> {
    const rows = await this.q<EsPg>(
      "SELECT * FROM execution_summaries WHERE workspace_id = ? ORDER BY created_at DESC LIMIT ?",
      [workspaceId, limit],
    )
    return rows.map(fromEs)
  }

  async insertSummary(row: Omit<ExecutionSummaryRow, "created_at"> & { created_at?: string }): Promise<{ changes: number }> {
    return await this.exec(`
      INSERT INTO execution_summaries (id, execution_id, workflow_ref, workspace_id, summary, status, duration_ms, failed_nodes, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `, [
      row.id, row.execution_id, row.workflow_ref, row.workspace_id,
      row.summary, row.status, row.duration_ms,
      jsonIn(row.failed_nodes, null),
      row.created_at ?? new Date().toISOString(),
    ])
  }

  async deleteSummariesByExecution(executionId: string): Promise<{ changes: number }> {
    return await this.exec("DELETE FROM execution_summaries WHERE execution_id = ?", [executionId])
  }

  // ── pipeline_state ──────────────────────────────────────────────

  async findPipelineState(workspaceId: string): Promise<PipelineStateRow | null> {
    const row = await this.q1<PsPg>("SELECT * FROM pipeline_state WHERE workspace_id = ?", [workspaceId])
    return row ? fromPs(row) : null
  }

  async findRunningPipelines(): Promise<PipelineStateRow[]> {
    const rows = await this.q<PsPg>("SELECT * FROM pipeline_state WHERE chain_status = 'running'")
    return rows.map(fromPs)
  }

  async upsertPipelineState(row: PipelineStateRow): Promise<{ changes: number }> {
    return await this.exec(`
      INSERT INTO pipeline_state (workspace_id, chain_status, config_hash, config_change_strategy, last_execution_id, started_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(workspace_id) DO UPDATE SET
        chain_status = excluded.chain_status,
        config_hash = excluded.config_hash,
        config_change_strategy = excluded.config_change_strategy,
        last_execution_id = excluded.last_execution_id,
        started_at = excluded.started_at,
        updated_at = excluded.updated_at
    `, [row.workspace_id, row.chain_status, row.config_hash, row.config_change_strategy, row.last_execution_id, row.started_at, row.updated_at])
  }

  async updatePipelineState(workspaceId: string, fields: Partial<PipelineStateRow>): Promise<{ changes: number }> {
    const sets: string[] = []
    const vals: unknown[] = []
    for (const [k, v] of Object.entries(fields)) {
      if (k === "id" || k === "workspace_id") continue
      sets.push(`${k} = ?`)
      vals.push(v)
    }
    if (sets.length === 0) return { changes: 0 }
    if (!("updated_at" in fields)) {
      sets.push("updated_at = ?")
      vals.push(new Date().toISOString())
    }
    vals.push(workspaceId)
    return await this.exec(`UPDATE pipeline_state SET ${sets.join(", ")} WHERE workspace_id = ?`, vals)
  }

  async deletePipelineState(workspaceId: string): Promise<{ changes: number }> {
    return await this.exec("DELETE FROM pipeline_state WHERE workspace_id = ?", [workspaceId])
  }

  // ── Cascade delete ──────────────────────────────────────────────

  /** [票5 事务红线] tx 体全程 t.*；新增 schedule_workspaces.execution_id 置 NULL ——
   *  PG 对 executions 的 FK 即时生效，删除被引用行必先解引用（旧 SQLite 同 FK 声明下
   *  该列此前只是恰好没有引用，删除序不变）。 */
  async cascadeDeleteByWorkspace(workspaceId: string): Promise<void> {
    await this.transaction(async (tx) => {
      const t = new ExecutionDAO(tx)
      const execIds = await t.findExecutionIdsForCascade(workspaceId)
      if (execIds.length > 0) {
        const placeholders = execIds.map(() => "?").join(",")
        const vals = execIds
        await t.exec("UPDATE schedule_workspaces SET execution_id = NULL WHERE execution_id IN (SELECT id FROM executions WHERE workspace_id = ?)", [workspaceId])
        await t.exec(`DELETE FROM agent_events WHERE node_execution_id IN (SELECT ne.id FROM node_executions ne WHERE ne.execution_id IN (${placeholders}))`, vals)
        await t.exec(`DELETE FROM llm_calls WHERE node_execution_id IN (SELECT ne.id FROM node_executions ne WHERE ne.execution_id IN (${placeholders}))`, vals)
        await t.exec(`DELETE FROM node_token_usages WHERE node_execution_id IN (SELECT ne.id FROM node_executions ne WHERE ne.execution_id IN (${placeholders}))`, vals)
        await t.exec(`DELETE FROM branch_executions WHERE node_execution_id IN (SELECT ne.id FROM node_executions ne WHERE ne.execution_id IN (${placeholders}))`, vals)
        await t.exec(`DELETE FROM node_edges WHERE execution_id IN (${placeholders})`, vals)
        await t.exec(`DELETE FROM node_executions WHERE execution_id IN (${placeholders})`, vals)
        await t.exec(`DELETE FROM execution_summaries WHERE execution_id IN (${placeholders})`, vals)
        await t.exec(`DELETE FROM schedule_executions WHERE execution_id IN (${placeholders})`, vals)
      }
      await t.exec("DELETE FROM executions WHERE workspace_id = ?", [workspaceId])
    })
  }

  private async findExecutionIdsForCascade(workspaceId: string): Promise<string[]> {
    const rows = await this.q<{ id: string }>("SELECT id FROM executions WHERE workspace_id = ?", [workspaceId])
    return rows.map(r => r.id)
  }

  // ── Additional methods for ExecutionLifecycle ─────────────────────

  async countRunning(workspaceId: string): Promise<number> {
    const row = await this.q1<{ count: PgNum }>(
      "SELECT COUNT(*) as count FROM executions WHERE workspace_id = ? AND status = 'running'",
      [workspaceId],
    )
    return num(row?.count)
  }

  async countRunningGroupedByWorkspace(): Promise<Record<string, number>> {
    const rows = await this.q<{ workspace_id: string; count: PgNum }>(
      "SELECT workspace_id, COUNT(*) as count FROM executions WHERE status = 'running' GROUP BY workspace_id",
    )
    const result: Record<string, number> = {}
    for (const r of rows) result[r.workspace_id] = num(r.count)
    return result
  }

  async findNodeExecutionById(id: string): Promise<NodeExecutionRow | null> {
    const row = await this.q1<NePg>("SELECT * FROM node_executions WHERE id = ?", [id])
    return row ? fromNe(row) : null
  }

  async findRunningNodeExecutionsByStatus(executionId: string, statuses: string[]): Promise<NodeExecutionRow[]> {
    if (statuses.length === 0) return []
    const placeholders = statuses.map(() => "?").join(",")
    const rows = await this.q<NePg>(
      `SELECT * FROM node_executions WHERE execution_id = ? AND status IN (${placeholders})`,
      [executionId, ...statuses],
    )
    return rows.map(fromNe)
  }

  async updateNodeExecutionsByStatus(executionId: string, newStatus: string, currentStatuses: string[], extra?: Record<string, unknown>): Promise<{ changes: number }> {
    if (currentStatuses.length === 0) return { changes: 0 }
    const placeholders = currentStatuses.map(() => "?").join(",")
    const sets = ["status = ?"]
    const vals: unknown[] = [newStatus]
    if (extra) {
      for (const [k, v] of Object.entries(extra)) {
        sets.push(`${k} = ?`)
        vals.push(v)
      }
    }
    vals.push(executionId)
    return await this.exec(
      `UPDATE node_executions SET ${sets.join(", ")} WHERE execution_id = ? AND status IN (${placeholders})`,
      [...vals, ...currentStatuses],
    )
  }

  async findFirstNodeByStatus(executionId: string, status: string, orderBy = "started_at DESC NULLS LAST"): Promise<{ node_id: string } | null> {
    const row = await this.q1<{ node_id: string }>(
      `SELECT node_id FROM node_executions WHERE execution_id = ? AND status = ? ORDER BY ${orderBy} LIMIT 1`,
      [executionId, status],
    )
    return row ?? null
  }

  async findFirstNodeErrorByStatus(executionId: string, status: string): Promise<{ error: string | null } | null> {
    const row = await this.q1<{ error: string | null }>(
      "SELECT error FROM node_executions WHERE execution_id = ? AND status = ? ORDER BY started_at DESC NULLS LAST LIMIT 1",
      [executionId, status],
    )
    return row ?? null
  }

  async findNodeStatsForExecution(executionId: string): Promise<{ total: number; completed: number; running_or_pending: number }> {
    const row = await this.q1<{ total: PgNum; completed: PgNum | null; running_or_pending: PgNum | null }>(`
      SELECT
        COUNT(*) as total,
        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed,
        SUM(CASE WHEN status IN ('running', 'pending') THEN 1 ELSE 0 END) as running_or_pending
      FROM node_executions
      WHERE execution_id = ?
    `, [executionId])
    return { total: num(row?.total), completed: num(row?.completed), running_or_pending: num(row?.running_or_pending) }
  }

  async deleteTokenUsagesByExecution(executionId: string): Promise<{ changes: number }> {
    return await this.exec(
      "DELETE FROM node_token_usages WHERE node_execution_id IN (SELECT id FROM node_executions WHERE execution_id = ?)",
      [executionId],
    )
  }

  /** [票5 事务红线] tx 体经 t = new ExecutionDAO(tx)，体内禁 this.*。 */
  async cascadeDeleteExecution(executionId: string): Promise<void> {
    await this.transaction(async (tx) => {
      const t = new ExecutionDAO(tx)
      // Leaf tables (FK → node_executions)
      await t.deleteAgentEventsByExecution(executionId)
      await t.exec(`DELETE FROM llm_calls WHERE node_execution_id IN (SELECT id FROM node_executions WHERE execution_id = ?)`, [executionId])
      await t.deleteTokenUsagesByExecution(executionId)
      await t.deleteBranchExecutionsByExecution(executionId)
      // Tables with direct FK → executions
      await t.deleteNodeEdgesByExecution(executionId)
      await t.deleteSummariesByExecution(executionId)
      await t.exec("DELETE FROM schedule_executions WHERE execution_id = ?", [executionId])
      await t.exec("UPDATE schedule_workspaces SET execution_id = NULL WHERE execution_id = ?", [executionId])
      // Core tables
      await t.deleteNodeExecutionsByExecution(executionId)
      await t.deleteById(executionId)
    })
  }

  async findCompletedNodeExecutions(executionId: string): Promise<Array<{ node_id: string; status: string; duration: number | null; error: string | null; outputs: string | null; session_id: string | null }>> {
    const rows = await this.q<{ node_id: string; status: string; duration: PgNum | null; error: string | null; outputs: unknown; session_id: string | null }>(
      "SELECT node_id, status, duration, error, outputs, session_id FROM node_executions WHERE execution_id = ? AND status IN ('completed', 'skipped', 'rejected', 'paused', 'cancelled')",
      [executionId],
    )
    return rows.map(r => ({
      node_id: r.node_id, status: r.status, duration: numOrNull(r.duration), error: r.error,
      outputs: jsonStr(r.outputs), session_id: r.session_id,
    }))
  }

  async findSessionNodes(executionId: string): Promise<Array<{ node_id: string; session_id: string }>> {
    return await this.q<{ node_id: string; session_id: string }>(
      "SELECT node_id, session_id FROM node_executions WHERE execution_id = ? AND status = 'completed' AND session_id IS NOT NULL ORDER BY completed_at DESC NULLS LAST",
      [executionId],
    )
  }

  async findPendingHooksExecutions(): Promise<Array<{ id: string; pending_hooks: string; workspace_path: string }>> {
    const rows = await this.q<{ id: string; pending_hooks: unknown; workspace_path: string }>(
      `SELECT e.id, e.pending_hooks, ws.path as workspace_path
       FROM executions e
       JOIN workspaces ws ON e.workspace_id = ws.id
       WHERE e.pending_hooks IS NOT NULL AND e.pending_hooks != '[]'::jsonb`,
    )
    return rows.map(r => ({ id: r.id, pending_hooks: jsonStr(r.pending_hooks) ?? "[]", workspace_path: r.workspace_path }))
  }

  async findStaleRunningExecutions(staleCutoff: string): Promise<Array<{ id: string; updated_at: string; pipeline_config: string }>> {
    const rows = await this.q<{ id: string; updated_at: PgDate; pipeline_config: unknown }>(
      "SELECT id, updated_at, pipeline_config FROM executions WHERE status = 'running' AND updated_at < ?",
      [staleCutoff],
    )
    return rows.map(r => ({ id: r.id, updated_at: iso(r.updated_at), pipeline_config: jsonStr(r.pipeline_config) ?? "{}" }))
  }

  async findRecentRunningExecutions(staleCutoff: string): Promise<Array<{ id: string; updated_at: string; pipeline_config: string }>> {
    const rows = await this.q<{ id: string; updated_at: PgDate; pipeline_config: unknown }>(
      "SELECT id, updated_at, pipeline_config FROM executions WHERE status = 'running' AND updated_at >= ?",
      [staleCutoff],
    )
    return rows.map(r => ({ id: r.id, updated_at: iso(r.updated_at), pipeline_config: jsonStr(r.pipeline_config) ?? "{}" }))
  }

  async fixOrphanedNodes(): Promise<number> {
    const result = await this.exec(
      `UPDATE node_executions SET status = 'failed', error = ?
       WHERE status IN ('running', 'pending')
         AND execution_id IN (SELECT id FROM executions WHERE status IN ('failed', 'cancelled'))`,
      ["服务重启中断（孤立节点）"],
    )
    return result.changes
  }

  async findPendingResumeExecutions(): Promise<Array<{ id: string; pipeline_config: string; resume_attempts: number; workspace_id: string; updated_at: string }>> {
    const rows = await this.q<{ id: string; pipeline_config: unknown; resume_attempts: number | null; workspace_id: string; updated_at: PgDate }>(`
      SELECT id, pipeline_config, resume_attempts, workspace_id, updated_at FROM executions
      WHERE status = 'pending_resume'
    `)
    return rows.map(r => ({
      id: r.id, pipeline_config: jsonStr(r.pipeline_config) ?? "{}", resume_attempts: r.resume_attempts ?? 0,
      workspace_id: r.workspace_id, updated_at: iso(r.updated_at),
    }))
  }

  async findRunningExecutionIds(): Promise<Array<{ id: string; workspace_id: string; workflow_ref: string }>> {
    return await this.q<{ id: string; workspace_id: string; workflow_ref: string }>(
      "SELECT id, workspace_id, workflow_ref FROM executions WHERE status = 'running'",
    )
  }

  async findWorkspacePath(workspaceId: string): Promise<string | null> {
    const row = await this.q1<{ path: string }>("SELECT path FROM workspaces WHERE id = ?", [workspaceId])
    return row?.path ?? null
  }

  async findWorkspacePathByExecution(executionId: string, workspaceId: string): Promise<string | null> {
    const row = await this.q1<{ workspace_path: string }>(`
      SELECT w.path as workspace_path
      FROM executions e JOIN workspaces w ON e.workspace_id = w.id
      WHERE e.id = ? AND e.workspace_id = ?
    `, [executionId, workspaceId])
    return row?.workspace_path ?? null
  }

  async findNodeErrorAndExitCode(executionId: string, nodeId: string): Promise<{ error: string | null; exit_code: number | null } | null> {
    const row = await this.q1<{ error: string | null; exit_code: number | null }>(
      "SELECT error, exit_code FROM node_executions WHERE execution_id = ? AND node_id = ?",
      [executionId, nodeId],
    )
    return row ?? null
  }

  /**
   * 每步 token 用量（REST steps 用）。NEW-r2：ntu 无 cost 列 —— costUsd 从
   * llm_calls_costed 视图按 (node_execution, model) 派生（LEFT JOIN：无明细行 = NULL，
   * 全未定价组 SUM 自然 NULL 不焊 0）。
   */
  async findNodeTokenUsages(executionId: string): Promise<Array<{ node_id: string; model: string; input_tokens: number; output_tokens: number; cache_read_tokens: number; cache_creation_tokens: number; cost_usd: number | null }>> {
    const rows = await this.q<{ node_id: string; model: string; input_tokens: number; output_tokens: number; cache_read_tokens: number; cache_creation_tokens: number; cost_usd: PgNum | null }>(
      `SELECT ne.node_id, ntu.model, ntu.input_tokens, ntu.output_tokens,
              ntu.cache_read_tokens, ntu.cache_creation_tokens, v.cost_usd
       FROM node_token_usages ntu
       JOIN node_executions ne ON ntu.node_execution_id = ne.id
       LEFT JOIN (
         SELECT node_execution_id, model, SUM(cost_usd) AS cost_usd
         FROM llm_calls_costed
         GROUP BY node_execution_id, model
       ) v ON v.node_execution_id = ntu.node_execution_id AND v.model = ntu.model
       WHERE ne.execution_id = ?`,
      [executionId],
    )
    return rows.map(r => ({ ...r, cost_usd: numOrNull(r.cost_usd) }))
  }

  /** 每节点 llm_calls 行数（= LLM 请求次数）。 */
  async llmCallCountsByNode(executionId: string): Promise<Array<{ node_id: string; count: number }>> {
    const rows = await this.q<{ node_id: string; count: PgNum }>(
      `SELECT ne.node_id, COUNT(*) as count
       FROM llm_calls lc
       JOIN node_executions ne ON lc.node_execution_id = ne.id
       WHERE ne.execution_id = ?
       GROUP BY ne.node_id`,
      [executionId],
    )
    return rows.map(r => ({ node_id: r.node_id, count: num(r.count) }))
  }

  async findLatestNodeOutput(executionId: string, nodeId: string): Promise<Record<string, unknown> | null> {
    const row = await this.q1<{ outputs: unknown }>(
      "SELECT outputs FROM node_executions WHERE execution_id = ? AND node_id = ? AND status = 'completed' ORDER BY completed_at DESC NULLS LAST LIMIT 1",
      [executionId, nodeId],
    )
    return parseJsonObject(row?.outputs)
  }

  async findRunningPipelineWorkspaces(): Promise<Array<{ workspace_id: string }>> {
    return await this.q<{ workspace_id: string }>("SELECT workspace_id FROM pipeline_state WHERE chain_status = 'running'")
  }

  async updatePipelineStatus(workspaceId: string, status: string): Promise<{ changes: number }> {
    return await this.exec(
      "UPDATE pipeline_state SET chain_status = ?, updated_at = ? WHERE workspace_id = ?",
      [status, new Date().toISOString(), workspaceId],
    )
  }

  async findLatestExecutionByWorkspace(workspaceId: string): Promise<ExecutionRow | null> {
    const row = await this.q1<ExecPg>(
      "SELECT * FROM executions WHERE workspace_id = ? ORDER BY created_at DESC LIMIT 1", [workspaceId],
    )
    return row ? fromExec(row) : null
  }

  async findExecutionForLookup(id: string): Promise<{ parent_id: string | null; var_pool: string | null; input_values: string | null } | null> {
    const row = await this.q1<{ parent_id: string | null; var_pool: unknown; input_values: unknown }>(
      "SELECT parent_id, var_pool, input_values FROM executions WHERE id = ?", [id],
    )
    if (!row) return null
    return { parent_id: row.parent_id, var_pool: jsonStr(row.var_pool), input_values: jsonStr(row.input_values) }
  }

  async findCrossExecOutputs(workflowRef: string, nodeId: string, workspaceId: string): Promise<{ outputs: string | null } | null> {
    const row = await this.q1<{ outputs: unknown }>(`
      SELECT ne.outputs
      FROM node_executions ne
      JOIN executions e ON ne.execution_id = e.id
      WHERE e.workflow_ref = ?
        AND ne.node_id = ?
        AND ne.status = 'completed'
        AND e.workspace_id = ?
      ORDER BY ne.completed_at DESC NULLS LAST
      LIMIT 1
    `, [workflowRef, nodeId, workspaceId])
    if (!row) return null
    return { outputs: jsonStr(row.outputs) }
  }

  async findPendingHooksForWorkspace(workspaceDbId: string): Promise<Array<{ id: string; workflow_ref: string; pending_hooks: string }>> {
    const rows = await this.q<{ id: string; workflow_ref: string; pending_hooks: unknown }>(
      "SELECT id, workflow_ref, pending_hooks FROM executions WHERE pending_hooks IS NOT NULL AND pending_hooks != '[]'::jsonb AND workspace_id = ?",
      [workspaceDbId],
    )
    return rows.map(r => ({ ...r, pending_hooks: jsonStr(r.pending_hooks) ?? "[]" }))
  }

  async findExecutionsForStateSync(workspaceDbId: string): Promise<Array<ExecutionRow>> {
    const rows = await this.q<ExecPg>(
      "SELECT id, parent_id, node_type, branch, workflow_ref, workflow_name, status, input_values, start_commit_id, end_commit_id, started_at, completed_at FROM executions WHERE workspace_id = ? ORDER BY created_at ASC",
      [workspaceDbId],
    )
    return rows.map(fromExec)
  }

  async findRootExecutionId(workspaceId: string): Promise<{ id: string } | null> {
    const row = await this.q1<{ id: string }>(
      "SELECT id FROM executions WHERE workspace_id = ? AND (parent_id = '0' OR parent_id IS NULL) LIMIT 1",
      [workspaceId],
    )
    return row ?? null
  }

  async findParentEndCommit(parentId: string): Promise<{ end_commit_id: string } | null> {
    const row = await this.q1<{ end_commit_id: string }>("SELECT end_commit_id FROM executions WHERE id = ?", [parentId])
    return row ?? null
  }

  async findRecentSummariesForInjection(workflowRef: string, workspaceId: string, limit = 3): Promise<Array<{ summary: string; status: string; duration_ms: number; created_at: string }>> {
    const rows = await this.q<{ summary: string; status: string; duration_ms: PgNum; created_at: PgDate }>(`
      SELECT summary, status, duration_ms, created_at
      FROM execution_summaries
      WHERE workflow_ref = ? AND workspace_id = ?
      ORDER BY created_at DESC
      LIMIT ?
    `, [workflowRef, workspaceId, limit])
    return rows.map(r => ({ summary: r.summary, status: r.status, duration_ms: num(r.duration_ms), created_at: iso(r.created_at) }))
  }

  // insertNodeTokenUsage 已删除（C3）：node_token_usages 唯一写入口 = TokenUsageDAO.recordNodeUsage

  async updateNodeExecutionsGlobalSession(executionId: string, globalSessionId: string): Promise<{ changes: number }> {
    return await this.exec("UPDATE executions SET global_session_id = ? WHERE id = ?", [globalSessionId, executionId])
  }

  async updateExecutionProgress(executionId: string, progress: number): Promise<{ changes: number }> {
    return await this.exec("UPDATE executions SET progress = ? WHERE id = ?", [progress, executionId])
  }

  async updateNodeRetryInfo(executionId: string, nodeId: string, retryCount: number, retryAt: string): Promise<{ changes: number }> {
    return await this.exec(
      "UPDATE node_executions SET retry_count = ?, last_retry_at = ? WHERE execution_id = ? AND node_id = ?",
      [retryCount, retryAt, executionId, nodeId],
    )
  }

  async incrementRetryCount(executionId: string): Promise<{ changes: number }> {
    return await this.exec("UPDATE executions SET retry_count = retry_count + 1 WHERE id = ?", [executionId])
  }

  async getRetryCount(executionId: string): Promise<number> {
    const row = await this.q1<{ retry_count: number | null }>("SELECT retry_count FROM executions WHERE id = ?", [executionId])
    return row?.retry_count ?? 0
  }

  async findFirstRunningLeaf(workspaceId: string): Promise<{ id: string } | null> {
    const row = await this.q1<{ id: string }>(`
      SELECT e.id FROM executions e
      WHERE e.workspace_id = ? AND e.status = 'running'
        AND NOT EXISTS (SELECT 1 FROM executions child WHERE child.parent_id = e.id)
    `, [workspaceId])
    return row ?? null
  }

  async findFirstRunningNode(executionId: string): Promise<NodeExecutionRow | null> {
    const row = await this.q1<NePg>(
      "SELECT * FROM node_executions WHERE execution_id = ? AND status = 'running' ORDER BY started_at DESC NULLS LAST LIMIT 1",
      [executionId],
    )
    return row ? fromNe(row) : null
  }

  /**
   * The task_dispatch node a composite parent is parked on — the resume target after a
   * child finishes. Written to accept BOTH persistences rather than guess one: the node
   * row mirroring the engine's `pending_task_dispatch` status, or (if the engine only
   * persisted the execution-level status) the still-'running' task_dispatch node.
   * `started_at DESC` matches findFirstRunningNode's convention for the same reason —
   * the most recent visit is the one that is waiting, since a Loop re-enters the node.
   */
  async findWaitingDispatchNode(executionId: string): Promise<NodeExecutionRow | null> {
    const row = await this.q1<NePg>(
      `SELECT * FROM node_executions
       WHERE execution_id = ?
         AND (status = 'pending_task_dispatch'
              OR (node_type = 'task_dispatch' AND status = 'running'))
       ORDER BY started_at DESC NULLS LAST LIMIT 1`,
      [executionId],
    )
    return row ? fromNe(row) : null
  }

  async findExecutionStatus(id: string): Promise<{ status: string } | null> {
    const row = await this.q1<{ status: string }>("SELECT status FROM executions WHERE id = ?", [id])
    return row ?? null
  }

  async insertNodeExecutionOrIgnore(row: Partial<NodeExecutionRow> & { id: string; execution_id: string; node_id: string }): Promise<{ changes: number }> {
    return await this.exec(`
      INSERT INTO node_executions (
        id, execution_id, node_id, node_type, status,
        started_at, completed_at, duration, exit_code, error,
        vars_snapshot, outputs, session_id,
        parent_node_id, iteration_index
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT DO NOTHING
    `, [
      row.id, row.execution_id, row.node_id,
      row.node_type ?? "unknown", row.status ?? "pending",
      row.started_at ?? null, row.completed_at ?? null,
      row.duration ?? null, row.exit_code ?? null, row.error ?? null,
      jsonIn(row.vars_snapshot, null), jsonIn(row.outputs, null), row.session_id ?? null,
      row.parent_node_id ?? null, row.iteration_index ?? null,
    ])
  }

  async insertNodeEdgeOrIgnore(row: { id: string; execution_id: string; from_node_id: string; to_node_id: string; edge_type: string; label?: string | null }): Promise<{ changes: number }> {
    return await this.exec(
      "INSERT INTO node_edges (id, execution_id, from_node_id, to_node_id, edge_type, label) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING",
      [row.id, row.execution_id, row.from_node_id, row.to_node_id, row.edge_type, row.label ?? null],
    )
  }

  async incrementResumeAttempts(executionId: string): Promise<{ changes: number }> {
    return await this.exec("UPDATE executions SET resume_attempts = resume_attempts + 1 WHERE id = ?", [executionId])
  }

  // ── Dashboard queries ────────────────────────────────────────────

  async getDashboardStats(): Promise<{
    total_executions: number; completed_executions: number; failed_executions: number;
    running_executions: number; pending_executions: number; cancelled_executions: number;
    avg_duration_ms: number | null
  }> {
    const row = await this.q1<{
      total_executions: PgNum; completed_executions: PgNum | null; failed_executions: PgNum | null;
      running_executions: PgNum | null; pending_executions: PgNum | null; cancelled_executions: PgNum | null;
      avg_duration_ms: PgNum | null
    }>(`
      WITH root_executions AS (
        SELECT id, status as root_status, duration, completed_at, started_at
        FROM executions WHERE parent_id IS NULL OR parent_id = '0' OR phase_index IS NOT NULL
      ),
      latest_children AS (
        SELECT parent_id, status as child_status,
          ROW_NUMBER() OVER (PARTITION BY parent_id ORDER BY started_at DESC NULLS LAST) as rn
        FROM executions WHERE parent_id IS NOT NULL AND parent_id != '0' AND phase_index IS NULL
      ),
      effective_status AS (
        SELECT r.id, COALESCE(lc.child_status, r.root_status) as status,
          r.duration, r.completed_at, r.started_at
        FROM root_executions r
        LEFT JOIN latest_children lc ON r.id = lc.parent_id AND lc.rn = 1
      )
      SELECT
        COUNT(*) as total_executions,
        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed_executions,
        SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) as failed_executions,
        SUM(CASE WHEN status = 'running' THEN 1 ELSE 0 END) as running_executions,
        SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending_executions,
        SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) as cancelled_executions,
        AVG(COALESCE(duration,
          CASE WHEN completed_at IS NOT NULL AND started_at IS NOT NULL
            THEN EXTRACT(EPOCH FROM (completed_at - started_at)) * 1000
            ELSE NULL END)) as avg_duration_ms
      FROM effective_status
    `)
    return {
      total_executions: num(row?.total_executions),
      completed_executions: num(row?.completed_executions),
      failed_executions: num(row?.failed_executions),
      running_executions: num(row?.running_executions),
      pending_executions: num(row?.pending_executions),
      cancelled_executions: num(row?.cancelled_executions),
      avg_duration_ms: numOrNull(row?.avg_duration_ms),
    }
  }

  async getQueueItems(): Promise<Array<Record<string, unknown>>> {
    const rows = await this.q<ExecPg & { workspace_name: string | null; current_step: string | null }>(`
      SELECT e.*, w.name as workspace_name,
        (SELECT node_id FROM node_executions
         WHERE execution_id = e.id AND status = 'running'
         ORDER BY started_at DESC NULLS LAST LIMIT 1) as current_step
      FROM executions e
      LEFT JOIN workspaces w ON e.workspace_id = w.id
      WHERE e.status IN ('running', 'pending')
      ORDER BY CASE e.status WHEN 'running' THEN 0 ELSE 1 END, e.created_at DESC
    `)
    return rows.map(r => ({ ...fromExec(r), workspace_name: r.workspace_name, current_step: r.current_step }))
  }

  async getRecentCompleted(limit: number = 10): Promise<Array<Record<string, unknown>>> {
    const rows = await this.q<ExecPg & { workspace_name: string | null; current_step: string | null }>(`
      SELECT e.*, w.name as workspace_name,
        (SELECT node_id FROM node_executions
         WHERE execution_id = e.id AND status = 'running'
         ORDER BY started_at DESC NULLS LAST LIMIT 1) as current_step
      FROM executions e
      LEFT JOIN workspaces w ON e.workspace_id = w.id
      WHERE e.status IN ('completed', 'failed', 'cancelled', 'rejected')
      ORDER BY e.completed_at DESC NULLS LAST LIMIT ?
    `, [limit])
    return rows.map(r => ({ ...fromExec(r), workspace_name: r.workspace_name, current_step: r.current_step }))
  }

  async getWorkflowHealth(limit: number = 10): Promise<Array<{
    workflow_ref: string; executions: number; success_rate: number | null; avg_duration_ms: number | null
  }>> {
    const rows = await this.q<{
      workflow_ref: string; executions: PgNum; success_rate: number | null; avg_duration_ms: PgNum | null
    }>(`
      WITH root_executions AS (
        SELECT id, workflow_ref, status as root_status, duration, completed_at, started_at
        FROM executions WHERE parent_id IS NULL OR parent_id = '0' OR phase_index IS NOT NULL
      ),
      latest_children AS (
        SELECT parent_id, status as child_status,
          ROW_NUMBER() OVER (PARTITION BY parent_id ORDER BY started_at DESC NULLS LAST) as rn
        FROM executions WHERE parent_id IS NOT NULL AND parent_id != '0' AND phase_index IS NULL
      ),
      effective_status AS (
        SELECT r.id, r.workflow_ref, COALESCE(lc.child_status, r.root_status) as status,
          r.duration, r.completed_at, r.started_at
        FROM root_executions r
        LEFT JOIN latest_children lc ON r.id = lc.parent_id AND lc.rn = 1
      )
      SELECT workflow_ref, COUNT(*) as executions,
        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END)::double precision / COUNT(*) as success_rate,
        AVG(duration) as avg_duration_ms
      FROM effective_status GROUP BY workflow_ref HAVING COUNT(*) >= 1
      ORDER BY executions DESC LIMIT ?
    `, [limit])
    return rows.map(r => ({
      workflow_ref: r.workflow_ref, executions: num(r.executions),
      success_rate: numOrNull(r.success_rate), avg_duration_ms: numOrNull(r.avg_duration_ms),
    }))
  }

  async findAgentEventsWithNode(executionId: string, nodeId?: string): Promise<Array<Record<string, unknown>>> {
    let query = `
      SELECT ae.*, ne.node_id
      FROM agent_events ae
      JOIN node_executions ne ON ae.node_execution_id = ne.id
      WHERE ne.execution_id = ?
    `
    const params: unknown[] = [executionId]
    if (nodeId) { query += ` AND ne.node_id = ?`; params.push(nodeId) }
    query += ` ORDER BY ae.timestamp ASC`
    const rows = await this.q<AePg & { node_id: string }>(query, params)
    return rows.map(r => ({ ...fromAe(r), node_id: r.node_id }))
  }

  /**
   * 工具调用总数 = 不同 tool_call_id 数。两代词汇（raw 的 tool_start/tool_input/tool_result
   * 三行、merged 的 tool_call 两行）共享同一 id，DISTINCT 天然去重。
   */
  async countToolCalls(executionId: string, nodeId?: string): Promise<number> {
    let query = `
      SELECT COUNT(DISTINCT ae.tool_call_id) AS count
      FROM agent_events ae
      JOIN node_executions ne ON ae.node_execution_id = ne.id
      WHERE ne.execution_id = ? AND ae.tool_call_id IS NOT NULL
        AND ae.event_type IN ('tool_start','tool_input','tool_result','tool_call')
    `
    const params: unknown[] = [executionId]
    if (nodeId) { query += ` AND ne.node_id = ?`; params.push(nodeId) }
    const row = await this.q1<{ count: PgNum }>(query, params)
    return num(row?.count)
  }

  /**
   * Find all tool-level errors (tool_is_error = true) for an execution.
   * Used by observability to surface agent-internal tool failures.
   */
  async findToolErrors(executionId: string): Promise<Array<{
    node_id: string
    tool_name: string
    tool_result: string
    timestamp: number
  }>> {
    const rows = await this.q<{ node_id: string; tool_name: string; tool_result: string; timestamp: PgNum }>(`
      SELECT ne.node_id, ae.tool_name, ae.tool_result, ae.timestamp
      FROM agent_events ae
      JOIN node_executions ne ON ae.node_execution_id = ne.id
      WHERE ne.execution_id = ? AND ae.tool_is_error = true
      ORDER BY ae.timestamp ASC
    `, [executionId])
    return rows.map(r => ({ node_id: r.node_id, tool_name: r.tool_name, tool_result: r.tool_result, timestamp: num(r.timestamp) }))
  }

  async exists(id: string): Promise<boolean> {
    const row = await this.q1<{ one: number }>("SELECT 1 as one FROM executions WHERE id = ?", [id])
    return row !== undefined
  }

  async findByOrgWithWorkspace(org: string, limit: number = 50): Promise<Array<{
    id: string; workspace_id: string; workflow_name: string; status: string;
    started_at: string | null; completed_at: string | null; workspace_name?: string
  }>> {
    try {
      const rows = await this.q<{
        id: string; workspace_id: string; workflow_name: string; status: string;
        started_at: PgDate | null; completed_at: PgDate | null; workspace_name: string | null
      }>(`
        SELECT e.id, e.workspace_id, e.workflow_name, e.status,
               e.started_at, e.completed_at, w.name as workspace_name
        FROM executions e
        LEFT JOIN workspaces w ON e.workspace_id = w.id
        WHERE e.org = ?
        ORDER BY e.created_at DESC LIMIT ?
      `, [org, limit])
      return rows.map(r => ({
        id: r.id, workspace_id: r.workspace_id, workflow_name: r.workflow_name, status: r.status,
        started_at: isoOrNull(r.started_at), completed_at: isoOrNull(r.completed_at), workspace_name: r.workspace_name ?? undefined,
      }))
    } catch {
      return []
    }
  }

  async findActiveExecutionsByOrg(org: string): Promise<Array<{
    id: string; workspace_id: string; workflow_name: string; status: string;
    started_at: string | null; current_node: string | null; progress: number | null;
    workspace_name?: string
  }>> {
    try {
      // current_node 列两侧 schema 都不存在（存量行为 = 查询抛错被 catch 吞掉 → []）。
      // 保持原样：PG 下同样在 Parse 期报错走 catch，行为零漂移；列的补齐属独立需求。
      const rows = await this.q<{
        id: string; workspace_id: string; workflow_name: string; status: string;
        started_at: PgDate | null; current_node: string | null; progress: number | null; workspace_name: string | null
      }>(`
        SELECT e.id, e.workspace_id, e.workflow_name, e.status,
               e.started_at, e.current_node, e.progress, w.name as workspace_name
        FROM executions e
        LEFT JOIN workspaces w ON e.workspace_id = w.id
        WHERE e.org = ? AND e.status IN ('running', 'active', 'pending')
        ORDER BY e.started_at DESC NULLS LAST
      `, [org])
      return rows.map(r => ({
        id: r.id, workspace_id: r.workspace_id, workflow_name: r.workflow_name, status: r.status,
        started_at: isoOrNull(r.started_at), current_node: r.current_node, progress: r.progress,
        workspace_name: r.workspace_name ?? undefined,
      }))
    } catch {
      return []
    }
  }

  async findAllActiveExecutions(): Promise<Array<{
    id: string; workspace_id: string; workflow_name: string; workflow_ref: string;
    status: string; started_at: string | null; current_node: string | null;
    progress: number | null; triggered_by: string; workspace_name?: string;
    updated_at: string | null
  }>> {
    try {
      // current_node：同 findActiveExecutionsByOrg —— 两侧 schema 无此列，catch 兜底为 [] 是存量语义。
      const rows = await this.q<{
        id: string; workspace_id: string; workflow_name: string; workflow_ref: string; status: string;
        started_at: PgDate | null; current_node: string | null; progress: number | null;
        triggered_by: string; updated_at: PgDate | null; workspace_name: string | null
      }>(`
        SELECT e.id, e.workspace_id, e.workflow_name, e.workflow_ref, e.status,
               e.started_at, e.current_node, e.progress, e.triggered_by, e.updated_at,
               w.name as workspace_name
        FROM executions e
        LEFT JOIN workspaces w ON e.workspace_id = w.id
        WHERE e.status IN ('running', 'active', 'pending')
        ORDER BY e.started_at DESC NULLS LAST
      `)
      return rows.map(r => ({
        id: r.id, workspace_id: r.workspace_id, workflow_name: r.workflow_name, workflow_ref: r.workflow_ref,
        status: r.status, started_at: isoOrNull(r.started_at), current_node: r.current_node, progress: r.progress,
        triggered_by: r.triggered_by, workspace_name: r.workspace_name ?? undefined, updated_at: isoOrNull(r.updated_at),
      }))
    } catch {
      return []
    }
  }

  async findNodeStatsForExecutionSplit(executionId: string): Promise<{ total: number; completed: number; running: number; pending: number }> {
    const row = await this.q1<{ total: PgNum; completed: PgNum | null; running: PgNum | null; pending: PgNum | null }>(`
      SELECT
        COUNT(*) as total,
        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed,
        SUM(CASE WHEN status = 'running' THEN 1 ELSE 0 END) as running,
        SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending
      FROM node_executions
      WHERE execution_id = ?
    `, [executionId])
    return {
      total: num(row?.total), completed: num(row?.completed),
      running: num(row?.running), pending: num(row?.pending),
    }
  }

  async findByIdAndOrg(id: string, org: string): Promise<{ id: string; workspace_id: string; status: string; workflow_name: string } | null> {
    try {
      const row = await this.q1<{ id: string; workspace_id: string; status: string; workflow_name: string }>(
        "SELECT id, workspace_id, status, workflow_name FROM executions WHERE id = ? AND org = ?",
        [id, org],
      )
      return row ?? null
    } catch {
      return null
    }
  }

  async getOverallStats(): Promise<Record<string, unknown>> {
    const row = await this.q1<{
      total_executions: PgNum; running: PgNum; completed: PgNum; failed: PgNum;
      pending: PgNum; cancelled: PgNum; avg_duration_ms: PgNum | null
    }>(`
      SELECT
        COUNT(*) as total_executions,
        COUNT(CASE WHEN status = 'running' THEN 1 END) as running,
        COUNT(CASE WHEN status = 'completed' THEN 1 END) as completed,
        COUNT(CASE WHEN status = 'failed' THEN 1 END) as failed,
        COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending,
        COUNT(CASE WHEN status = 'cancelled' THEN 1 END) as cancelled,
        AVG(duration) as avg_duration_ms
      FROM executions
    `)
    return {
      total_executions: num(row?.total_executions), running: num(row?.running), completed: num(row?.completed),
      failed: num(row?.failed), pending: num(row?.pending), cancelled: num(row?.cancelled),
      avg_duration_ms: numOrNull(row?.avg_duration_ms),
    }
  }

  /** 旧 SQLite 侧 created_at 是 ISO 文本、入参是 epoch-ms 数字（比较永假 = 存量 no-op）；
   *  PG timestamptz 不接受裸数字 —— 按参数名义语义转 Date。 */
  async deleteOldNodeTokenUsages(cutoffTimestamp: number): Promise<{ changes: number }> {
    return await this.exec("DELETE FROM node_token_usages WHERE created_at < ?", [new Date(cutoffTimestamp)])
  }

  // ── Analytics route queries ────────────────────────────────────────

  async countByWorkspaceSince(workspaceId: string, cutoff: string): Promise<number> {
    const row = await this.q1<{ count: PgNum }>(
      "SELECT COUNT(*) as count FROM executions WHERE workspace_id = ? AND created_at >= ?",
      [workspaceId, cutoff],
    )
    return num(row?.count)
  }

  async successRateByWorkspaceSince(workspaceId: string, cutoff: string): Promise<number | null> {
    const row = await this.q1<{ rate: number | null }>(
      "SELECT SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END)::double precision / NULLIF(COUNT(*), 0) as rate FROM executions WHERE workspace_id = ? AND created_at >= ? AND status IN ('completed', 'failed')",
      [workspaceId, cutoff],
    )
    return numOrNull(row?.rate)
  }

  async avgDurationByWorkspaceSince(workspaceId: string, cutoff: string): Promise<number | null> {
    const row = await this.q1<{ avg_ms: PgNum | null }>(
      "SELECT AVG(duration) as avg_ms FROM executions WHERE workspace_id = ? AND created_at >= ? AND duration IS NOT NULL",
      [workspaceId, cutoff],
    )
    return numOrNull(row?.avg_ms)
  }

  async workflowStatsByWorkspace(workspaceId: string, cutoff: string): Promise<Array<Record<string, unknown>>> {
    const rows = await this.q<{ workflow_ref: string; executions: PgNum; success_rate: number | null; avg_duration_ms: PgNum | null }>(`
      SELECT workflow_ref,
             COUNT(*) as executions,
             SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END)::double precision / NULLIF(COUNT(*), 0) as success_rate,
             AVG(duration) as avg_duration_ms
      FROM executions
      WHERE workspace_id = ? AND created_at >= ?
      GROUP BY workflow_ref ORDER BY executions DESC
    `, [workspaceId, cutoff])
    return rows.map(r => ({
      workflow_ref: r.workflow_ref, executions: num(r.executions),
      success_rate: numOrNull(r.success_rate), avg_duration_ms: numOrNull(r.avg_duration_ms),
    }))
  }

  async dailyTrendByWorkspace(workspaceId: string, cutoff: string): Promise<Array<Record<string, unknown>>> {
    const rows = await this.q<{ date: string; executions: PgNum; success_rate: number | null }>(`
      SELECT to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD') as date,
             COUNT(*) as executions,
             SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END)::double precision / NULLIF(COUNT(*), 0) as success_rate
      FROM executions WHERE workspace_id = ? AND created_at >= ?
      GROUP BY to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD') ORDER BY date ASC
    `, [workspaceId, cutoff])
    return rows.map(r => ({ date: r.date, executions: num(r.executions), success_rate: numOrNull(r.success_rate) }))
  }

  async findExecutionsByWorkflow(workspaceId: string, workflowRef: string, cutoff: string, limit: number = 100): Promise<ExecutionRow[]> {
    const rows = await this.q<ExecPg>(
      "SELECT * FROM executions WHERE workspace_id = ? AND workflow_ref = ? AND created_at >= ? ORDER BY created_at DESC LIMIT ?",
      [workspaceId, workflowRef, cutoff, limit],
    )
    return rows.map(fromExec)
  }

  // ── Batch inserts (for observability) ─────────────────────────────

  /** [S9] named-@ 逐行循环 + DAO 内事务 → 一条多行 VALUES（ON CONFLICT DO NOTHING
   *  = 旧 INSERT OR IGNORE 语义），单语句天然原子，事务随形消失（:1317 消灭裁决）。 */
  async insertAgentEventBatch(rows: AgentEventRow[]): Promise<void> {
    if (rows.length === 0) return
    await this.insertAgentEvents(rows, true)
  }

  // ── Analytical queries (for log-analysis, suggestion-engine) ────────

  async findNodeExecStatsByWorkflow(workspaceId: string, days: number): Promise<Array<{
    node_id: string; status: string; node_type: string; workflow_ref: string; count: number
  }>> {
    const rows = await this.q<{ node_id: string; status: string; node_type: string; workflow_ref: string; count: PgNum }>(`
      SELECT ne.node_id, ne.status, ne.node_type, e.workflow_ref, COUNT(*) as count
      FROM node_executions ne JOIN executions e ON ne.execution_id = e.id
      WHERE e.workspace_id = ? AND e.workflow_ref IS NOT NULL
        AND e.created_at >= now() - make_interval(days => ?::int)
        AND ne.node_type = 'condition'
      GROUP BY ne.node_id, ne.status, ne.node_type, e.workflow_ref
    `, [workspaceId, days])
    return rows.map(r => ({ ...r, count: num(r.count) }))
  }

  async findFlakyNodeStats(workspaceId: string, days: number): Promise<Array<{
    node_id: string; failures: number; total: number
  }>> {
    const rows = await this.q<{ node_id: string; failures: PgNum | null; total: PgNum }>(`
      SELECT ne.node_id,
             SUM(CASE WHEN ne.status = 'failed' THEN 1 ELSE 0 END) as failures,
             COUNT(*) as total
      FROM node_executions ne JOIN executions e ON ne.execution_id = e.id
      WHERE e.workspace_id = ? AND e.created_at >= now() - make_interval(days => ?::int)
      GROUP BY ne.node_id HAVING SUM(CASE WHEN ne.status = 'failed' THEN 1 ELSE 0 END) > 0
    `, [workspaceId, days])
    return rows.map(r => ({ node_id: r.node_id, failures: num(r.failures), total: num(r.total) }))
  }

  // ── Additional methods for service migrations ─────────────────────

  async findVarPool(executionId: string): Promise<string | null> {
    const row = await this.q1<{ var_pool: unknown }>("SELECT var_pool FROM executions WHERE id = ?", [executionId])
    return jsonStr(row?.var_pool)
  }

  async findExecutionStatusSimple(executionId: string): Promise<string | null> {
    const row = await this.q1<{ status: string }>("SELECT status FROM executions WHERE id = ?", [executionId])
    return row?.status ?? null
  }

  /** Real (non-pseudo `__*`) node outcomes for an execution — used by the
   *  scheduler chain-completion callback to mirror ExecutionLifecycle's
   *  allSkipped→failed rule while the engine run is still unwinding. */
  async countRealNodeOutcomes(executionId: string): Promise<{ completed: number; skipped: number }> {
    const row = await this.q1<{ completed: PgNum | null; skipped: PgNum | null }>(`
      SELECT
        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS completed,
        SUM(CASE WHEN status = 'skipped'   THEN 1 ELSE 0 END) AS skipped
      FROM node_executions
      WHERE execution_id = ? AND substr(node_id, 1, 2) != '__'
    `, [executionId])
    return { completed: num(row?.completed), skipped: num(row?.skipped) }
  }

  async findFirstNodeError(executionId: string): Promise<string | null> {
    const row = await this.q1<{ error: string | null }>(
      "SELECT error FROM node_executions WHERE execution_id = ? AND status = 'failed' LIMIT 1",
      [executionId],
    )
    return row?.error ?? null
  }

  async findLastChildExecution(executionId: string): Promise<{ id: string } | null> {
    const row = await this.q1<{ id: string }>(`
      SELECT id FROM executions
      WHERE workspace_id = (SELECT workspace_id FROM executions WHERE id = ?)
      ORDER BY child_index DESC NULLS LAST
      LIMIT 1
    `, [executionId])
    return row ?? null
  }

  async findChainNodeErrors(executionId: string): Promise<{ error: string | null } | null> {
    const row = await this.q1<{ error: string | null }>(`
      SELECT error FROM node_executions
      WHERE execution_id IN (SELECT id FROM executions WHERE workspace_id = (SELECT workspace_id FROM executions WHERE id = ?))
      AND status = 'failed' LIMIT 1
    `, [executionId])
    return row ?? null
  }

  async insertContainerExecution(id: string, workspaceId: string, workflowRef: string, org: string, now: string): Promise<{ changes: number }> {
    return await this.exec(`
      INSERT INTO executions (
        id, workspace_id, parent_id, workflow_ref, workflow_name,
        status, node_type, triggered_by, org, created_at, updated_at,
        var_pool, input_values
      ) VALUES (?, ?, '0', ?, ?, 'completed', 'scheduler-root', 'scheduler', ?, ?, ?, '{}'::jsonb, '{}'::jsonb)
    `, [id, workspaceId, workflowRef, workflowRef, org, now, now])
  }

  async markInterruptedExecutions(org: string, completedAt: string): Promise<number> {
    const result = await this.exec(
      "UPDATE executions SET status = 'interrupted', completed_at = ? WHERE org = ? AND status = 'running'",
      [completedAt, org],
    )
    return result.changes
  }

  // ── Data retention methods ────────────────────────────────────────

  async truncateOldAgentEventContent(cutoffTimestamp: number): Promise<{ changes: number }> {
    return await this.exec(`
      UPDATE agent_events SET content = SUBSTR(content, 1, 50), content_length = 50
      WHERE timestamp < ? AND content IS NOT NULL AND LENGTH(content) > 50
    `, [cutoffTimestamp])
  }

  async deleteOldAgentEvents(cutoffTimestamp: number): Promise<{ changes: number }> {
    return await this.exec("DELETE FROM agent_events WHERE timestamp < ?", [cutoffTimestamp])
  }

  async deleteOldLlmCalls(cutoffTimestamp: number): Promise<{ changes: number }> {
    return await this.exec("DELETE FROM llm_calls WHERE timestamp < ?", [cutoffTimestamp])
  }
}
