export { VERSION } from "./version"
export * from "./types/workflow"
export * from "./types/workspace"
export * from "./types/config"
export * from "./types/pipeline"
export * from "./types/notify"
export * from "./yaml/parser"
export * from "./variables/var-pool"
export * from "./variables/expression"
export * from "./variables/substitute"
export * from "./variables/cross-exec-resolver"
export * from "./auto-answers/compiler"
export * from "./config/loader"
export * from "./manifest/validator"
export * from "./repo-ops/mod"
export * from "./skill-search"
export * from "./yaml/pipeline-parser"
export { TemplateRenderer, validateTemplateSyntax } from "./notify/template-renderer"
export { applyFilters } from "./notify/filters"
export * from "./types/scheduler-job"
export * from "./types/scheduler-execution"
export * from "./types/scheduler-audit"
export * from "./types/scheduler-common"
export * from "./types/schedule-workspace"
export * from "./types/agent"
export * from "./types/swarm"
export * from "./plugin/detector"
export * from "./plugin/types"
export * from "./types/knowledge"
export { ModelAliasConfigSchema, DEFAULT_MODEL_ALIASES, CustomProvidersMapSchema } from './config/model-alias'
export type { ModelAliasConfig, CustomProviderDef, CustomProvidersMap } from './config/model-alias'
export { resolveModelAlias, loadModelAliasConfig, collectNodeEngines } from './config/model-alias'

// Resource management
export * from "./resource/types"
export { ResourceError } from "./resource/errors"
export type { ResourceErrorCode } from "./resource/errors"
export * from "./resource/utils"
export * from "./resource/security"
export type { ResourceEvent } from "./resource/resource-event"
export type { SourceProvider } from "./resource/providers/types"
export { ResourceManager } from "./resource/manager"
export type { ResourceManagerConfig } from "./resource/manager"
export { RegistryStore } from "./resource/registry"
export type { RegistryFilter } from "./resource/registry"
export { LockManager } from "./resource/lock-manager"
export { DependencyResolver } from "./resource/dependency-resolver"
export { AuditLogger } from "./resource/audit-logger"
export { GarbageCollector } from "./resource/gc"
export { BuiltinProvider } from "./resource/providers/builtin-provider"
export { LocalProvider } from "./resource/providers/local-provider"
