// Resource management module — barrel exports

export * from "./types"
export * from "./errors"
export { AtomicJsonStore } from "./atomic-json-store"
export { RegistryStore } from "./registry-store"
export { LockManager } from "./lock-manager"
export { parseRef, registerRefParser, getRegisteredSources } from "./ref-parser"
export type { ParsedRef } from "./ref-parser"
export { BuiltinProvider } from "./builtin-provider"
export { LocalProvider } from "./local-provider"
export { GitProvider } from "./providers/git-provider"
export type { GitProviderConfig } from "./providers/git-provider"
export { isPathWithinBase, copyDirSync, generateFileHash, listFilesRecursive } from "./fs-utils"
export { PostInstallVerifier, PostUninstallVerifier } from "./verifier"
export type { VerifyStep, VerifyContext } from "./verifier"
export { AuditWriter } from "./audit-writer"
export { ResourceManager } from "./resource-manager"
export type { ResourceManagerConfig } from "./resource-manager"
export { SourceDiscovery } from "./source-discovery"
export type { DiscoveredResource } from "./source-discovery"
export { SourceManager } from "./source-manager"
export type { SourceManagerConfig } from "./source-manager"
export { SourcesStore } from "./sources-store"
export { TrustManager } from "./trust-manager"
export { WorkflowRef } from "./workflow-ref"
export { ResourcePreFlight } from "./resource-preflight"
export type { ResourceManifest, ResourceCheckResult } from "./resource-preflight"
export { ResourceProvisioner } from "./resource-provisioner"
