import { describe, it, expect, vi, beforeEach, afterEach } from "vitest"
import { ReposManager } from "../repos-manager"
import type { ReposConfig } from "@octopus/shared"
import { writeFileSync, mkdirSync, rmSync, mkdtempSync, readFileSync } from "fs"
import { join } from "path"
import { tmpdir } from "os"

vi.mock("@octopus/shared", async () => {
  const actual = await vi.importActual<typeof import("@octopus/shared")>("@octopus/shared")
  return {
    ...actual,
    cloneProject: vi.fn(),
    pullProject: vi.fn(),
    cloneMissingProjects: vi.fn(),
  }
})

import { cloneProject, pullProject, cloneMissingProjects } from "@octopus/shared"

function makeTmpDir(): string {
  return mkdtempSync(join(tmpdir(), "octopus-repos-mgr-test-"))
}

const MANIFEST_CONTENT = `## xzf (旧架构)

- order-service [master] https://git.example.com/order.git
- user-service [develop] https://git.example.com/user.git

`

const INDEX_CONTENT = `# GitRepo Index

> Auto-generated from manifest + local scan.

## xzf (旧架构)

### order-service
- git: https://git.example.com/order.git
- branch: master
- desc: —
- local: /tmp/test/cloned/order-service ✓ cloned
- knowledge: repowiki:no

### user-service
- git: https://git.example.com/user.git
- branch: develop
- desc: —
- local: — not cloned
- knowledge: index-only

---
*Generated by octopus repos — 2 projects from 1 groups*
`

describe("ReposManager", () => {
  let tmpDir: string

  beforeEach(() => {
    tmpDir = makeTmpDir()
    const reposDir = join(tmpDir, "repos")
    mkdirSync(reposDir, { recursive: true })
    writeFileSync(join(reposDir, "manifest.md"), MANIFEST_CONTENT, "utf-8")
    writeFileSync(join(reposDir, "index.md"), INDEX_CONTENT, "utf-8")
  })

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true })
  })

  function makeConfig(): ReposConfig {
    return {
      cloneBase: join(tmpDir, "cloned"),
      groups: ["xzf"],
      manifestPath: join(tmpDir, "repos", "manifest.md"),
      outputPath: join(tmpDir, "repos", "index.md"),
    }
  }

  describe("update", () => {
    it("rebuilds index from manifest", async () => {
      const config = makeConfig()
      const manager = new ReposManager(config)
      await manager.update()

      const content = readFileSync(config.outputPath, "utf-8")
      expect(content).toContain("### order-service")
      expect(content).toContain("### user-service")
      expect(content).toContain("- git: https://git.example.com/order.git")
      expect(content).toContain("- branch: master")
    })

    it("rebuilds index with external scan dirs", async () => {
      const extDir = join(tmpDir, "external")
      mkdirSync(join(extDir, "order-service"), { recursive: true })

      const config = makeConfig()
      const manager = new ReposManager(config)
      await manager.update([extDir])

      const content = readFileSync(config.outputPath, "utf-8")
      expect(content).toContain("order-service")
    })
  })

  describe("pull", () => {
    it("reports no projects to pull when index has no cloned paths", async () => {
      writeFileSync(join(tmpDir, "repos", "index.md"), `# GitRepo Index\n\n## xzf\n\n### order-service\n- git: https://git.example.com/order.git\n- branch: master\n- local: — not cloned\n- knowledge: index-only\n\n`, "utf-8")

      const config = makeConfig()
      const manager = new ReposManager(config)
      await manager.pull()
    })

    it("handles named projects not in manifest", async () => {
      const config = makeConfig()
      const manager = new ReposManager(config)
      await manager.pull(["nonexistent-project"])
    })
  })

  describe("rebuildIndex", () => {
    it("rebuilds index without clone/pull", async () => {
      const config = makeConfig()
      const manager = new ReposManager(config)
      await manager.rebuildIndex()

      const content = readFileSync(config.outputPath, "utf-8")
      expect(content).toContain("order-service")
      expect(content).toContain("user-service")
    })
  })

  describe("cloneProjects", () => {
    beforeEach(() => {
      vi.clearAllMocks()
    })

    it("clones single project successfully", async () => {
      vi.mocked(cloneProject).mockReturnValue({ success: true, message: "cloned" })

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.cloneProjects(["order-service"])

      expect(result.success).toEqual(["order-service"])
      expect(result.failed).toEqual([])
      expect(result.skipped).toEqual([])
    })

    it("clones multiple projects sequentially", async () => {
      vi.mocked(cloneProject).mockReturnValue({ success: true, message: "cloned" })

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.cloneProjects(["order-service", "user-service"])

      expect(result.success).toEqual(["order-service", "user-service"])
      expect(vi.mocked(cloneProject)).toHaveBeenCalledTimes(2)
    })

    it("reports not-found for unknown project and continues", async () => {
      vi.mocked(cloneProject).mockReturnValue({ success: true, message: "cloned" })

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.cloneProjects(["nonexistent", "order-service"])

      expect(result.failed).toEqual([{ name: "nonexistent", reason: "'nonexistent' not found in manifest" }])
      expect(result.success).toEqual(["order-service"])
    })

    it("reports no-git_url for project without URL", async () => {
      vi.mocked(cloneProject).mockReturnValue({ success: true, message: "cloned" })

      writeFileSync(
        join(tmpDir, "repos", "manifest.md"),
        "## xzf\n- no-url-project [master]\n- order-service [master] https://git.example.com/order.git\n",
        "utf-8"
      )

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.cloneProjects(["no-url-project", "order-service"])

      expect(result.failed).toEqual([{ name: "no-url-project", reason: "'no-url-project' has no git_url" }])
    })

    it("skips already cloned project", async () => {
      const repoDir = join(tmpDir, "cloned", "xzf", "order-service")
      mkdirSync(join(repoDir, ".git"), { recursive: true })

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.cloneProjects(["order-service"])

      expect(result.skipped).toEqual(["order-service"])
      expect(vi.mocked(cloneProject)).not.toHaveBeenCalled()
    })

    it("throws ReposError when all projects fail and none succeeded", async () => {
      const config = makeConfig()
      const manager = new ReposManager(config)

      await expect(manager.cloneProjects(["nonexistent"])).rejects.toThrow("All 1 projects failed")
    })

    it("does not throw when at least one succeeds", async () => {
      vi.mocked(cloneProject).mockReturnValue({ success: true, message: "cloned" })

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.cloneProjects(["nonexistent", "order-service"])

      expect(result.success).toEqual(["order-service"])
      expect(result.failed.length).toBe(1)
    })

    it("uses branchOverride when provided", async () => {
      vi.mocked(cloneProject).mockReturnValue({ success: true, message: "cloned" })

      const config = makeConfig()
      const manager = new ReposManager(config)
      await manager.cloneProjects(["order-service"], "feature-branch")

      expect(vi.mocked(cloneProject)).toHaveBeenCalledWith(
        "https://git.example.com/order.git",
        "xzf",
        "order-service",
        "feature-branch",
        config.cloneBase
      )
    })

    it("reports failure when cloneProject returns unsuccessful result", async () => {
      vi.mocked(cloneProject)
        .mockReturnValueOnce({ success: false, message: "Authentication failed" })
        .mockReturnValueOnce({ success: true, message: "cloned" })

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.cloneProjects(["order-service", "user-service"])

      expect(result.failed).toEqual([{ name: "order-service", reason: "Authentication failed" }])
      expect(result.success).toEqual(["user-service"])
    })

    it("handles unexpected errors from cloneProject without aborting loop", async () => {
      vi.mocked(cloneProject)
        .mockImplementationOnce(() => { throw new Error("EACCES: permission denied") })
        .mockReturnValueOnce({ success: true, message: "cloned" })

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.cloneProjects(["order-service", "user-service"])

      expect(result.failed).toEqual([{ name: "order-service", reason: "EACCES: permission denied" }])
      expect(result.success).toEqual(["user-service"])
    })
  })

  describe("sync", () => {
    beforeEach(() => {
      vi.clearAllMocks()
      vi.mocked(cloneMissingProjects).mockReturnValue({ cloned: 0, failed: 0 })
      vi.mocked(pullProject).mockReturnValue({ success: true, message: "pulled" })
    })

    it("executes clone + pull + rebuild in order", async () => {
      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.sync()

      expect(vi.mocked(cloneMissingProjects)).toHaveBeenCalled()
      expect(result.cloned).toEqual({ success: 0, failed: 0 })
      expect(result.rebuilt).toBe(true)
    })

    it("skips clone when clone=false", async () => {
      const config = makeConfig()
      const manager = new ReposManager(config)
      await manager.sync({ clone: false })

      expect(vi.mocked(cloneMissingProjects)).not.toHaveBeenCalled()
    })

    it("skips pull when pull=false", async () => {
      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.sync({ pull: false })

      expect(vi.mocked(pullProject)).not.toHaveBeenCalled()
      expect(result.pulled).toEqual({ success: 0, failed: 0 })
    })

    it("skips rebuild when rebuild=false", async () => {
      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.sync({ rebuild: false })

      expect(result.rebuilt).toBe(false)
    })

    it("continues pull even when clone has failures", async () => {
      vi.mocked(cloneMissingProjects).mockReturnValue({ cloned: 1, failed: 2 })

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.sync()

      expect(result.cloned).toEqual({ success: 1, failed: 2 })
    })

    it("continues rebuild even when pull has failures", async () => {
      vi.mocked(pullProject).mockReturnValue({ success: false, message: "dirty" })

      const clonedDir = join(tmpDir, "cloned", "xzf", "order-service")
      mkdirSync(join(clonedDir, ".git"), { recursive: true })

      const config = makeConfig()
      const manager = new ReposManager(config)
      const result = await manager.sync()

      expect(result.pulled.failed).toBeGreaterThan(0)
      expect(result.rebuilt).toBe(true)
    })

    it("uses branchOverride for pull step", async () => {
      const clonedDir = join(tmpDir, "cloned", "xzf", "order-service")
      mkdirSync(join(clonedDir, ".git"), { recursive: true })

      const config = makeConfig()
      const manager = new ReposManager(config)
      await manager.sync({ branchOverride: "develop" })

      expect(vi.mocked(pullProject)).toHaveBeenCalledWith(clonedDir, "develop")
    })

    it("finds cloned projects via manifest + findLocalRepo", async () => {
      const clonedDir = join(tmpDir, "cloned", "xzf", "order-service")
      mkdirSync(join(clonedDir, ".git"), { recursive: true })

      const config = makeConfig()
      const manager = new ReposManager(config)
      await manager.sync()

      expect(vi.mocked(pullProject)).toHaveBeenCalledWith(clonedDir, "master")
    })
  })
})
