#!/usr/bin/env node
/**
 * P1-B1 · 74MB 存量数据一次性搬迁：SQLite → PostgreSQL（COPY），幂等可重跑。
 *
 * 用法:
 *   node scripts/pg-migrate/migrate-data.mjs --db <sqlite> --pg <pg-url>
 *        [--dry-run | --verify-only] [--quarantine] [--report <out.md>] [--sample <n=5>]
 *
 *   --dry-run      校验 + 对账预演（逐表行数/脏清单/装载序），零写入
 *   --verify-only  不装载，只对当前 PG 现状跑对账（重跑幂等验证用）
 *   --quarantine   脏行（不可解析 jsonb / 坏时间戳 / NOT NULL 存 NULL / 布尔域外 /
 *                  FK 孤儿及其级联）整行进隔离清单，其余照常灌；脏清单必进报告
 *
 * 契约 → 实现落点：
 *   1) 幂等：单事务 TRUNCATE <全部表> RESTART IDENTITY CASCADE 后按依赖序全量重灌；
 *      任何一步失败 → 整体回滚，PG 停在上次成功态；任意次重跑结果一致。
 *   2) 带原 id：PG IDENTITY 为 GENERATED BY DEFAULT（B0 铺路，见 db/pg/schema.sql 头注），
 *      COPY 列清单带原主键；提交后对全部 attidentity='d' 列 setval —— 表达式与
 *      db/pg/migrate.ts 同款（COALESCE(MAX(id),0)+1, is_called=false），但动态发现，
 *      未来新增 IDENTITY 表自动覆盖。
 *   3) 类型转换按 B0 映射事实（db/pg/__tests__/schema-parity.test.ts 的
 *      JSONB/BOOL/EPOCH_MS/IDENTITY + isIsoTimestampCol；目标类型以 PG
 *      information_schema 实测为唯一真相源）：
 *        · epoch ms → bigint 直传（值域逐格校验）
 *        · TEXT 时间戳 → timestamptz：装载事务先 `SET timezone='UTC'`（schema.sql
 *          头注的坑：库内混存 toISOString 带 Z 与 datetime('now') 无标记 UTC 串；
 *          带标记串 PG 按标记解析，无标记串按会话 UTC 解读）
 *        · jsonb 列灌前 JSON.parse 校验，不可解析 → 行级清单，绝不静默丢
 *        · 布尔契约 0/1（B0 README 点名 0/1→bool 为最大静默漂移面），域外值进脏清单
 *   4) 表依赖序：对 PG 实际 FK 边（pg_constraint）做 Kahn 拓扑，父先于子；并列按
 *      表名字典序 → 跨运行确定。依据：FK 边两侧一一对由 B0 schema-parity 测试保证。
 *      FK 孤儿灌前全量检出并沿拓扑级联（父行被隔离 → 引用它的子行也成孤儿）。
 *   5) 对账（plan.html P1 判据③「逐表行数 + 抽样列值比对通过，不是跑起来了」）：
 *      ① 逐表行数双式核验：pg = 存活数 且 sqlite 总 = 存活 + 隔离；
 *      ② 每表 sha256 稳定排序抽 ≥5 行（不足取全表），比对全部映射列的归一化值
 *        （时间戳→epoch-ms、JSON→稳定序列化、布尔/整数/浮点归一、文本逐字）。
 *      不一致清单非空 → exit 1。
 *
 * exit code：0 零脏+全等 · 1 失败（严格模式脏数据零写入 / 对账不一致 / COPY 被拒）
 *            · 2 带隔离完成（--quarantine 下对账全等，脏清单见报告 —— 喂 P3）
 *
 * 只读纪律：SQLite 侧 better-sqlite3 readonly，全程零写。
 */
import { createRequire } from 'node:module'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
// pnpm 布局：better-sqlite3/postgres 只装在 packages/server —— 从那里解析（只 import，不触碰其源码）
const require = createRequire(path.join(ROOT, 'packages', 'server', 'index.js'))
const Database = require('better-sqlite3')
const postgres = require('postgres')

const log = (...a) => console.log('[pg-migrate]', ...a)
const sha = (s) => crypto.createHash('sha256').update(s).digest('hex')
const maskPgUrl = (u) => u.replace(/\/\/[^@/]+@/, '//***@')
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const PK_SEP = '\u0001'
const trunc = (v) => { const s = typeof v === 'string' ? v : String(v); return s.length > 140 ? s.slice(0, 140) + '…' : s }
const mdCell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')

// 不搬迁的 SQLite 侧表族（报告 §5 注明依据）：
//   FTS5 虚表家族（PG 占位表无搬迁消费者，pg_search 票在真表上 BM25 重建）
//   *_old_schema_backup_vNN（历史 schema 备份残迹）
const isFtsFamily = (n) => /_fts(_|$)/.test(n)
const isLegacyBackup = (n) => /_old_schema_backup/.test(n)

// ── CLI ─────────────────────────────────────────────────────────────────────
function parseArgs(argv) {
  const out = { sample: 5, dryRun: false, verifyOnly: false, quarantine: false }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--db') out.db = argv[++i]
    else if (a === '--pg') out.pg = argv[++i]
    else if (a === '--dry-run') out.dryRun = true
    else if (a === '--verify-only') out.verifyOnly = true
    else if (a === '--quarantine') out.quarantine = true
    else if (a === '--report') out.report = argv[++i]
    else if (a === '--sample') {
      out.sample = Number(argv[++i])
      if (!Number.isInteger(out.sample) || out.sample < 1) die('--sample 需为正整数')
    } else if (a === '--help' || a === '-h') {
      console.log('用法: migrate-data.mjs --db <sqlite> --pg <url> [--dry-run|--verify-only] [--quarantine] [--report <md>] [--sample <n>]')
      process.exit(0)
    } else die(`未知参数: ${a}`)
  }
  if (!out.db || !out.pg) die('必须提供 --db <sqlite路径> 与 --pg <pg-url>')
  if (out.dryRun && out.verifyOnly) die('--dry-run 与 --verify-only 互斥')
  return out
}
function die(msg) { console.error('[pg-migrate]', msg); process.exit(1) }

// ── PG 元数据（目标类型 = 唯一真相源；B0 parity 保证与 SQLite 侧一致）────────
async function loadPgMeta(sql) {
  const colRows = await sql`
    SELECT table_name, column_name, data_type, is_nullable = 'NO' AS notnull,
           column_default IS NOT NULL AS hasdefault
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name <> 'octopus_schema_version'
      AND table_name NOT LIKE 'pg\\_%' ESCAPE '\\'
      AND table_name NOT LIKE '%\\_fts%' ESCAPE '\\'
      -- P1 B4 票2B-2: information_schema.columns 同样列出视图列（如 llm_calls_costed
      -- 派生视图）—— 视图不可 TRUNCATE/COPY，枚举只认 BASE TABLE。
      AND table_name IN (
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
      )
    ORDER BY table_name, ordinal_position`
  const fkRows = await sql`
    SELECT src.relname AS child, tgt.relname AS parent,
           (SELECT a.attname FROM pg_attribute a WHERE a.attrelid = fc.conrelid AND a.attnum = fc.conkey[1]) AS ccol,
           (SELECT a.attname FROM pg_attribute a WHERE a.attrelid = fc.confrelid AND a.attnum = fc.confkey[1]) AS pcol
    FROM pg_constraint fc
    JOIN pg_class src ON src.oid = fc.conrelid
    JOIN pg_class tgt ON tgt.oid = fc.confrelid
    WHERE fc.contype = 'f'`
  const identRows = await sql`
    SELECT c.relname AS t, a.attname AS c
    FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND a.attidentity = 'd' AND a.attnum > 0
    ORDER BY 1, 2`
  const placeholderRows = await sql`
    SELECT table_name FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name LIKE '%\\_fts%' ESCAPE '\\'`
  const tables = new Map()
  for (const r of colRows) {
    if (!tables.has(r.table_name)) tables.set(r.table_name, [])
    tables.get(r.table_name).push({ name: r.column_name, type: r.data_type, notnull: r.notnull, hasdefault: r.hasdefault })
  }
  const fks = fkRows
    .filter((r) => r.child !== r.parent && tables.has(r.child) && tables.has(r.parent))
    .map((r) => ({ child: r.child, parent: r.parent, ccol: r.ccol, pcol: r.pcol }))
  return { tables, fks, identities: identRows.map((r) => [r.t, r.c]), placeholders: placeholderRows.map((r) => r.table_name) }
}

// Kahn 拓扑排序（父表先装载；并列字典序 —— 依赖序跨运行确定）
function topoOrder(tables, fks) {
  const indeg = new Map([...tables.keys()].map((t) => [t, 0]))
  const children = new Map()
  for (const { child, parent } of fks) {
    indeg.set(child, indeg.get(child) + 1)
    if (!children.has(parent)) children.set(parent, [])
    children.get(parent).push(child)
  }
  const ready = [...indeg.entries()].filter(([, d]) => d === 0).map(([t]) => t).sort()
  const order = []
  while (ready.length) {
    const t = ready.shift()
    order.push(t)
    for (const c of (children.get(t) ?? []).sort()) {
      const d = indeg.get(c) - 1
      indeg.set(c, d)
      if (d === 0) { ready.push(c); ready.sort() }
    }
  }
  if (order.length !== tables.size) throw new Error(`FK 拓扑存在环（排出 ${order.length} / 应 ${tables.size}）`)
  return order
}

// ── 值归一（灌前校验、COPY 编码、对账比较共用同一套语义）─────────────────────
// normValue: pgType + 任一引擎原值 → 跨侧可比的字符串（epoch-ms / 稳定 JSON / 归一文本）。
function normValue(pgType, raw) {
  if (raw === null || raw === undefined) return null
  switch (pgType) {
    case 'timestamp with time zone': {
      if (raw instanceof Date) return String(raw.getTime())
      const iso = String(raw).replace(' ', 'T')
      const marked = /[zZ]$|[+-]\d{2}:?\d{2}$/.test(iso)
      const ms = Date.parse(marked ? iso : iso + 'Z') // 无标记串按 UTC —— 与装载会话 SET timezone='UTC' 同纪律
      return Number.isNaN(ms) ? `UNPARSED:${String(raw)}` : String(ms)
    }
    case 'jsonb':
      return stableJson(typeof raw === 'string' ? safeParse(raw) : raw)
    case 'boolean':
      if (typeof raw === 'boolean') return raw ? '1' : '0'
      return String(Number(raw))
    case 'bigint': case 'integer':
      return String(raw)
    case 'double precision':
      return String(Number(raw))
    default:
      if (Buffer.isBuffer(raw)) return `BLOB:${sha(Buffer.from(raw))}`
      return String(raw)
  }
}
function safeParse(s) { try { return JSON.parse(s) } catch { return { __raw: s } } }
function stableJson(v) {
  if (v === null || v === undefined) return 'null'
  if (Array.isArray(v)) return '[' + v.map(stableJson).join(',') + ']'
  if (typeof v === 'object')
    return '{' + Object.keys(v).sort().map((k) => JSON.stringify(k) + ':' + stableJson(v[k])).join(',') + '}'
  return JSON.stringify(v)
}

// cellIssue: 单格灌前判定。null = 可安全入 PG；否则行级脏原因。
function cellIssue(col, raw) {
  const { type, notnull } = col
  if (raw === null || raw === undefined) return notnull ? 'null-in-notnull' : null
  if (Buffer.isBuffer(raw)) return 'binary-value'
  if (typeof raw === 'string' && raw.includes('\0')) return 'nul-byte'
  switch (type) {
    case 'jsonb':
      if (typeof raw !== 'string') return 'json-col-non-text'
      try { JSON.parse(raw); return null } catch { return 'json-col-unparseable' }
    case 'timestamp with time zone':
      if (typeof raw === 'number') return 'ts-col-numeric-epoch' // EPOCH_MS 列在 B0 映射里是 bigint —— 落 timestamptz 即脏
      if (typeof raw !== 'string') return 'ts-col-non-text'
      {
        const iso = raw.replace(' ', 'T')
        const marked = /[zZ]$|[+-]\d{2}:?\d{2}$/.test(iso)
        return Number.isNaN(Date.parse(marked ? iso : iso + 'Z')) ? 'ts-col-unparseable' : null
      }
    case 'boolean':
      if (typeof raw === 'number' && (raw === 0 || raw === 1)) return null
      if (typeof raw === 'bigint' && (raw === 0n || raw === 1n)) return null
      if (typeof raw === 'string' && (raw === '0' || raw === '1')) return null
      return 'bool-col-not-01'
    case 'integer': case 'bigint': {
      const lo = type === 'bigint' ? -9223372036854775808n : -2147483648n
      const hi = type === 'bigint' ? 9223372036854775807n : 2147483647n
      let v
      if (typeof raw === 'number') {
        if (!Number.isInteger(raw)) return 'int-col-non-integer'
        if (!Number.isSafeInteger(raw)) return 'int-col-unsafe-precision'
        v = BigInt(raw)
      } else if (typeof raw === 'bigint') v = raw
      else if (typeof raw === 'string' && /^-?\d+$/.test(raw)) v = BigInt(raw)
      else return 'int-col-non-numeric'
      return v < lo || v > hi ? 'int-col-out-of-range' : null
    }
    case 'double precision':
      if (typeof raw === 'number') return Number.isFinite(raw) ? null : 'float-col-non-finite'
      if (typeof raw === 'bigint') return null
      if (typeof raw === 'string' && raw.trim() !== '' && Number.isFinite(Number(raw))) return null
      return 'float-col-non-numeric'
    default:
      return null // text：非 BLOB 非 NUL 皆合法
  }
}

// ── 表形状：PG 列 ∩ SQLite 列；主键；双向漂移清单 ────────────────────────────
function tableShape(db, table, pgCols) {
  const sCols = db.prepare(`PRAGMA table_info("${table}")`).all()
  const pk = sCols.filter((c) => c.pk > 0).sort((a, b) => a.pk - b.pk).map((c) => c.name)
  if (pk.length === 0) throw new Error(`${table}: SQLite 无主键 —— 无法定位脏行`)
  const present = new Set(sCols.map((c) => c.name))
  return {
    pk,
    use: pgCols.filter((c) => present.has(c.name)),
    pgOnly: pgCols.filter((c) => !present.has(c.name)),
    sqliteOnly: sCols.filter((c) => !pgCols.some((p) => p.name === c.name)).map((c) => c.name),
  }
}

// ── 校验 pass（只读）：逐表逐格 → 行级脏清单 + 隔离集 + 抽样池 ────────────────
function validateTable(db, table, shape) {
  const rows = db.prepare(`SELECT ${shape.use.map((c) => `"${c.name}"`).join(', ')} FROM "${table}"`).all()
  const problems = []
  const dirty = new Set()
  const seen = new Set()
  // pgOnly 列（PG 有、SQLite 无源）：可空/有 DEFAULT → 装载即 NULL/默认值（合法）；
  // NOT NULL 且无默认 → 每行必脏（无法凭空造值）。
  const pgOnlyNotNull = shape.pgOnly.filter((c) => c.notnull && !c.hasdefault)
  for (const row of rows) {
    const pkVal = shape.pk.map((k) => String(row[k])).join(PK_SEP)
    for (const col of shape.use) {
      const why = cellIssue(col, row[col.name])
      if (why) {
        problems.push({ table, pk: pkVal, column: col.name, kind: why, value: trunc(String(row[col.name])) })
        dirty.add(pkVal)
      }
    }
    for (const col of pgOnlyNotNull) {
      problems.push({ table, pk: pkVal, column: col.name, kind: 'pg-col-no-sqlite-source', value: 'NOT NULL 但 SQLite 无此列' })
      dirty.add(pkVal)
    }
    if (seen.has(pkVal)) {
      problems.push({ table, pk: pkVal, column: shape.pk.join(','), kind: 'duplicate-pk', value: '第二次出现' })
      dirty.add(pkVal)
    }
    seen.add(pkVal)
  }
  const pool = rows.map((r) => shape.pk.map((k) => String(r[k])).join(PK_SEP))
    .filter((p) => !dirty.has(p))
  return { rows, pk: shape.pk, dirty, pool, problems }
}

// FK 孤儿（含级联）：按拓扑序扫 —— 父表 pool 先定型，子表引用不存在的父行即脏；
// 子表自身被隔离又会使其子表成孤儿（同一趟覆盖，因为父先于子）。
function orphanSweep(db, order, shapes, vals, fkByChild) {
  const problems = []
  for (const child of order) {
    const v = vals.get(child)
    const shape = shapes.get(child)
    for (const fk of fkByChild.get(child) ?? []) {
      const pv = vals.get(fk.parent)
      if (!pv) continue // 父表不在 SQLite 源（0 行）→ 子表任何非空引用都是孤儿，parentSet 为空集即可
      const parentSet = new Set(pv.pool)
      for (const row of v.rows) {
        const pkVal = shape.pk.map((k) => String(row[k])).join(PK_SEP)
        if (v.dirty.has(pkVal)) continue
        const fv = row[fk.ccol]
        if (fv === null || fv === undefined) continue
        if (!parentSet.has(String(fv))) {
          v.dirty.add(pkVal)
          v.pool = v.pool.filter((p) => p !== pkVal)
          problems.push({ table: child, pk: pkVal, column: fk.ccol, kind: 'fk-orphan', value: `-> ${fk.parent}.${fk.pcol} = ${trunc(String(fv))}` })
        }
      }
    }
  }
  return problems
}

// ── COPY 文本编码 ────────────────────────────────────────────────────────────
const COPY_ESC = { '\\': '\\\\', '\t': '\\t', '\n': '\\n', '\r': '\\r' }
const escField = (s) => String(s).replace(/[\\\t\n\r]/g, (c) => COPY_ESC[c])
function copyLine(row, cols) {
  const parts = new Array(cols.length)
  for (let i = 0; i < cols.length; i++) {
    const col = cols[i]
    const raw = row[col.name]
    if (raw === null || raw === undefined) { parts[i] = '\\N'; continue }
    let v = raw
    if (col.type === 'timestamp with time zone' && typeof v === 'string') v = v.replace(' ', 'T') // 空格分隔是合法输入，T 更无歧义
    if ((col.type === 'integer' || col.type === 'bigint')) {
      if (typeof v === 'string') v = String(BigInt(v))
      else if (typeof v === 'number') v = Math.trunc(v)
    }
    parts[i] = escField(v)
  }
  return parts.join('\t') + '\n'
}

// ── 装载：手动 BEGIN/COMMIT（max:1 连接），失败整体回滚（幂等的根基） ──────────
// 为什么不用 sql.begin()：begin 的 scope 会对每条查询内部挂 q.catch 记 uncaughtError，
// 即使调用方已处理 COPY_IN_PROGRESS 探测拒绝，COMMIT 时也会被 scope 重抛成失败
// （postgres.js 3.4.9 对照实验 18/18 复现）。max:1 + simple BEGIN/COMMIT 绕开 scope，
// 探测 rejection 归调用方 catch 独享；connection.js:605 保证 max:1 下 BEGIN 合法。
async function loadAll(sql, order, shapes, vals, db, meta) {
  const loaded = new Map()
  await sql`SET timezone = 'UTC'`      // schema.sql 头注的坑：无标记 UTC 串按会话时区解读 —— 锁 UTC
  await sql`SET statement_timeout = 0` // 搬迁连接豁免查询级超时（B0 pool.ts 头注：server 级刻意不设）
  await sql`BEGIN`
  try {
    await sql.unsafe(
      `TRUNCATE TABLE ${[...shapes.keys(), ...meta.placeholders].map((t) => `"${t}"`).join(', ')} RESTART IDENTITY CASCADE`)
    for (const table of order) {
      const shape = shapes.get(table)
      const v = vals.get(table)
      if (!v.rows.length) { loaded.set(table, 0); continue } // 空表/缺源表：0 行 COPY 省掉（也避免空列清单）
      const colList = shape.use.map((c) => `"${c.name}"`).join(', ')
      const stream = await sql.unsafe(`COPY "${table}" (${colList}) FROM STDIN (FORMAT text)`).writable()
      let n = 0
      let buf = []
      for (const row of v.rows) {
        const pkVal = shape.pk.map((k) => String(row[k])).join(PK_SEP)
        if (v.dirty.has(pkVal)) continue
        buf.push(copyLine(row, shape.use))
        n++
        if (buf.length >= 1000) { stream.write(buf.join('')); buf = [] }
      }
      if (buf.length) stream.write(buf.join(''))
      stream.end()
      await waitCopySettled(sql, stream, table)
      loaded.set(table, n)
      log(`  COPY ${table}: ${n} 行（隔离 ${v.rows.length - n}）`)
    }
    await sql`COMMIT`
  } catch (e) {
    await sql`ROLLBACK`.catch(() => {})
    throw e
  }
  return loaded
}
// COPY 完成判定（postgres.js 3.4.9 实测纪律）：
//   · 唯一成功信号 = stream 的 'finish'（= COPY 的 CommandComplete 已被连接层消费）。
//   · PG 拒 COPY 时 finish 永不到达 → 探测语句区分：COPY_IN_PROGRESS=数据还在刷；
//     25P02=被拒（大声失败，外层 ROLLBACK）。autoDestroy=false 掐掉 finish 后的杂散 CopyFail。
async function waitCopySettled(sql, stream, table) {
  stream.autoDestroy = false
  const done = new Promise((res) => stream.once('finish', () => res(true)))
  const deadline = Date.now() + 600_000
  for (;;) {
    const ok = await Promise.race([done, sleep(200).then(() => false)])
    if (ok === true) return
    try { await sql`SELECT 1` }
    catch (e) {
      if (e.code === 'COPY_IN_PROGRESS') { /* CopyData 仍在刷出，继续等 finish */ }
      else if (e.code === '25P02') throw new Error(`${table}: COPY 被 PG 拒绝（前置校验漏网行）—— 事务回滚`)
      else throw e
    }
    if (Date.now() > deadline) throw new Error(`${table}: COPY 等待超时（>10min）`)
  }
}

// IDENTITY 序列对齐（与 db/pg/migrate.ts setval 表达式同款；动态发现全部 attidentity='d'）
async function syncIdentitySequences(sql, identities) {
  for (const [t, c] of identities)
    await sql.unsafe(
      `SELECT setval(pg_get_serial_sequence('${t}', '${c}'), ` +
      `(SELECT COALESCE(MAX("${c}"), 0) + 1 FROM "${t}"), false)`)
  return identities.length
}

// ── 对账 ─────────────────────────────────────────────────────────────────────
async function reconcile(sql, db, order, shapes, vals, sampleN, sSet) {
  const rowsOut = []
  const mismatches = []
  for (const table of order) {
    const shape = shapes.get(table)
    const v = vals.get(table)
    const quarantined = v.rows.length - v.pool.length
    const sN = sSet.has(table) ? db.prepare(`SELECT count(*) AS c FROM "${table}"`).get().c : 0
    let pN
    try { pN = Number((await sql.unsafe(`SELECT count(*)::bigint AS c FROM "${table}"`))[0].c) }
    catch { pN = -1 }
    // 双式核验：pg=存活数 且 sqlite总=存活+隔离（存活+隔离 恒等于 sN 时第二式防「sqlite 侧读挂」）
    const rowsOk = pN === v.pool.length && sN === v.rows.length
    rowsOut.push({ table, sqlite: sN, quarantined, loaded: v.pool.length, pg: pN, ok: rowsOk })
    if (!rowsOk)
      mismatches.push({ table, pk: '(表级)', column: '*', kind: 'row-count',
        sqlite: `存活 ${v.pool.length} / 总 ${v.rows.length} / 隔离 ${quarantined}`, pg: String(pN) })
    const picked = topSample(v.pool, sampleN)
    let cmp = 0
    for (const pkVal of picked) {
      const sRow = fetchByPkSqlite(db, table, shape.pk, pkVal)
      if (!sRow) { mismatches.push({ table, pk: pkVal, column: '*', kind: 'sqlite-row-missing', sqlite: '?', pg: '?' }); continue }
      const pRow = await fetchByPkPg(sql, table, shape.pk, pkVal)
      if (!pRow) { mismatches.push({ table, pk: pkVal, column: '*', kind: 'pg-row-missing', sqlite: 'row', pg: 'MISSING' }); continue }
      for (const col of shape.use) {
        cmp++
        const sv = normValue(col.type, sRow[col.name])
        const pv = normValue(col.type, pRow[col.name])
        if (sv !== pv)
          mismatches.push({ table, pk: pkVal, column: col.name, kind: 'value', sqlite: trunc(String(sv)), pg: trunc(String(pv)) })
      }
    }
    log(`  对账 ${table}: 总${v.rows.length} 隔离${quarantined} pg${pN}${rowsOk ? ' ✓' : ' ✗'} · 抽样 ${picked.length} 行/${cmp} 格`)
  }
  return { rowsOut, mismatches }
}
function topSample(pool, n) {
  return [...pool].map((v) => ({ v, h: sha(String(v)) }))
    .sort((a, b) => (a.h < b.h ? -1 : a.h > b.h ? 1 : 0))
    .slice(0, n).map((x) => x.v)
}
function splitPk(pkVal, len) {
  const parts = String(pkVal).split(PK_SEP)
  return parts.length === len ? parts : null
}
function fetchByPkSqlite(db, table, pk, pkVal) {
  const parts = splitPk(pkVal, pk.length)
  if (!parts) return null
  const where = pk.map((k) => `"${k}" = ?`).join(' AND ')
  return db.prepare(`SELECT * FROM "${table}" WHERE ${where} LIMIT 1`).get(...parts) ?? null
}
async function fetchByPkPg(sql, table, pk, pkVal) {
  const parts = splitPk(pkVal, pk.length)
  if (!parts) return null
  const where = pk.map((k, i) => `"${k}" = $${i + 1}`).join(' AND ')
  const rows = await sql.unsafe(`SELECT * FROM "${table}" WHERE ${where} LIMIT 1`, parts)
  return rows[0] ?? null
}

// 装载后 PG 侧 FK 复核（双保险 + 报告证据：PG 约束视角 0 孤儿）
async function fkCheck(sql, fks) {
  const out = []
  for (const { child, parent, ccol, pcol } of fks) {
    const orphans = await sql.unsafe(
      `SELECT ch."${ccol}" AS v FROM "${child}" ch WHERE ch."${ccol}" IS NOT NULL
         AND NOT EXISTS (SELECT 1 FROM "${parent}" p WHERE p."${pcol}" = ch."${ccol}") LIMIT 50`)
    for (const o of orphans)
      out.push({ table: child, pk: String(o.v), column: ccol, kind: 'fk-orphan-in-pg', value: `-> ${parent}.${pcol}` })
  }
  return out
}

// ── 漂移观察（只报不丢）──────────────────────────────────────────────────────
function collectNotes(db, shapes, sqliteTableNames) {
  const notes = []
  for (const [table, shape] of shapes) {
    for (const c of shape.pgOnly)
      notes.push({ table, kind: 'pg-col-no-sqlite-source',
        detail: `${c.name}${c.notnull && !c.hasdefault ? '（NOT NULL 无默认 —— 该行全量进脏清单）' : c.hasdefault ? '（装载取 PG 默认值）' : '（装载为 NULL）'}` })
    for (const c of shape.sqliteOnly) {
      const n = db.prepare(`SELECT count(*) AS c FROM "${table}" WHERE "${c}" IS NOT NULL`).get().c
      notes.push({ table, kind: 'sqlite-col-not-in-pg', detail: `${c}：非空 ${n} 行${n > 0 ? '（该列不随迁 —— B0 schema 无此列）' : '（全 NULL，无损）'}` })
    }
  }
  for (const t of sqliteTableNames)
    if (!shapes.has(t))
      notes.push({ table: t, kind: 'sqlite-table-not-migrated',
        detail: isFtsFamily(t) ? 'FTS5 家族 —— pg_search 票在真表重建，无搬迁消费者'
          : isLegacyBackup(t) ? '历史 schema 备份表' : 'PG schema 无此表' })
  return notes
}

// ── 报告 ─────────────────────────────────────────────────────────────────────
function renderReport(ctx) {
  const { cli, userVersion, order, shapes, problems, rowsOut, mismatches, notes, identities,
    placeholders, startedAt, finishedAt, fkAfter, loaded } = ctx
  const L = []
  L.push('# P1-B1 · 74MB 数据搬迁对账报告（SQLite → PG COPY）')
  L.push('')
  L.push(`- 时间: ${startedAt.toISOString()} → ${finishedAt.toISOString()}`)
  L.push(`- 源: \`${cli.db}\` · SQLite user_version = ${userVersion} · readonly`)
  L.push(`- 目标: \`${maskPgUrl(cli.pg)}\``)
  L.push(`- 模式: ${cli.dryRun ? '**dry-run（零写入预演）**' : cli.verifyOnly ? '**verify-only（只对现状不装载）**' : cli.quarantine ? '实灌 + `--quarantine`（脏行放行隔离）' : '实灌（严格模式，脏即中止）'}`)
  L.push(`- 结论: **${ctx.verdict}** · exit ${ctx.exitCode}`)
  L.push('')
  L.push(`搬迁 ${shapes.size} 表；装载序 = PG 实际 FK 边（pg_constraint）Kahn 拓扑（父先于子，并列字典序；依据：FK 边两侧一致性由 B0 schema-parity 测试证明）：`)
  L.push('')
  L.push('```')
  L.push(order.join(' → '))
  L.push('```')
  L.push('')
  L.push('同步清空的 FTS 占位表（不搬迁）: ' + (placeholders.length ? placeholders.map((p) => `\`${p}\``).join(' · ') : '（无）'))
  L.push('')
  L.push('## §1 逐表行数（sqlite vs pg）')
  L.push('')
  L.push('| 表 | sqlite 总 | 隔离 | 应落库 | pg 实测 | 一致 |')
  L.push('|---|---:|---:|---:|---:|:---:|')
  for (const r of rowsOut)
    L.push(`| ${r.table} | ${r.sqlite} | ${r.quarantined} | ${r.loaded} | ${r.pg === null ? '—(本次未写)' : r.pg} | ${r.ok === null ? '—' : r.ok ? '✓' : '✗'} |`)
  L.push('')
  L.push('## §2 抽样列值比对')
  L.push('')
  if (!rowsOut.some((r) => r.ok !== null)) L.push('本次未对目标库做对账（dry-run 或严格模式中止态）。')
  else if (!mismatches.length)
    L.push(`全等 —— 每表 sha256 稳定排序抽 ${cli.sample} 行（不足取全表）× 全部映射列：时间戳两侧 epoch-ms、JSON 稳定序列化（键排序）、布尔 0/1↔bool、整数/浮点按类型、文本逐字，逐一相等。`)
  else {
    L.push(`**不一致 ${mismatches.length} 条 —— 判红**`)
    L.push('')
    L.push('| 表 | 主键 | 列 | 类型 | sqlite 归一 | pg 归一 |')
    L.push('|---|---|---|---|---|---|')
    for (const m of mismatches) L.push(`| ${m.table} | ${mdCell(m.pk)} | ${m.column} | ${m.kind} | ${mdCell(m.sqlite)} | ${mdCell(m.pg)} |`)
  }
  L.push('')
  L.push(`## §3 脏数据清单（${problems.length} 条）—— 喂 P3 quarantine 设计`)
  L.push('')
  if (!problems.length) L.push('零脏数据：jsonb 全部可 JSON.parse；timestamptz 无数字/坏格式混入；NOT NULL 列无 NULL；布尔列仅 0/1；主键无重复；FK 无孤儿。')
  else {
    const groups = new Map()
    for (const p of problems) {
      const k = `${p.table} · ${p.column} · ${p.kind}`
      if (!groups.has(k)) groups.set(k, [])
      groups.get(k).push(p)
    }
    for (const [k, list] of [...groups.entries()].sort()) {
      L.push(`- **${k}** × ${list.length}${cli.quarantine ? '（已隔离，不入库）' : cli.dryRun ? '（dry-run 仅预演）' : ''}`)
      for (const p of list.slice(0, 10)) L.push(`    - \`${mdCell(p.pk)}\` = ${mdCell(p.value)}`)
      if (list.length > 10) L.push(`    - …其余 ${list.length - 10} 条见 ${ctx.jsonPath ?? 'JSON 清单'}`)
    }
  }
  L.push('')
  L.push('## §4 装载后 PG 侧 FK 复核')
  L.push('')
  if (fkAfter === null) L.push('未装载（dry-run 或脏数据中止），跳过。')
  else if (!fkAfter.length) L.push('0 孤儿 —— PG 约束视角全链路引用完整。')
  else { L.push(`**${fkAfter.length} 条孤儿**`); for (const f of fkAfter) L.push(`- ${f.table}.${f.column} \`${mdCell(f.pk)}\` ${f.value}`) }
  L.push('')
  L.push('## §5 发现与边界')
  L.push('')
  L.push('- IDENTITY 带原 id 装载 + setval 对齐: ' + (identities.length ? identities.map(([t, c]) => `\`${t}.${c}\``).join(' · ') : '（无 IDENTITY 列）'))
  if (loaded) L.push(`- 实际 COPY 落库行数合计: ${[...loaded.values()].reduce((a, b) => a + b, 0)}`)
  L.push('- FTS 占位表不搬迁（无消费者；pg_search 票在真表上 BM25 重建）；装载时同步清空防残留。')
  for (const n of notes) L.push(`- [${n.kind}] ${n.table}: ${n.detail}`)
  L.push('')
  return L.join('\n') + '\n'
}

// ── 主流程 ───────────────────────────────────────────────────────────────────
async function main() {
  const cli = parseArgs(process.argv.slice(2))
  const startedAt = new Date()
  const dbPath = path.resolve(cli.db)
  if (!fs.existsSync(dbPath)) die(`SQLite 库不存在: ${dbPath}`)
  const db = new Database(dbPath, { readonly: true, fileMustExist: true })
  const userVersion = db.pragma('user_version', { simple: true })
  const sql = postgres(cli.pg, { max: 1, onnotice: () => {} })

  try {
    const meta = await loadPgMeta(sql)
    if (!meta.tables.size) throw new Error('PG 侧 public schema 无业务表 —— 先跑 B0 迁移器（applyPgSchema）')
    const order = topoOrder(meta.tables, meta.fks)
    const fkByChild = new Map()
    for (const fk of meta.fks) {
      if (!fkByChild.has(fk.child)) fkByChild.set(fk.child, [])
      fkByChild.get(fk.child).push(fk)
    }
    log(`PG ${meta.tables.size} 张搬迁表 · FK ${meta.fks.length} 边 · IDENTITY ${meta.identities.length} · 装载序 ${order.length}`)

    const shapes = new Map()
    const vals = new Map()
    const sqliteTableNames = db.prepare(
      "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map((r) => r.name)
    const sSet = new Set(sqliteTableNames)

    const problems = []
    for (const table of order) {
      const pgCols = meta.tables.get(table)
      if (!sSet.has(table)) {
        // 源库里不存在的 PG 表（如合成夹具/真库缺表）：装载后即 0 行；只需登记 pgOnly 漂移
        shapes.set(table, { pk: [], use: [], pgOnly: pgCols.filter((c) => c.notnull && !c.hasdefault), sqliteOnly: [] })
        vals.set(table, { rows: [], pk: [], dirty: new Set(), pool: [], problems: [] })
        continue
      }
      const shape = tableShape(db, table, pgCols)
      shapes.set(table, shape)
      vals.set(table, validateTable(db, table, shape))
    }
    for (const table of order) problems.push(...vals.get(table).problems)
    problems.push(...orphanSweep(db, order, shapes, vals, fkByChild))

    const notes = collectNotes(db, shapes, sqliteTableNames)

    if (problems.length) {
      log(`校验发现 ${problems.length} 条脏数据${cli.quarantine ? '（--quarantine：整行进隔离清单，其余照常灌）' : '（严格模式：中止，零写入）'}`)
      for (const p of problems.slice(0, 30)) log(`  - ${p.table} \`${p.pk}\` ${p.column} ${p.kind} :: ${p.value}`)
      if (problems.length > 30) log(`  …其余 ${problems.length - 30} 条见报告`)
    }

    // 严格中止只约束「本要写库」的实灌：dry-run / verify-only 皆零写入，脏清单进报告即可
    const strictAbort = problems.length > 0 && !cli.quarantine && !cli.dryRun && !cli.verifyOnly
    let loaded = null
    if (!strictAbort && !cli.dryRun && !cli.verifyOnly) {
      loaded = await loadAll(sql, order, shapes, vals, db, meta)
      const synced = await syncIdentitySequences(sql, meta.identities)
      log(`setval 对齐 ${synced} 个 IDENTITY 序列`)
    }

    let rowsOut, mismatches, fkAfter
    if (cli.dryRun || strictAbort) {
      // 预演/中止：目标库是上一次状态，对它做行数核对无意义 —— 只报本次「应落库」口径
      rowsOut = order.map((t) => {
        const v = vals.get(t)
        return { table: t, sqlite: v.rows.length, quarantined: v.rows.length - v.pool.length, loaded: v.pool.length, pg: null, ok: null }
      })
      mismatches = []
      fkAfter = null
    } else {
      const rec = await reconcile(sql, db, order, shapes, vals, cli.sample, sSet)
      rowsOut = rec.rowsOut
      fkAfter = await fkCheck(sql, meta.fks)
      mismatches = [...rec.mismatches, ...fkAfter]
    }
    if (mismatches.length) {
      log(`对账不一致 ${mismatches.length} 条 —— 判红`)
      for (const m of mismatches.slice(0, 20)) log(`  ! ${m.table} \`${m.pk}\` ${m.column} ${m.kind}: sqlite=${m.sqlite} pg=${m.pg}`)
    }

    const quarantined = [...vals.values()].reduce((a, v) => a + (v.rows.length - v.pool.length), 0)
    const verdict = strictAbort ? '中止（脏数据，零写入）'
      : cli.dryRun ? `dry-run 预演完成${problems.length ? `（脏 ${problems.length} 条）` : ''}`
      : mismatches.length ? '失败（对账不一致清单非空）'
        : quarantined ? `带隔离完成（隔离 ${quarantined} 行）` : '完全一致'
    const exitCode = strictAbort || mismatches.length ? 1
      : (problems.length || quarantined) ? 2 : 0

    const ctx = { cli, userVersion, order, shapes, problems, rowsOut, mismatches, notes,
      identities: meta.identities, placeholders: meta.placeholders, startedAt, finishedAt: new Date(),
      fkAfter, loaded, verdict, exitCode, jsonPath: cli.report ? cli.report.replace(/\.md$/, '') + '.quarantine.json' : null }
    const md = renderReport(ctx)
    if (cli.report) {
      fs.mkdirSync(path.dirname(path.resolve(cli.report)), { recursive: true })
      fs.writeFileSync(cli.report, md)
      fs.writeFileSync(ctx.jsonPath, JSON.stringify({ generatedAt: new Date().toISOString(), mode: cli, problems, mismatches, fkAfter }, null, 1))
      log(`报告 → ${cli.report}`)
      log(`JSON → ${ctx.jsonPath}`)
    } else process.stdout.write('\n' + md)
    log(`SUMMARY mode=${cli.dryRun ? 'dry-run' : cli.verifyOnly ? 'verify-only' : cli.quarantine ? 'quarantine' : 'strict'} problems=${problems.length} quarantined=${quarantined} mismatches=${mismatches.length} verdict=${verdict} exit=${exitCode}`)
    process.exitCode = exitCode
  } finally {
    await sql.end({ timeout: 5 }).catch(() => {})
    db.close()
  }
}
main().catch((e) => { console.error('[pg-migrate] FATAL', e?.code ? `${e.code}: ${e.message}` : e, '\n', e?.stack?.split('\n').slice(0, 8).join('\n')); process.exit(1) })